// Seed batch 3/5 — Układ ruchu człowieka
// Budowa stawu (2) + Tkanka mięśniowa (8) = 10 questions

const https = require('https')
const KEY = process.env.SUPABASE_SERVICE_ROLE_KEY || ''
const TOPIC = '42b3edde-2027-4bbb-8a90-38568031d9b0'

const S = {
  staw:    '4b0f4c0b-7c18-48c4-9599-a7f7d619db94',
  miesien: '5837158f-0ba4-47e2-8f59-4d8888b5feab',
}

const questions = [

  // ── BUDOWA STAWU (2) ──────────────────────────────────────────────────────
  {
    topic_id: TOPIC, subtopic_id: S.staw, question_type: 'single',
    question_text: 'Zakres ruchomości stawu zależy od jego kształtu i struktury. Który opis POPRAWNIE wyjaśnia biomechanikę stawu barkowego i jego podatność na urazy?',
    options: [
      { id: 'A', text: 'STAW BARKOWY (art. humeri): kulisty (3 osie) → największy zakres ruchomości; STABILNOŚĆ: (1) statyczna: glenoid labrum (fibrocartilage, ↑kontakt 60→120%); więzadła glenohumeralne (SGHL, MGHL, AIGHL = inferior, najważniejsze w zewnętrznej rotacji); więzadło kruczo-ramienne (coracohumeral); (2) dynamiczna: rotator cuff (SITS: supraspinatus, infraspinatus, teres minor, subscapularis) → centruje główkę w panewce; depressory: infraspinatus + teres minor (↓główki przy unoszeniu); PODDACH (subacromial space): przestrzeń między wyrostkiem barkowym (acromion) + więzadłem kruczawo-barkowym a górną powierzchnią rotator cuff → impingement', is_correct: true },
      { id: 'B', text: 'Staw barkowy jest najstabilniejszym i najtrudniej ulegającym zwichnięciu stawem ciała; glenoid (panewka łopatkowa) jest głęboka i głębiej niż acetabulum (panewka biodrowa); stabilność dynamiczna zależy od mięśni kończyny dolnej; supraspin jest zginaczem łokcia (nie mięśniem rotator cuff); acromion leży poniżej główki kości ramiennej; AIGHL (anterior inferior glenohumeral ligament) nie ma znaczenia w stabilizacji stawu barkowego', is_correct: false },
      { id: 'C', text: 'Staw barkowy ma najmniejszy zakres ruchomości spośród wszystkich stawów; glenoid labrum zmniejsza obszar kontaktu (nie zwiększa); stabiliizację zapewniają wyłącznie więzadła kostne (bez mięśni); rotator cuff składa się z 5 mięśni (SIPTS); subscapularis jest mięśniem rotującym zewnętrznie; impingement syndrome polega na ucisku rotator cuff pod kością udową', is_correct: false },
      { id: 'D', text: 'Więzadło kruczawo-obojczykowe jest głównym stabilizatorem stawu ramiennego (nie glenohumeralne); rotator cuff produkuje maź stawową; labrum (obrąbek) jest strukturą kostną (nie fibrocartilaginous); glenoid jest głębszy niż acetabulum; wyrostek barkowy (acromion) stabilizuje głowę kości udowej; SITS to skrót od czterech mięśni zginaczy łokcia', is_correct: false },
    ],
    correct_answer: ['A'],
    explanation: 'STAW BARKOWY KLINICZNE: IMPINGEMENT SYNDROME: Neer: outlet impingement (supraspinatus pod acromionem); typy acromion: I (flat) → II (curved) → III (hooked) → ↑ryzyko impingement; Hawkins-Kennedy test: wewnętrzna rotacja przy 90° zgięcia → ból; leczenie: fizyko, NSAID, iniekcja GKS → artroskopowa sub-acromial decompression (acromioplastyka); ROTATOR CUFF TEARS: degeneracyjne (> 40 lat) vs traumatyczne; częściowe (partial thickness) vs pełne (full thickness); pęknięcie supraspinatus: ból przy zewnętrznej rotacji + abdukcji; empty can test (Jobe); MRI: gold standard; leczenie: zachowawcze (fizjo) → artroskopowa naprawa (do 6 tyg. od urazu); ZAMROŻONE RAMIĘ (frozen shoulder, adhesive capsulitis): ↑zapalenie torebki → ↓elastyczność → ↓ROM; 3 fazy: freezing (ból) + frozen (sztywność) + thawing (poprawa); 1–3 lata naturalny przebieg; leczenie: fizjo + GKS + MUA (manipulation under anesthesia) + artroskopowe uwolnienie; ACROMIOCLAVICULAR JOINT (ACJ, staw barkowo-obojczykowy): urazy przy upadku na bark; Rockwood classification I–VI; typ I–II: zachowawcze; III: kontrowersyjne; IV–VI: operacyjne.',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },
  {
    topic_id: TOPIC, subtopic_id: S.staw, question_type: 'multiple',
    question_text: 'Które z poniższych stwierdzeń POPRAWNIE opisują staw skokowo-goleniowy (górny staw skokowy) i skręcenia stawu skokowego? (zaznacz wszystkie prawdziwe)',
    options: [
      { id: 'A', text: 'STAW SKOKOWO-GOLENIOWY (talocrural, upper ankle joint): zawiasowy (ginglimus, 1 oś); kości: troczek (talus) + piszczel (tibia) + strzałka (fibula); "tenon and mortise": talus wchodzi w widełki (mortise) tibiofibular; RUCH: zgięcie podeszwowe (plantarflexion 50°) + grzbietowe (dorsiflexion 20°); stabilizacja: (1) PRZYŚRODKOWA: więzadło trójstronne (lig. deltoideum) = anterior tibiotalar + tibiocalcaneal + tibionavicular + posterior tibiotalar → bardzo silne; (2) BOCZNA: ATFL (anterior talofibular) + CFL (calcaneofibular) + PTFL (posterior talofibular); ATFL: najsłabsze, najczęściej uszkadzane', is_correct: true },
      { id: 'B', text: 'SKRĘCENIE STAWU SKOKOWEGO: najczęstszy uraz narządu ruchu; (1) BOCZNE (lateral): inversion + plantarflexion → ATFL (85%) ± CFL (65%); grading: I (mikronaderwanie, bez niestabilności) → II (częściowe) → III (całkowite zerwanie + niestabilność); testy: anterior drawer test (ATFL), talar tilt (CFL); Ottawa ankle rules: RTG tylko gdy ból w "bone zones" + nie chodzi; leczenie: PRICE (protection, rest, ice, compression, elevation) → rehab → operacyjne (Broström repair) przy nawracającej niestabilności; (2) PRZYŚRODKOWE (medial, eversion): rzadziej; uszkodzenie deltoid', is_correct: true },
      { id: 'C', text: 'DOLNY STAW SKOKOWY (subtalar joint, talocalcaneal): ruch: pronacja + supinacja (inwersja/ewersja stopy); kliniczne: pes planus (płaskostopie) ↔ nadmierna pronacja; flatfoot (PTTD = posterior tibial tendon dysfunction): ↓mięsień piszczelowy tylny → "too many toes" sign (widok od tyłu: więcej niż 2. palce widoczne bocznie) + ból przyśrodkowy stawu skokowego; leczenie: wkładki ortopedyczne + fizyko → artroskopia (subtalar arthrodesis); ACHILLES TENDON: przyczep na guzku piętowym (calcaneal tuberosity); najgrubsze i najsilniejsze ścięgno w ciele; mięśnie: m. trójgłowy łydki (gastrocnemius + soleus) + m. płaszczkowaty', is_correct: true },
      { id: 'D', text: 'Więzadło trójstronne (deltoid) jest najczęściej uszkadzanym więzadłem stawu skokowego; staw skokowo-goleniowy to staw kulisty (3 osie); ATFL jest silniejszym więzadłem bocznym niż PTFL; inwersja + plantarflexion uszkadza typowo więzadła przyśrodkowe; Ottawa ankle rules zalecają RTG u wszystkich pacjentów ze skręceniem; dolny staw skokowy jest stawem zawiasowym umożliwiającym tylko zginanie grzbietowe i podeszwowe', is_correct: false },
    ],
    correct_answer: ['A', 'B', 'C'],
    explanation: '(A) ANKLE MORTISE STABILITY: normalne: talus snugly fits mortise; pronacja → poszerzenie widełek → niestabilność; MAISONNEUVE FRACTURE: rotacja zewnętrzna → przerwanie deltoid + syndesmoza + proksymalna fibula fracture; ważne: fibula fracture wysoko (poza RTG stawu); ból kolana przy urazie stawu skokowego → RTG fibula proksymalnie; (B) ANKLE REHABILITATION: PRICE → proprioception exercises → peroneal strengthening → functional exercises → sport-specific; ANKLE INSTABILITY: chronic lateral ankle instability (CLAI): > 3 skręcenia / "giving way"; Broström-Gould procedure: anatomiczna naprawa ATFL + CFL; wyniki: 85–90% powrót do sportu; (C) ACHILLES TENDON PATHOLOGY: Achilles tendinopathy: tendinosis (dystrofia ścięgna) + peritendinitis; biegacze; Royal London Hospital test + arc sign; leczenie: ekscentryczne ćwiczenia (Alfredson protocol) → PRP → operacja (fasciotomy); ACHILLES TENDON RUPTURE: 30–50 lat, rekreacyjni sportowcy ("weekend warriors"); Thompson test: ucisk łydki → brak plantarflexion stopy = zerwanie; MSU (badanie ultrasonograficzne) lub MRI; leczenie: operacyjne (direct repair) vs zachowawcze (brace, non-weight-bearing) → równoważne wyniki; D — Fałsz: deltoid: RZADZIEJ (medial skręcenie rzadkie); zawiasowy (1 oś); ATFL: NAJSŁABSZE; inwersja + plantar: boczne (nie przyśrodkowe); Ottawa: tylko przy "bone zones" (nie wszyscy); dolny staw skokowy: stawowy triodalny/płaski → INwersja/ewersja (nie zawiasowy).',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },

  // ── TKANKA MIĘŚNIOWA (8) ─────────────────────────────────────────────────
  {
    topic_id: TOPIC, subtopic_id: S.miesien, question_type: 'single',
    question_text: 'Tkanka mięśniowa dzieli się na trzy typy. Który opis POPRAWNIE charakteryzuje mięśień szkieletowy (poprzecznie prążkowany, skeletal muscle)?',
    options: [
      { id: 'A', text: 'MIĘSIEŃ SZKIELETOWY: wielojądrowe włókna (syncytium, jądra peryferie → pod sarkolemą); długość: 1 mm – 30 cm; średnica: 10–100 μm; HIERARCHIA BUDOWY: mięsień → pęczki (otoczone perimysium) → włókna (otoczone endomysium); cały mięsień: epimysium; SARKOMERA (jednostka kurczliwa): Z-disc → A-band (miozynowe grube filmy) + I-band (aktynowe cienkie) + H-zone (tylko miozyna, brak aktyny) + M-line (środek A-bandy, sarkomerowe białka porządkujące: myomesin, M-protein); TYPY WŁÓKIEN: I (slow-twitch, czerwone): ↑mioglobina + ↑mitochondria + ↑lipidy → aerobowe; IIa (fast-twitch, intermediate): miks; IIx (IIb): szybkie + anaerobowe + ↑glikogen + ↓mitochondria', is_correct: true },
      { id: 'B', text: 'Mięsień szkieletowy jest mononuklearny (1 jądro); jądra komórkowe leżą centralnie (środkowo) w miocycie; mięsień sercowy jest tkanką wielojądrową (syncytium); I-band zawiera wyłącznie grube filamenty miozyny; H-zone jest obszarem nakładania się aktyny i miozyny; Z-disc jest środkiem H-zone; mięśnie typu I (slow-twitch) mają mało mitochondriów i bogactwo glikogenu', is_correct: false },
      { id: 'C', text: 'Mięsień szkieletowy jest jednojądrowy jak mięsień sercowy; epimysium otacza poszczególne włókna mięśniowe; perimysium otacza cały mięsień; I-band zawiera zarówno aktynę jak i miozynę; M-line jest linią podziału sarkomery (jak Z-disc); włókna IIx/IIb są przeznaczone głównie do długotrwałych wysiłków wytrzymałościowych; mioglobina nie jest obecna w mięśniach szkieletowych', is_correct: false },
      { id: 'D', text: 'Sarkomer to jednostka od Z-disc do M-line (nie Z-disc do Z-disc); A-band zawiera wyłącznie cienkie filamenty aktyny; mięśnie poprzecznie prążkowane mają jądra w centrum włókna (jak mięsień gładki); perimysium jest zewnętrzną otoczką całego mięśnia; włókna mięśniowe IIa są wyłącznie anaerobowe; mioglobina transportuje CO₂ (nie tlen)', is_correct: false },
    ],
    correct_answer: ['A'],
    explanation: 'SARKOMERA — BIAŁKA STRUKTURALNE: AKTYNA: G-aktynamonomer → F-aktyna (polimer, 2 nici skręcone) → thin filament; tropomiozyna: leży wzdłuż F-aktyny, blokuje miejsca wiążące miozynę w spoczynku; troponina kompleks (Tn): TnI (inhibitor) + TnC (Ca²⁺ sensor) + TnT (wiąże tropomiozynę); MIOZYNA II: grube filamenty; główki myozynowe (S1): ATPase + aktyno-wiążące; TITINA (titin, conectina): elastyczne "sprężyny" Z-disc → M-line; pasywna elastyczność + sarkomery centrowanie; negatywna rola w kardiomiopatii (titin truncation = TTNtv → DCM); NEBULIN: rejestr cienkiego filamentu (reguluje długość thin filamentin); MYOMESIN: M-line: utrzymuje grube filamenty w równoległości; DYSTROFINA: połącze aktyna-sarkolema-ECM (dystroglikan-sarkoglikan); utrata: DMD (Duchenne) → niestabilność błony + nekroza włókien; NEBULIN-NEMALINE: mutacja nebulin → nemaline myopathy (nić-ciała w biopsji mięśnia); TIPY WŁÓKIEN — KLINICZNE: typ I przeważa: biegacze maratonowi (> 80%); typ IIx: sprinterzy, ciężarowcy; trening: wytrzymałościowy → ↑mitochondria + ↑kapilaryzacja + ↑rozmiar typ I; siłowy → ↑rozmiar IIx (hypertrofia) + konwersja IIb → IIa.',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },
  {
    topic_id: TOPIC, subtopic_id: S.miesien, question_type: 'multiple',
    question_text: 'Które z poniższych stwierdzeń POPRAWNIE opisują mięsień sercowy (myocardium) i mięsień gładki? (zaznacz wszystkie prawdziwe)',
    options: [
      { id: 'A', text: 'MIĘSIEŃ SERCOWY (myocardium): komórki = kardiomiocyty: (1) JEDNO LUB DWIE JĄDRA (CENTRALNIE!); (2) poprzeczne prążkowanie (sarkomery jak w szkieletowym); (3) WSTAWKI (intercalated discs): gap junctions (connexin 43, Cx43) → przekazywanie AP między komórkami (syncytium FUNKCJONALNE) + desmosomy (mechaniczne sprzężenie); (4) AUTOMATYZM (spontaniczne AP, rozrusznik = sinus node, węzeł zatokowoprzedsionkowy); (5) refrakcja absolutna długa (serce nie może tężyć = summacja niemożliwa) → bezpieczeństwo pompowania; ZAOPATRZENIE W TLEN: gęsta sieć kapilar + ↑mitochondria (25–35% obj.) + mioglobina; 100% aerobowe (FFA 60%, glukoza/mleczan 40%)', is_correct: true },
      { id: 'B', text: 'MIĘSIEŃ GŁADKI (smooth muscle): wrzecionowate mononuklearne komórki (1 centralne jądro); BRAK PRĄŻKOWANIA: brak regularnych sarkomer; aktyna + miozyna II + kaldesmon + kalmodzulina; MECHANIZM SKURCZU: ↑Ca²⁺ (z SR lub zewnątrz) → wiązanie z kalmoduliną → ↑MLCK (myosin light chain kinase) → fosforylacja MLC (myosin light chain, Ser19) → aktywacja miozyny → skurcz; MLCP (myosin light chain phosphatase): defosorylacja MLC → rozkurcz; GĘSTE CIAŁA (dense bodies): zakotwiczenie aktyny (jak Z-disc funkcyjnie); CAVEOLAE: ↑Ca²⁺ wejście; podział: jednojądrowe, wrzecionowate; lokalizacja: naczynia + GI + oddechowe + moczowe + macica', is_correct: true },
      { id: 'C', text: 'REGULACJA NACZYNIOWA M. GŁADKIEGO: wazodylatacja: NO (→ sGC → ↑cGMP → PKG → ↓MLCK + ↑MLCP → rozkurcz) + PGI2 (prostacyklina, → ↑cAMP → PKA → ↓MLCK) + adenozyna; wazokonstrykcja: ET-1 (endotelina → ETA/B receptory na vSMC → Gq → ↑IP₃ → ↑Ca²⁺) + Ang II (AT1R) + adrenalina/NA (α1-AR) + TXA₂ (tromboksan); LEKI działające na m. gładki naczyń: CCB (antagoniści Ca²⁺: nifedipina, amlodipin) → ↓Ca²⁺ wejście → rozkurcz; nitrates → NO → ↑cGMP; α1-blokery (prazosin, doksazosin) → ↓NA-indukowany skurcz; PDE5i (sildenafil) → ↓degradacja cGMP → ↑cGMP → rozkurcz (płucna/penalna vasculatura)', is_correct: true },
      { id: 'D', text: 'Mięsień sercowy jest wielojądrowy jak mięsień szkieletowy (syncytium z setkami jąder w jednej komórce); mięsień gładki ma poprzeczne prążkowanie (sarkomery) jak mięsień szkieletowy; connexin 43 (Cx43) jest białkiem budującym desmosomy (nie gap junctions); MLCK jest enzymem defosorylującym MLC i powodującym rozkurcz mięśnia gładkiego; kardiomiocyty nie mają automatyzmu (AP są wyzwalane wyłącznie przez nerw błędny); mięsień gładki nie ma kaldesmon i kalmodulina', is_correct: false },
    ],
    correct_answer: ['A', 'B', 'C'],
    explanation: '(A) KARDIOMIOPATIE: DCM (dilated): ↓systoliczna funkcja, ↑objętość; etiologia: viralne (Coxsackie B) + alkohole + IDC (idiopathic); titin (TTNtv) → DCM; leczenie: HF therapy (ACEI/ARB + BB + MRA + SGLT2i) + CRT (cardiac resynchronization) + LVAD + transplant; HCM (hypertrophic): sarcomere gene mutations (myosin heavy chain, MYH7; myosin binding protein C, MYBPC3 — >60%) → ↑hypertrofia → ↓filling; ryzyko SCD (sudden cardiac death); leczenie: BB + CCB + disopyramide; HOCM (z obstrukcją): ↑gradient LVOT → septal ablation (alcohol) lub myotomy (Morrow); ICD (implantable cardioverter-defibrillator) przy ↑ryzyku; (B) M. GŁADKI GI: ICC (interstitial cells of Cajal): rozruszniki GI (peristaltyka); Auerbach (myenteric) + Meissner (submucosal) sploty; achalazja: ↓ICC + ↓NANC (NO) w dolnym zwieraczu przełyku → brak rozkurczu → dysfagia; leczenie: calcium channel blocker + nitraty + pneumatyczna dylatacja + Heller myotomy (+ fundoplikacja) + POEM; HIRSCHSPRUNG: brak zwojów (kongenital aganglionosis) → brak splotów → okrężnica nie rozkurcza → niedrożność; (C) PDE5 INHIBITORS: sildenafil (Viagra, Revatio) + tadalafil (Cialis, Adcirca) + vardenafil; wskazania: ED + PAH (pulmonary arterial hypertension); D — Fałsz: kardiomiocyty: 1–2 jądra (centralnie, nie syncytium wielojądrowe jak szkieletowy); m. gładki: BRAK prążkowania; Cx43: gap junctions; MLCK: FOSORYLUJE (aktywuje skurcz); kardiomiocyty: MAJĄ automatyzm (SA node, AV node); mięsień gładki MA kaldesmon i kalmodulin.',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },
  {
    topic_id: TOPIC, subtopic_id: S.miesien, question_type: 'true_false',
    question_text: 'Oceń prawdziwość poniższych stwierdzeń dotyczących unerwienia mięśni i jednostki motorycznej:',
    options: [
      { id: 'A', text: 'JEDNOSTKA MOTORYCZNA (motor unit): 1 motoneuron alfa (α-MN) + wszystkie włókna mięśniowe przez niego unerwione; SKŁAD: małe jednostki motoryczne (precyzja): 1 MN:3–5 włókien (mięśnie oka, ręki); duże (siła): 1 MN:1000–2000 włókien (mięśnie posturalne); ZASADA HENNEMAN\'A (size principle): rekrutacja od małych (typ I) → do dużych (typ IIx): ↑siła → ↑rekrutacja; INERWACJA PROPRIOCEPTYWNA: WRZECIONA MIĘŚNIOWE (muscle spindles): włókna intrafuzalne (bieg. w sarkomerze) → aferentacja Ia (ann. spiralis → szybka, prędkość + długość) + II (kwiatkowe = flower spray → powolna, długość); eferentacja γ-motoneurony (regulują wrażliwość wrzeciona podczas skurczu)', is_correct: true },
      { id: 'B', text: 'ZŁĄCZE NERWOWO-MIĘŚNIOWE (NMJ, synapse neuromuscular): (1) nerw motoryczny (Aα) wchodzi → rozgałęzia → terminale → AP → Ca²⁺ wejście (VGCC, P/Q-type) → egzocytoza pęcherzyków z ACh (kwanty); (2) ACh → szczelinę synaptyczną → nAChR (nikotynowy; heteropentamer: α₂βγδ → dorosły: α₂βεδ) na junctional folds postsynaptycznej → Na⁺/K⁺ ↑ → EPP (end-plate potential) → sarkolema AP → ↑Ca²⁺ z SR → skurcz; (3) AChE (acetylocholinesteraza) w synaptycznej szparze → degradacja ACh → przerwa sygnału; CHOLINERGICZNE LEKI: neostygmina/pyridostigmina (AChE inhibitory) → ↑ACh → wskazanie: MG (myasthenia gravis)', is_correct: true },
      { id: 'C', text: 'Zasada Henneman\'a mówi, że duże jednostki motoryczne (typ IIx) są rekrutowane jako pierwsze podczas skurczu mięśnia; γ-motoneurony unerwiają pozawrzecionowe włókna ekstrafuzalne; wrzeciona mięśniowe zawierają wyłącznie aferentne włókna Ia (nie ma włókien II); AChE jest enzymem syntetyzującym ACh (nie degradującym); nAChR (nikotynowy receptor acetylocholiny) jest receptorem metabotropowym (GPCR) sprzężonym z białkiem Gq; jednostki motoryczne oka mają 1000 włókien (duże, do precyzji)', is_correct: false },
    ],
    correct_answer: ['A', 'B'],
    explanation: 'A — Prawda: POLIOMYELITIS: wirus polio → α-MN w rogach przednich rdzenia → porażenie wiotkie; eliminacja OPV (oral, replikuje → polio-like) → IPV (inaktywowany, bezpieczny); POST-POLIO SYNDROME: 30 lat po infekcji → nowa słabość; mechanizm: wyczerpanie przerostowo-kompensacyjnych jednostek; ALS (amyotrophic lateral sclerosis, choroba Lou Gehriga): UMN + LMN degeneracja; SOD1, TDP-43, FUS, C9orf72 (hexanucleotide repeat); leczenie: riluzol (anty-glutamatergiczne, ↑przeżycie 3 mies.) + edaravone; Nusinersen (antisense oligonucleotide → blokuje SMN2 exon 7 skipping → ↑SMN2 → SMA); B — Prawda: MYASTHENIA GRAVIS (MG): anty-AChR (Ab IgG → komplement + internalizacja receptora + blokada) → ↓EPP → ↓AP mięśnia → osłabienie; fatigability (↑przy powtarzaniu) + ocular (ptosis + diplopia) + bulbar (dysfagia + dysartria) + kończyny; thymoma (15%): skojarzony; diagnostyka: Edrophonium (Tensilon) test: krótkodziałający AChE inhibitor → ↑siła; leczenie: pyridostigmina (cholinesteraz inh.) + immunosupresja (GKS, azatiopryna) + plazmafereza/IVIG (kryzys) + tymektomia; anty-MuSK MG: bez thymoma, bardziej bulbarny; LAMBERT-EATON (LEMS): anty-VGCC (P/Q) → ↓Ca²⁺ → ↓ACh egzocytoza → odwrotność MG: poprawa przy powtarzaniu; paraneoplastyczny (SCLC 60%); C — Fałsz: Henneman: małe rekrutowane PIERWSZE (slow-twitch, typ I); γ-MN: INTRAFUZALne; wrzeciona: Ia + II; AChE: DEGRADUJE ACh; nAChR: JONOTROPOWY (nie GPCR); jednostki oka: MAŁE (3–5 włókien).',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },
  {
    topic_id: TOPIC, subtopic_id: S.miesien, question_type: 'single',
    question_text: 'Mięśnie różnią się między sobą funkcją i lokalizacją. Który opis POPRAWNIE charakteryzuje główne mięśnie kończyny dolnej i ich działanie?',
    options: [
      { id: 'A', text: 'KOŃCZYNA DOLNA — GŁÓWNE MIĘŚNIE: (1) POŚLADKOWE: gluteus maximus (L5-S2, n. pośladkowy dolny): wyprost + rotacja zewnętrzna biodra; najsilniejszy prostownik ciała (wchodzenie po schodach); gluteus medius + minimus (L4-S1, n. pośladkowy górny): odwiedzenie + stabilizacja miednicy (Trendelenburg); (2) UDO: PRZÓD (mięsień czworogłowy = quadriceps femoris: rectus femoris, vastus lateralis, medialis, intermedius): zgięcie biodra (rectus) + wyprost kolana; ścięgno rzepki; TYŁ (hamstrings: biceps femoris + semitendinosus + semimembranosus, n. kulszowy): zgięcie kolana + wyprost biodra; (3) ŁYDKA: gastrocnemius (n. piszczelowy, S1-2) + soleus = m. trójgłowy łydki → plantarflexion + na palce (calf raise)', is_correct: true },
      { id: 'B', text: 'Gluteus maximus jest odwodzicielem biodra odpowiedzialnym za stabilizację miednicy; mięsień czworogłowy (quadriceps) jest zginaczem kolana; mięsień dwugłowy uda (biceps femoris) jest wyprostownikiem kolana; objawy uszkodzenia n. kulszowego to utrata odruchu rzepkowego (nie skokowego); gastrocnemius jest zginaczem grzbietowym (dorsiflektor); trójgłowy łydki ma jedno brzuśce (nie dwa: gastrocnemius + soleus)', is_correct: false },
      { id: 'C', text: 'Mięsień prostownik kolana (quadriceps) jest unerwiony przez n. kulszowy; hamstrings (dwugłowy uda, półścięgnisty, półbłoniasty) są prostownikami kolana; Trendelenburg sign wynika z uszkodzenia nerwu kulszowego i gluteus maximus; gastrocnemius działa tylko jako dorsiflektor; mięsień biodrowo-lędźwiowy (iliopsoas) odpowiada za wyprost biodra; mięśnie przywodziciele biodra są unerwione przez nerw pośladkowy górny', is_correct: false },
      { id: 'D', text: 'Quadriceps femoris jest zginaczem kolana unerwionym przez n. kulszowy; semimembranosus jest mięśniem pośladkowym; gluteus medius stabilizuje udo podczas wyprostu w stawie kolanowym; nerw piszczelowy (tibialis) unerwia mięsień czworogłowy; soleus i gastrocnemius działają odwrotnie (soleus = dorsiflektor); mięsień prostownik długi palucha (EHL) jest zginaczem podeszwowym', is_correct: false },
    ],
    correct_answer: ['A'],
    explanation: 'KLINICZNE NERWÓW KOŃCZYNY DOLNEJ: NERW KULSZOWY (N. ISCHIADICUS, L4-S3): podział: n. strzałkowy wspólny (common peroneal, CPN) + n. piszczelowy (tibialis); ucisk: piriformis (piriformis syndrome) lub dyskopatia L4-S5; COMMON PERONEAL NERVE (CPN): okrąża głowę fibuli → gałąź powierzchowna (mm. strzałkowe → dorsiflekcja palców + ewersja) + głęboka (mm. piszczelowe + EHL + EDB → dorsiflekcja stopy + inwersja + prostowanie palców 1); uszkodzenie CPN (przez fibulę): foot drop (STEPPAGE gait) + parestezje grzbiet stopy; FEMORAL NERVE (L2-4): unerwia m. czworogłowy + biodrowo-lędźwiowy; testowanie: odruch rzepkowy (L3-4); uszkodzenie: ↓prostowanie kolana + ↓czucie przyśrodkowe uda; OBTURATOR NERVE (L2-4): przywodziciele + część obturator externus; SUPERIOR GLUTEAL NERVE (L4-S1): gluteus medius/minimus + TFL; uszkodzenie → Trendelenburg; INFERIOR GLUTEAL NERVE (L5-S2): gluteus maximus; uszkodzenie: ↓wyprost biodra (trudność ze schodami).',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },
  {
    topic_id: TOPIC, subtopic_id: S.miesien, question_type: 'true_false',
    question_text: 'Oceń prawdziwość poniższych stwierdzeń dotyczących rodzajów skurczu mięśniowego i pracy mięśni:',
    options: [
      { id: 'A', text: 'RODZAJE SKURCZU MIĘŚNIOWEGO: (1) IZOTONICZNY: stała siła → zmiana długości; koncentryczny (agonist shortens) np. biceps curl przy uginaniu; ekscentryczny (antagonist elongates under load) np. quadriceps przy schodzeniu ze schodów → ↑mikrouszkodzenia + DOMS (delayed onset muscle soreness, ból 24–72h po) + ↑hipertrofia sygnalizacja; (2) IZOMETRYCZNY: stała długość → zmiana siły; np. chwyt statyczny, stabilizacja; (3) IZOKINETYCZNY: stała szybkość → zmienna siła; wytworzone na maszynach izokinetycznych; wskaźnik do rehabilitacji', is_correct: true },
      { id: 'B', text: 'MECHANIKA SKURCZU: KRZYWA NAPIĘCIE-DŁUGOŚĆ: optimalna długość sarkomery (L0, ~2.2 μm): maksymalne nakładanie aktyny i miozyny → max siła; przy ↓L (skrócenie): titin + poprzeczne mostki utrudniają ruch → ↓siła; przy ↑L (rozciągnięcie): ↓nakładanie aktyny-miozyny → ↓mostek → ↓siła; KRZYWA SIŁA-PRĘDKOŚĆ: przy stałym obciążeniu: ↑szybkość skracania → ↓siła (cross-bridge kinetics); przy ekscentrycznym: ↑prędkość → ↑siła (pasywna); SUMMACJA: ↑częstotliwość AP → ↑Ca²⁺ → ↑siła → TĘŻEĆ (tetanus): przy 80–100 Hz u mięśni szybkich, 20–30 Hz u wolnych (sercowy: tężeć niemożliwy → długa refrakcja)', is_correct: true },
      { id: 'C', text: 'Skurcz koncentryczny polega na wydłużaniu mięśnia (nie skracaniu); skurcz ekscentryczny jest bezpieczniejszy od koncentrycznego i nie powoduje DOMS; skurcz izometryczny powoduje największą zmianę długości mięśnia; przy optymalnej długości sarkomery (L0) nakładanie aktyny i miozyny jest minimalne; skurcz tężcowy (tetanus) jest możliwy w mięśniu sercowym dzięki krótkim okresom refrakcji; DOMS (ból opóźniony) pojawia się bezpośrednio po wysiłku (0–2h, nie 24–72h)', is_correct: false },
    ],
    correct_answer: ['A', 'B'],
    explanation: 'A — Prawda: DOMS MECHANIZM: mikrouszkodzenia sarkolemma + miofibryli → ↑IL-1β, IL-6, TNF + infiltracja neutrofili → ból zapalny; ekscentryczne: ↑ mikrouszkodzenia vs koncentryczne → ↑DOMS; REPEATED BOUT EFFECT: po 1. treningu → ↓DOMS przy kolejnym (adaptacja: ↑titin expression + ↓sarcomere non-uniformity); HIPERTROFIA: ekscentryczne stymuluje mechanotransdukcję (YAP/TAZ, mTORC1 → ↑MPS = muscle protein synthesis); SARCOPENIA: ↓mięśni z wiekiem (3–8%/dekadę po 30); ↓satelitarne komórki (stem cells) + ↓IGF-1 + ↑miostatyna; leczenie: trening oporowy + białko (1.2–2.0 g/kg/d); B — Prawda: IZOMETRYCZNY vs DYNAMICZNY: wytrzymałość izometryczna ↑BP bardziej niż dynamiczna (Valsalva-like); zalecenia: izometryczne ↓BP przy regularnym treningu (IHG = isometric handgrip training); TETANUS W SERCU: NIEMOŻLIWY → refrakcja absolutna = 250 ms (czas skurczu = 300 ms) → AP nie może wywołać kolejnego skurczu gdy mięsień jeszcze się kurczy; MIĘSIEŃ SZKIELETOWY: refrakcja absolutna = 1–3 ms (krótka) → tetanus możliwy; UKŁAD RUFOWY (RANK): ↑obciążenie ↑silne skurcze → EIMD (exercise-induced muscle damage) → leukocytoza + ↑CK + ↑AST w surowicy (przejściowe); C — Fałsz: koncentryczny: SKRACANIE; ekscentryczny: WIĘCEJ DOMS + więcej mikrouszkodzeń; izometryczny: BRAK zmiany długości; L0: MAKSYMALNE nakładanie; sercowy: tetanus NIEMOŻLIWY (długa refrakcja); DOMS: 24–72h (nie 0–2h).',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },
  {
    topic_id: TOPIC, subtopic_id: S.miesien, question_type: 'multiple',
    question_text: 'Które z poniższych stwierdzeń POPRAWNIE opisują główne mięśnie kończyny górnej i ich unerwienie? (zaznacz wszystkie prawdziwe)',
    options: [
      { id: 'A', text: 'KOŃCZYNA GÓRNA — SPLOT RAMIENNY (C5–T1): (1) n. pachowy (axillary, C5-6): deltoid (odwiedzenie ramienia) + teres minor; uszkodzenie przy zwichnięciu barku → ↓czucie boczne ramienia; (2) n. mięśniowo-skórny (musculocutaneous, C5-6): biceps brachii (zgięcie łokcia + supinacja) + brachialis + coracobrachialis; (3) n. promieniowy (radial, C5-T1): mięśnie prostowniki (triceps, wrist extensors, EDC, APL, EPL, EPB) + supinator; uszkodzenie w spiralnym rowku kości ramiennej ("Saturday night palsy") → drop wrist; (4) n. pośrodkowy (median, C6-T1): LOAF (lumbricales 1+2, opponens pollicis, abductor pollicis brevis, flexor pollicis brevis) + FDS + FDP (radial 2); CTS (carpal tunnel syndrome)', is_correct: true },
      { id: 'B', text: 'N. ŁOKCIOWY (ulnar, C8-T1): ↑intrinsic hand muscles (hypothenar + lumbricales 3+4 + interosseous + adductor pollicis) + FCU + FDP (ulnar 2); uszkodzenie: "claw hand" (4+5 palce, Benediction sign) + ↓abdukcja palców + ↓Froment sign (zaciśnięcie kartki papieru → kciuk flektuje przez FPL — n. pośrodkowy kompensuje); ENTRAPMENT: cubital tunnel (retroepicondylar groove, przy łokciu) → ból + parestezje łokciowe; KLSKI SPLOTU RAMIENNEGO: Erb (C5-6): górny → "waiter tip" (ramię wewnętrzna rotacja + wyprost łokcia + pronacja nadgarstka); Klumpke (C8-T1): dolny → claw hand + Horner (uszkodzenie T1 → ↓sympatyczne włókna → ptosis, mioza, anhidroza)', is_correct: true },
      { id: 'C', text: 'MIĘŚNIE GRZBIETU I RAMIENIA: trapezius (n. dodatkowy CN XI: ↑ ramię/łopatka; uszkodzenie → opadnięcie barku + ↓abdukcja powyżej 90°) + serratus anterior (n. piersiowy długi C5-7: odsuwa łopatkę od kręgosłupa; uszkodzenie → "winging scapula", łopatka sterczy) + latissimus dorsi (n. piersiowo-grzbietowy: prostownik + adduktor + pronator ramienia); MIĘŚNIE RAMIENIA: biceps brachii (2 głowy: krótka na wyrostku kruczym, długa na biegunie górnym glenoid; zginacz łokcia + supinator); triceps brachii (3 głowy: prostownik łokcia, n. promieniowy)', is_correct: true },
      { id: 'D', text: 'Nerw promieniowy (radial) unerwia biceps brachii i odpowiada za zgięcie łokcia; nerw łokciowy (ulnar) unerwia mięśnie LOAF (opponens pollicis, abductor pollicis brevis); Erb\'s palsy to uszkodzenie dolnego splotu (C8–T1); nerw mięśniowo-skórny (musculocutaneous) unerwia mięśnie prostowniki ramienia; drop wrist jest wynikiem uszkodzenia nerwu pośrodkowego; serratus anterior jest unerwiony przez nerw dodatkowy (CN XI)', is_correct: false },
    ],
    correct_answer: ['A', 'B', 'C'],
    explanation: '(A) CARPAL TUNNEL SYNDROME (CTS): ucisk n. pośrodkowego pod więzadłem poprzecznym nadgarstka; RF: ciąża (↑obrzęk), DM, RA, niedoczynność tarczycy, praca z drganiami, acromegalia; objawy: parestezje/ból kciuk+2+3 + promieniowy 4 (nocny, po przebudzeniu); Tinel (stuk w CTS → parestezje) + Phalen (zgięcie nadgarstka 60s → parestezje); diagnostyka: NCS (nerve conduction studies) → ↓SNAP + ↓CMAP n. pośrodkowego; leczenie: szyny nocne → steroid iniekcja → operacja (carpal tunnel release, CTR); (B) ULNAR NERVE AT ELBOW: cubital tunnel syndrome: "funny bone" = ucisk na epicondylus medialis; retrocondylar groove; test: elbow flexion (90° → kompresja); FROMENT SIGN: użycie FPL (n. pośrodkowy) do kompensacji braku adductor pollicis (n. łokciowy) → kciuk flektuje przy ciągnięciu papieru; WARTENBERG SIGN: abdukcja 5. palca (brak addukcji przez interosseous); (C) SERRATUS ANTERIOR: przyczep: żebra 1–8 → przyśrodkowy brzeg łopatki (kostka); stabilizuje łopatkę do klatki; WINGING SCAPULA: uszkodzenie n. piersiowego długiego → ↓serratus → łopatka "odfrywa"; test: pushup ściana; D — Fałsz: radial: prostowniki (nie biceps); LOAF: pośrodkowy (nie łokciowy); Erb: GÓRNY (C5-6, nie dolny); musculocutaneous: ZGINACZE (nie prostowniki); drop wrist: radial (nie pośrodkowy); serratus: long thoracic (nie CN XI; trapezius = CN XI).',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },
  {
    topic_id: TOPIC, subtopic_id: S.miesien, question_type: 'single',
    question_text: 'Mięśnie oddechowe uczestniczą w mechanice oddychania. Który opis POPRAWNIE wyjaśnia rolę poszczególnych mięśni w wdechu i wydechu?',
    options: [
      { id: 'A', text: 'MIĘŚNIE ODDECHOWE: WDECH SPOKOJNY: (1) PRZEPONA (diaphragm, C3-5 = phrenic nerve): główny mięsień wdechu → skurcz → obniżenie kopuły → ↑objętość jamy piersiowej → ↓ciśnienie → powietrze wchodzi; tworzy 70% objętości oddechowej w spoczynku; (2) MIĘŚNIE ZEWNĘTRZNE MIĘDZYŻEBROWE (mm. intercostales externi, Th1-Th11, nn. intercostales): unoszą żebra (pump handle + bucket handle) → ↑wymiar przednio-tylny + poprzeczny; WYDECH SPOKOJNY: PASYWNY (sprężystość płuc + klatki → powrót); WDECH FORSOWANY: + STERNOCLEIDOMASTOIDEUS (SCM) + scaleni (predniają żebra 1+2) + serratus anterior + pectoralis major (przy unieruchomieniu rąk); WYDECH FORSOWANY: mm. brzucha (transversus, obliquus) + mm. wewnętrzne międzyżebrowe', is_correct: true },
      { id: 'B', text: 'Przepona jest mięśniem wydechu; wydech spokojny wymaga aktywnego skurczu mięśni brzucha; mięśnie zewnętrzne międzyżebrowe uczestniczą w wydechu; podczas spokojnego wdechu mięśnie SCM i scaleni są głównie aktywne; przepona unosi żebra podczas wdechu; nerw przeponowy pochodzi z segmentów C7–T2; podczas kaszlu i kichania głównie pracuje m. trapezius', is_correct: false },
      { id: 'C', text: 'Mięśnie wewnętrzne międzyżebrowe uczestniczą w wdechu; przepona obniża żebra podczas wdechu (nie obniża kopuły); normalne oddychanie (tidal breathing) wymaga aktywnego wydechu przez mięśnie brzucha; nerw przeponowy to n. ramienny (brachial nerve, C6–T1); kopuła przepony skurczem przesuwa się ku górze (ogonowo/caudally); mięsień mostkowo-obojczykowo-sutkowy (SCM) jest głównym mięśniem w spoczynkowym wdechu', is_correct: false },
      { id: 'D', text: 'Wydech spokojny jest aktywnym procesem wymagającym skurczu mm. międzyżebrowych; wdech w spoczynku wymaga tylko SCM i scaleni (przepona nie działa); mięśnie zewnętrzne międzyżebrowe obniżają żebra podczas wdechu (bucket-handle ↓); przepona jest unerwiona przez nerw łokciowy (ulnar); podczas kaszlu i wysiłku fizycznego wyłącznie przepona wykonuje wszystkie ruchy oddechowe; mięśnie scaleni unoszą żebra I–V (nie I–II)', is_correct: false },
    ],
    correct_answer: ['A'],
    explanation: 'PRZEPONA — KLINICZNE: PORADOŚĆ PRZEPONY: HICCUP (czkawka): mimowolny skurcz przepony → nagłe zamknięcie głośni (addukcja fałdów głosowych) → "hic" dźwięk; najczęściej niegroźna; przyczyny przewlekłe: guz śródpiersia, guzy przełyku, GERD, zapalenie wyrostka; leczenie: chlorpromazyna, baklofem, gabapentyna; PORAŻENIE PRZEPONY: jednostronne: zwykle bezobjawowe (kontralateralna); obustronne: respiracyjna niewydolność → intubacja; PRZEPUKLINA PRZEPONOWA: wrodzony defekt (lewy bok, foramen Bochdalek): jelita w klatce → ↓płuca → niewydolność oddechowa noworodka; leczenie: chirurgiczne + stabilizacja oddechowa; PHRENIC NERVE PACING: DPS (diaphragmatic pacing system) dla tetraplegii (C3-4 porażenie) → stymulacja nerwu przeponowego → niezależność od respiratora; SPIROMETRIA: FVC (forced vital capacity): objętość wymuszona przy maksymalnym wydechu; FEV1 (forced expiratory volume 1s): ↓w obturacji; FEV1/FVC: norma > 0.7; ↓w COPD/astma (obturacja); ↓FVC + FEV1 normalne/podwyższone FEV1/FVC → restrykcja (↓TLC) → ILD, osłabienie mięśni oddechowych (ALS, MG); MIP (maximal inspiratory pressure): test siły przepony (< −60 cmH₂O norma).',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },
  {
    topic_id: TOPIC, subtopic_id: S.miesien, question_type: 'true_false',
    question_text: 'Oceń prawdziwość poniższych stwierdzeń dotyczących właściwości mechanicznych mięśni:',
    options: [
      { id: 'A', text: 'WŁAŚCIWOŚCI MECHANICZNE MIĘŚNIA: (1) POBUDLIWOŚĆ: zdolność do odpowiedzi na bodźce (elektryczne, mechaniczne, chemiczne) → AP; progowa intensywność bodźca: "all or nothing" (każde włókno całkowicie lub wcale); (2) KURCZLIWOŚĆ: zdolność do generowania napięcia (active tension) przez aktynomiozynowe poprzeczne mostki; (3) SPRĘŻYSTOŚĆ (elasticity): zdolność do powrotu do spoczynkowej długości po odkształceniu; (4) ROZCIĄGLIWOŚĆ (extensibility): zdolność do rozciągania powyżej spoczynkowej długości; (5) TONUS MIĘŚNIOWY: tło ciągłego napięcia (niepełne tężeć, rotacyjna rekrutacja) → podtrzymanie postawy; ↑tonus: spastyczność (uszkodzenie UMN); ↓tonus: wiotkość (uszkodzenie LMN)', is_correct: true },
      { id: 'B', text: 'REAKCJA "WSZYSTKO ALBO NIC" (all-or-nothing): dotyczy POJEDYNCZEGO włókna mięśniowego lub kardiomiocytu (komórki autopobudzającej); siła całego mięśnia: regulacja przez (1) rekrutację jednostek motorycznych (spatial summation) + (2) frecwencję AP (temporal summation → summacja skurczów → partial/complete tetanus); PRAWA STARLING SERCA: "Frank-Starling law": ↑preload (↑EDV) → ↑rozciągnięcie → ↑nakładanie → ↑siła skurczu kardiomiocytu (in cardiac muscle → ↑sarcomere length → ↑Ca²⁺ sensitivity of TnC) → ↑SV; mechanizm: ↑titin stretch → ↑lattice spacing → ↑cross-bridge attachment + ↑TnC Ca²⁺ affinity', is_correct: true },
      { id: 'C', text: 'Zasada "wszystko albo nic" dotyczy całego mięśnia (nie pojedynczego włókna); spastyczność jest wynikiem uszkodzenia dolnego neuronu ruchowego (LMN); wiotkość jest wynikiem uszkodzenia górnego neuronu ruchowego (UMN); siła mięśnia jest regulowana wyłącznie przez rekrutację (nie częstotliwość AP); rozciągliwość mięśnia oznacza powrót do długości spoczynkowej (nie rozciąganie powyżej); prawo Franka-Starlinga dotyczy wyłącznie mięśnia szkieletowego (nie sercowego)', is_correct: false },
    ],
    correct_answer: ['A', 'B'],
    explanation: 'A — Prawda: TONUS MIĘŚNIOWY KLINICZNY: SPASTYCZNOŚĆ (UMN = korowo-rdzeniowy): ↑stretch reflex → ↑tonus zależny od prędkości; "clasp-knife" phenomenon; RIGIDITY (sztywność): ↑oporność niezależna od prędkości; "lead pipe" lub "cogwheel" (przy Parkinsonze); leczenie spastyczności: baclofen (GABA-B agonista), tizanidyna (α2), benzodiazepiny, botulinum toxin (lokalne → ↓ACh); HYPOTONIA (wiotkość, LMN): ↓stretch reflex + ↓tonus; przyczyny: rdzeniowy (SMA, polio) + obwodowy (Guillain-Barré, CIDP, neuropatia) + mięśniowy (miopatie, DMD) + synaptyczny (MG, botulizm); B — Prawda: FRANK-STARLING W KLINICE: HF z niskim EF (HFrEF): ↑EDV → ↑preload → compensatory Frank-Starling; ale przy nadmiernym rozciągnięciu (> L0) → ↓siła (descending limb); główny mechanizm kompensacji we wczesnej HF; LENIWE SERCE po treningu: ↓HR → ↑czas napełniania → ↑EDV → ↑SV (Frank-Starling) → ↑CO; INOTROPIA: ↑inotropy (dobutamina, digitalisy, adrenalina) → ↑siła przy tej samej długości (shift Frank-Starling w górę); C — Fałsz: all-or-nothing: POJEDYNCZE włókno; spastyczność: UMN (nie LMN); wiotkość: LMN (nie UMN); siła: rekrutacja + CZĘSTOTLIWOŚĆ; rozciągliwość: rozciąganie PONAD spoczynkową; Frank-Starling: SERCOWY (nie szkieletowy).',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },

]

function post(body) {
  return new Promise((resolve, reject) => {
    const data = Buffer.from(JSON.stringify(body), 'utf8')
    const req = https.request({
      hostname: 'gzpxvfaftvkfwpvljcrk.supabase.co',
      path: '/rest/v1/questions', method: 'POST',
      headers: {
        apikey: KEY, Authorization: 'Bearer ' + KEY,
        'Content-Type': 'application/json', Prefer: 'return=minimal',
        'Content-Length': data.length,
      },
    }, res => {
      let r = ''; res.on('data', c => r += c)
      res.on('end', () => resolve({ status: res.statusCode, body: r }))
    })
    req.on('error', reject); req.write(data); req.end()
  })
}

async function main() {
  console.log(`Seeding batch 3 (${questions.length} questions)...`)
  for (const q of questions) {
    const { status, body } = await post(q)
    const ok = status === 201 || status === 204
    if (!ok) console.log('ERR', status, body.slice(0, 200))
    else console.log('OK', `[${q.question_type}]`, q.question_text.slice(0, 60).replace(/\n/g, ' '))
  }
  console.log('Done.')
}
main().catch(err => { console.error(err); process.exit(1) })
