// Seed batch 5/5 — Układ ruchu człowieka
// Zmęczenie mięśni (5) + Choroby układu ruchu (7) = 12 questions

const https = require('https')
const KEY = process.env.SUPABASE_SERVICE_ROLE_KEY || ''
const TOPIC = '42b3edde-2027-4bbb-8a90-38568031d9b0'

const S = {
  zmeczeie: '957b8505-0f02-4284-900d-854311b0952a',
  choroby:  '7552bf0c-5c0d-4f28-8549-8326ae76b95c',
}

const questions = [

  // ── ZMĘCZENIE MIĘŚNI (5) ─────────────────────────────────────────────────
  {
    topic_id: TOPIC, subtopic_id: S.zmeczeie, question_type: 'single',
    question_text: 'Badacz mierzy zdolność wysiłkową mięśni zginaczy przedramienia podczas próby izometrycznej utrzymywanej do wyczerpania. Które stwierdzenie POPRAWNIE opisuje kinetykę energetyczną podczas tego wysiłku?',
    options: [
      { id: 'A', text: 'KINETYKA ENERGETYCZNA IZOMETRYCZNEGO SKURCZU DO WYCZERPANIA: (1) 0–10 s: ATP + PCr system; ATP: ↓stężenie nieznacznie (homeostaza przez PCr); PCr: ↓gwałtownie (PCr + ADP → Cr + ATP, CK); Pi ↑ + Cr ↑ → hamowanie CK (produkt-inhibicja); (2) 10–120 s: ↑glikoliza beztlenowa → ↑mleczan + ↑H⁺; ↓pH (7.1→6.7) → ↓PFK (allosteryczna inhibicja) + ↓ATPase miozyny + ↓TnC Ca²⁺ affinity + ↓RYR1 (↓Ca²⁺ release); (3) powyżej 2 min: ↑↑K⁺ extracell (accumulation w T-tubule) → ↑impedance T-tubule → ↓AP propagation → E-C uncoupling (excitation-contraction decoupling) → ↓Ca²⁺ release bez ↓EMG', is_correct: true },
      { id: 'B', text: 'ATP i fosfokreatyna (PCr) nie ulegają deplecji podczas skurczu izometrycznego; mleczan powoduje zmęczenie przez bezpośrednie wiązanie z TnC; H⁺ (kwas) jest korzystny dla skurczu mięśni przez ↑ATPase miozyny; K⁺ nie akumuluje się w T-tubule podczas wysiłku; ↓pH aktywuje PFK (kluczowy enzym glikolizy); E-C uncoupling oznacza odsprzężenie elektromechaniczne bezpośrednio z powodu braku ACh', is_correct: false },
      { id: 'C', text: 'PCr (fosfokreatyna) jest substratem wyłącznie dla metabolizmu tlenowego; PFK (fosfofruktokinaza) jest aktywowana przez ↓pH; ↑K⁺ w T-tubule powoduje hiperpolaryzację sarkolemy → ↑Ca²⁺ release; E-C uncoupling jest procesem zależnym od serotoniny (nie K⁺ ani H⁺); mleczan hamuje RYR1 bezpośrednio przez wiązanie z kanałem; Pi nie wpływa na kinezę główek miozyny', is_correct: false },
      { id: 'D', text: 'Izometryczny skurcz nie zużywa ATP; glikoliza beztlenowa nie może działać przy skurczu izometrycznym; K⁺ nie wychodzi z komórek mięśniowych podczas depolaryzacji; ↑Pi poprawia siłę skurczu przez ↑power stroke; mleczan powoduje zasadowicę metaboliczną, która sprzyja skurczowi; PCr resynteza zachodzi anaerobowo (beztlenowo) przez kinazę kreatynową + O₂', is_correct: false },
    ],
    correct_answer: ['A'],
    explanation: 'K⁺ I T-TUBULE SZCZEGÓŁY: każdy AP: ↑K⁺ z komórki (repolaryzacja: K⁺ efluks) → przy intensywnym wysiłku: ↑[K⁺]o (interstitium 4 → 8–10 mM); T-tubule (wąskie wpuklenia): ↑[K⁺] w T-tubule >> interstitium (anatomicznie: wąska przestrzeń, słabe "wypłukanie"); ↑[K⁺] → ↓Vm gradient → ↓amplituda AP → ↓E-C coupling; Na⁺/K⁺-ATPase (α2 isoform w T-tubule): kompensuje K⁺ leak; przy zmęczeniu: ↓Na⁺/K⁺-ATPase aktywność → ↑K⁺ accumulation; OCHRONNE MECHANIZMY: Cl⁻ current (ClC-1): stabilizuje Vm (↓excitability) + chloran inhibitory (toksyczne) → ↑excitability (paradoxalnie ↑fatigue resistance krótkoterm.); Na⁺/K⁺-ATPase stymulacja: katecholaminy (β2 → ↑α2 translokacja do sarkolemy), kaliy, kwas mlekowy; ACID BASE PARADOX: ↓pH protects against K⁺-induced E-C failure? Mechanizm: H⁺ → ↓ClC-1 (Cl⁻ channel) → ↑membrane excitability → ↑AP propagation mimo ↑K⁺; LAKTAT A ZMĘCZENIE: NOWOCZESNY POGLĄD (Brooks\' lactate shuttle): mleczan nie jest "waste product" — jest substratem energetycznym: glycolytic (fast) fibers → lactate export (MCT4) → oxidative (slow) fibers → import (MCT1) + oxidation; mózg: główny konsument mleczanu podczas wysiłku; GLYCOGEN DEPLETION: Bergström (1967): needle biopsy → ↓glikogen koreluje z fatigue przy long-duration exercise; "hitting the wall" / "bonking" = glikogen krytycznie niski; karmienie CHO pre + mid-exercise → ↑endurance.',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },
  {
    topic_id: TOPIC, subtopic_id: S.zmeczeie, question_type: 'multiple',
    question_text: 'Które z poniższych czynników POPRAWNIE opisują różnice w zmęczeniu między typami włókien mięśniowych (I, IIa, IIx)? (zaznacz wszystkie prawdziwe)',
    options: [
      { id: 'A', text: 'WŁÓKNA WOLNOKURCZLIWE TYPU I (slow-twitch, oxidative, SO): ↑mitochondria (gęstość 4×) + ↑mioglobina (czerwona) + ↑gęstość kapilar + ↑enzymów β-oksydacji + ↑SDH (succinyl dehydrogenase) → wysokoefektywna fosforylacja oksydatywna; ↓ATPase miozyny (MYH7) → wolny skurcz (powolna kinetyka Ca²⁺) → WYSOKA ODPORNOŚĆ NA ZMĘCZENIE; stosowane: posturalne + długotrwałe niskie obciążenia (np. chód); zasada Hennemana: rekrutowane PIERWSZE przy małej sile', is_correct: true },
      { id: 'B', text: 'WŁÓKNA SZYBKOKURCZLIWE TYPU IIx (fast-twitch glycolytic, FG): ↓mitochondria + ↓mioglobina (białe/blady) + ↓gęstość kapilar + ↑glikoliza beztlenowa (↑PFK, ↑LDH) + ↑PCr zapas + ↑ATPase miozyny (MYH1) → szybki, silny skurcz; NISKA ODPORNOŚĆ NA ZMĘCZENIE (szybka deplecja PCr + ↑H⁺ + ↑K⁺ + ↑Pi); stosowane: sprinty, skoki, eksplozywne ruchy; rekrutowane OSTATNIE (wysokoprogowe MU)', is_correct: true },
      { id: 'C', text: 'PLASTYCZNOŚĆ WŁÓKIEN (fiber type plasticity): TRENING WYTRZYMAŁOŚCIOWY (aerobowy): IIx → IIa (pośredni) → I (ograniczone u dorosłych); ↑mitochondria + ↑MCT1 + ↑lipid droplets; ↑AMPK → ↑PGC-1α (koaktywator transkrypcji) → ↑biogeneza mitochondrialna + ↑angiogeneza; TRENING SIŁOWY: ↑IIa → IIx; ↑hypertrofia (↑sarcomere + ↑białka strukturalne); DENNERWACJA: ↑IIx; UNLOADING/BED REST: ↑IIx + ↑atrofia; AGING: ↓MU liczba (apoptoza motoneuronów) → sarkopennia (typ II > typ I loss)', is_correct: true },
      { id: 'D', text: 'Włókna typu I mają wyższą ATPase miozyny i szybszy cykl poprzecznych mostków niż włókna IIx; mioglobina (czerwona barwa) jest obecna wyłącznie we włóknach IIx; włókna IIx są rekrutowane przy najmniejszych siłach (zasada Hennemana); trening wytrzymałościowy powoduje konwersję włókien I → IIx (odwrotnie niż wskazano); PGC-1α (peroxisome proliferator-activated receptor gamma coactivator-1α) hamuje biogenezę mitochondrialną', is_correct: false },
    ],
    correct_answer: ['A', 'B', 'C'],
    explanation: '(A) ROZRÓŻNIENIE I VS IIa VS IIx: TYP I: MYH7 (β-MHC) + ↑TnI slow + ↑TnT slow + ↑tropomiozyna α + ↑SERCA2; TYP IIa (fast oxidative glycolytic, FOG): MYH2 + ↑mitochondria (pośrednie) + ↑glikoliza + ↑oksydacja → POŚREDNIA zmęczliwość; TYP IIx (IId u myszy): MYH1 + ↑PCr + ↑glikoliza → WYSOKA zmęczliwość; MIĘSIEŃ SOLEUS: ~ 80% typ I (posturalny); MIĘSIEŃ GASTROCNEMIUS: ~ 50% typ I; BICEPS BRACHII: ~ 50:50; (B) FATIGUE INDEX: Fatigue Index = (peak force – force at 2 min) / peak force × 100; TYP I: FI ~ 10–20%; TYP IIa: FI ~ 30–50%; TYP IIx: FI ~ 70–90%; (C) PGC-1α PATHWAY: AMPK aktywacja: ↑AMP/ATP ratio + metformina + AICAR + Ca²⁺/CaM kinase II → AMPK → ↑PGC-1α fosorylacja → translokacja do jądra → aktywacja: NRF1 + NRF2 → ↑mitochondrial transcription factor A (TFAM) → ↑mt biogeneza; ↑GLUT4 (↑insulin sensitivity); ↑UCP3 (uncoupling protein 3); ↑FAT/CD36 (lipid transport); SARCOPENIA MECHANIZM: ↓α-motoneuron survival → denervation → ↑atrophy → ↓MU number + ↓MU size; myostatin (GDF-8): ↑z wiekiem → ↑UPS (ubiquitin-proteasome) + ↑autophagy → ↑protein degradation; INSULIN-LIKE GF-1 (IGF-1)/mTOR: ↓z wiekiem → ↓protein synthesis → ↓hypertrophy; D — Fałsz: TYP I: WOLNA ATPase; mioglobina: WOLNE włókna (I); zasada Hennemana: I rekrutowane PIERWSZE; trening wytrzymałościowy: IIx → I (nie odwrotnie); PGC-1α: AKTYWUJE biogenezę mitochondrialną.',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },
  {
    topic_id: TOPIC, subtopic_id: S.zmeczeie, question_type: 'true_false',
    question_text: 'Oceń prawdziwość poniższych stwierdzeń dotyczących supresji i regeneracji mięśni po wysiłku:',
    options: [
      { id: 'A', text: 'OPÓŹNIONA BOLESNOŚĆ MIĘŚNI (DOMS, Delayed Onset Muscle Soreness): pojawia się 24–48 h po wysiłku ekscentrycznym (nie koncentrycznym); MECHANIZM: mikrouszkodzenia sarkolemy (przy ekscentrycznym: ↑siła zewnętrzna > siła mięśnia → ↑skurcz przy rozciągnięciu → ↑stres mechaniczny → mikrouszkodzenia Z-disc + sarkolemy) → ↑Ca²⁺ leak → aktywacja proteaz (kalpainy) + ↑reaktywne formy tlenu (ROS) → ↑IL-6 + ↑TNF-α + ↑PG E₂ + bradykinina → nocisensory aktywacja (TRPV1, TRPA1) → bolesność; MARKERY: ↑CK surowicy (peak 48–72 h) + ↑mioglobina + ↑LDH; ADAPTACJA: repeated bout effect (RBE): kolejny bliźniaczy wysiłek → ↓DOMS (neuralna + strukturalna adaptacja)', is_correct: true },
      { id: 'B', text: 'REGENERACJA GLIKOGENU MIĘŚNIOWEGO: deplecja glikogenu → natychmiastowe spożycie CHO (1–1.2 g CHO/kg/h) → ↑GLUT4 (translokacja do sarkolemy, max do 2 h po) + ↑insulina → ↑glukoza → ↑glikogeno-syntaza (GS, aktywna postać a = defosforylowana przez PP1) → ↑glikogen; pełna resynteza: 24 h przy odpowiednim CHO; GLUT4 INSULINOWE vs KONTRAKTYLNE: wysiłek: ↑Ca²⁺/AMPK/RAS → GLUT4 translokacja BEZ insuliny; po wysiłku: ↑GLUT4 translokacja z insuliną → ↑insulinowa wrażliwość (ważne dla diabetyków); WHY PROTEIN po wysiłku: leucyna → ↑mTORC1 → ↑MPS (muscle protein synthesis); timing: ≤ 30 min po wysiłku optymalny dla mTOR', is_correct: true },
      { id: 'C', text: 'DOMS (opóźniona bolesność mięśni) pojawia się wyłącznie po wysiłku koncentrycznym (nie ekscentrycznym); CK surowicy szczytuje natychmiast po wysiłku (nie po 48–72 h); mikrouszkodzenia mięśni nie są związane z ↑IL-6 ani TNF-α; GLUT4 jest transporterem glukozy zależnym wyłącznie od insuliny (nie aktywowanym przez wysiłek); resynteza glikogenu po wysiłku trwa minimum 72 h (niezależnie od spożycia CHO); leucyna hamuje mTORC1 (nie aktywuje; mTOR = mammalian target of rapamycin)', is_correct: false },
    ],
    correct_answer: ['A', 'B'],
    explanation: 'A — DOMS KLINICZNE: ASA/NLPZ (ibuprofen) → ↓PGE₂ → ↓bolesność (krótkoterminowo), ale mogą hamować RBE i adaptacje treningowe (↓COX-2 → ↓prostaglandyny proanaboliczne); masaż: ↓subiektywne odczucie bez ↓CK; kriioterapia (ice bath): kontrowersyjna → ↓DOMS krótkoterminowo, ale ↓adaptacje siłowe/hipertrofia (↓aktywacja MPS + satelity); REPEATED BOUT EFFECT (RBE): mechanizm: (1) neuralna: ↑rekrutacja + ↓inhibicja → ↓stres per włókno; (2) strukturalna: ↑titin stiffness + ↑Z-disc armored; (3) cellular: ↑heat shock proteins + ↑antioxidant enzymes; B — INSULIN SENSITIVITY POST-EXERCISE: GLUT4 biology: w spoczynku: 90% GLUT4 w cytozolowych pęcherzykach; wysiłek/insulin → AS160 (Akt substrate 160 kDa, TBC1D4) fosorylacja → ↓GTPase aktywność Rab → ↑GLUT4 vesicle fusion; wysiłek przez AMPK → TBC1D1 (muscle-specific); połączony efekt (wysiłek + insulina): addytywny; DIABETES I WYSIŁEK: T2DM: ↓GLUT4 translokacja (insulinowa ścieżka zaburzona) → wysiłek: AMPK ścieżka NIENARUSZONA → ↑GLUT4 bez insuliny → ↑glikoza uptake → ↓glikemia; LEUCINE-mTOR: leucyna → LAT1 transporter → cytosol → Sestrin2 inhibicja → GATOR complex inhibicja → Ragulator/Rag activation → mTORC1 lysosomal recruitment → ↑S6K1 + ↑4E-BP1 fosorylacja → ↑translacja mRNA → ↑MPS; C — Fałsz: DOMS: EKSCENTRYCZNY (nie koncentryczny); CK: peak 48–72 h; IL-6/TNF-α: tak; GLUT4: INSULINA + WYSIŁEK; resynteza: 24 h; leucyna: AKTYWUJE mTOR.',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },
  {
    topic_id: TOPIC, subtopic_id: S.zmeczeie, question_type: 'single',
    question_text: 'Rabdomioliza jest poważnym powikłaniem nadmiernego wysiłku fizycznego. Które stwierdzenie POPRAWNIE opisuje patomechanizm i leczenie rabdomiolizy wysiłkowej?',
    options: [
      { id: 'A', text: 'RABDOMIOLIZA WYSIŁKOWA: PATOMECHANIZM: ↑intensywny/długotrwały wysiłek → nadmierne mikrouszkodzenia mięśni → MASYWNA NEKROZA WŁÓKIEN MIĘŚNIOWYCH: (1) ↑Ca²⁺ leak (RYR1 + sarkolema disruption) → ↑Ca²⁺ mitochondrialne → ↓ΔΨm → ↓ATP + ↑ROS → śmierć komórki; (2) ↑kalpainy (Ca²⁺-aktywowane proteinazy) → degradacja białek sarkomeru + cytoszkieletu; (3) ZAWARTOŚĆ KOMÓREK wycieka: mioglobina + CK + LDH + aldolaza + K⁺ → krew; NASTĘPSTWA: ↑CK > 5× norma (poważna: > 10 000 U/L); ↑mioglobina → nerka → mioglobinuria (brunatny mocz) → AKI (tubularna toksyczność: heme-pigment, kwasica + hipovolemia → ↓GFR); LECZENIE: agresywne nawodnienie i.v. (0.9% NaCl lub M/6 Ringer → ↑diureza ≥ 200 mL/h) → ↑wydalanie mioglobiny; bicarbonate + alkalizacja moczu (kontrowersyjne)', is_correct: true },
      { id: 'B', text: 'Rabdomioliza wysiłkowa jest wynikiem ↓Ca²⁺ w mięśniach (nie ↑Ca²⁺); mioglobina w moczu powoduje alkalurię (zasadowy mocz); leczenie rabdomiolizy polega na ograniczeniu podaży płynów (restrykcja wodna) by zmniejszyć obciążenie nerki; CK < 1000 U/L jest typową wartością dla ciężkiej rabdomiolizy; mioglobina jest nefrotoksyczna przez ↑diurezę (a nie przez ↓GFR); AKI (ostre uszkodzenie nerek) w rabdomiolizie jest konsekwencją ↑albuminy, nie mioglobiny', is_correct: false },
      { id: 'C', text: 'Mioglobinuria wywołuje erytrocyturię w badaniu moczu (mioglobina to to samo co hemoglobina); leczenie rabdomiolizy to hemodializa od pierwszego dnia; K⁺ nie jest uwalniany z uszkodzonych mięśni (↑K⁺ przy rabdomiolizie jest błędem klinicznym); CK (kinaza kreatynowa) jest uwalniana z hepatocytów (nie z mięśni); nawodnienie i.v. jest przeciwwskazane w rabdomiolizie z powodu ryzyka obrzęku płuc', is_correct: false },
      { id: 'D', text: 'Rabdomioliza jest wyłącznie chorobą genetyczną (McArdle\'s) bez formy wysiłkowej; mioglobina jest filtrowna przez nerki bez efektów toksycznych; ↑CK po treningu jest zawsze patologicznym, wymagającym hospitalizacji; AKI w rabdomiolizie wynika z ↑albuminy (nie mioglobiny); leczenie objawowe: ibuprofen (↓prostaglandyny → ↑diureza) + restrykcja płynów', is_correct: false },
    ],
    correct_answer: ['A'],
    explanation: 'RABDOMIOLIZA KLINICZNE SZCZEGÓŁY: PRZYCZYNY: wysiłkowe (marathon, CrossFit, eccentric exercise) + crush injury + ↑temp (malignant hyperthermia, heat stroke, NMS) + toxins (statyny, alkohol, kokaina, ecstasy) + viral (influenza, EBV) + metaboliczne (glycogen storage diseases: McArdle, Pompe) + hypophosphatemia + hypokalemia; DIAGNOZA: CK: ↑ 24–72h post; mioglobina: ↑szybciej (↓half-life, 2–3h); urinalysis: "heme positive" bez RBC (= mioglobinuria, odróżnia od hematuria); elektrolitY: ↑K⁺ + ↑PO₄ + ↑urate (hyperuricemia) + ↓Ca²⁺ (wczesna faza: wiązanie przez nekrotyczne mięśnie); AKI PATHOGENESIS: (1) tubular obstruction: myoglobin casts (szczególnie w kwaśnym moczu: Mb + Tamm-Horsfall protein → casts); (2) direct heme toxicity: ↑Fe-mediated ROS → tubular oxidative injury; (3) prerenal: ↓ECV (wysiłek + pocenie + trzecia przestrzeń); ALKALIZACJA MOCZU: teoria: pH > 6.5 → ↓Mb-cast formation + ↑solubility; praktyka: brak RCT dowodów; ryzyko: ↑Ca²⁺-PO₄ precipitates; COMPARTMENT SYNDROME: powikłanie crush injury / intense exercise → ↑pressure > 30 mmHg → fasciotomy; MYOGLOBIN vs HEMOGLOBIN w moczu: różnicowanie: centrifuge → czerwone supernatant = hemoglobin (freeHb); brunatne supernatant = myoglobin; color: hemoglobinuria: intensywnie czerwony; mioglobinuria: brunatny/herbaciano-brunatny ("cola-colored"); STATIN-INDUCED MYOPATHY: mechanizm: ↓CoQ10 (ubiquinone) → ↓ETC function + ↓mitochondrial bioenergetics; SLCO1B1 polymorphism: ↓statin transport → ↑statin plasma levels → ↑myopathy risk.',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },
  {
    topic_id: TOPIC, subtopic_id: S.zmeczeie, question_type: 'multiple',
    question_text: 'Które z poniższych czynników POPRAWNIE opisują adaptacje mięśni do treningu siłowego (hipertrofia)? (zaznacz wszystkie prawdziwe)',
    options: [
      { id: 'A', text: 'HIPERTROFIA MIĘŚNIOWA — MECHANIZMY: (1) MECHANOSENSING: stres mechaniczny → integryny + titin → ↑focal adhesion kinase (FAK) + ↑ERK1/2 → ↑mTORC1; (2) mTORC1 PATHWAY: IGF-1 → PI3K → Akt/PKB → mTORC1 aktywacja → (a) S6K1: fosorylacja rybosomów → ↑translacja + ↑ribosome biogeneza; (b) 4E-BP1: fosorylacja → ↑cap-dependent translation; (3) MYOSTATIN PATHWAY: myostatin (GDF-8) → ActRIIB → Smad2/3 → ↑MAFbx + ↑MuRF1 → ↑protein ubiquitination → ↑UPS → ↓mięśnie; trening siłowy → ↓myostatin + ↑follistatin (myostatin antagonist) → ↑hipertrofia; (4) SATELITARNE KOMÓRKI (myosatellite cells, Pax7+): quiescent → aktywowane (↑uszkodzenia, ↑MGF = mechano-growth factor) → proliferacja (MyoD+ myoblasty) → fuzja z włóknami → ↑jądra (↑nuclear domain)', is_correct: true },
      { id: 'B', text: 'NEURONALNA ADAPTACJA (SZYBKA, PIERWSZE 4–6 TYGODNIE): ↑siła BEZ ↑rozmiar mięśnia → ↑rekrutacja MU (więcej MU aktywowanych przy danej sile) + ↑częstotliwość impulsów (rate coding, 10–80 Hz) + ↑synchronizacja MU + ↓ko-aktywacja antagonistów (mniej "brake") + ↑wzbudzenie korowe (↑CAD, corticospinal drive); DUPLEX: cross-education (contralateral strength gain przy unilateral training): ~8% po 6 tyg; mechanizm: ↑ipsilateral motor cortex + corpus callosum; DETRAINING: Neural: szybka utrata (2 tygodnie) → ↓siła; Structural (hypertrophy): wolniejsza utrata (4–6 tyg)', is_correct: true },
      { id: 'C', text: 'PROTEIN TURNOVER I MPS/MPB: BASAL MPS (muscle protein synthesis): ~0.05–0.10 %/h; po treningu: ↑MPS 2–4× przez 24–48 h; po posiłku (leucyna): ↑MPS 2–3×; kombinacja trening + leucyna: ↑4–6×; MPB (muscle protein breakdown): ↑natychmiast po treningu (ubiquitin-proteasome UPS + autophagia); NET BALANCE (NB) = MPS – MPB; bez jedzenia: NB < 0 (katabolizm); z białkiem: NB > 0 (anabolizm); LEUCINE THRESHOLD: minimalna doza leucyny (~2–3 g per meal) → ↑mTORC1; 20–40 g białka per meal → max MPS; elderly: ↑leucine threshold (↑"anabolic resistance")', is_correct: true },
      { id: 'D', text: 'mTORC1 jest hamowany przez trening siłowy i leucynę (nie aktywowany); myostatin (GDF-8) stymuluje hipertrofię mięśniową (nie hamuje); komórki satelitarne (Pax7+) nie uczestniczą w regeneracji i wzroście mięśni; neuronalna adaptacja jest wolniejsza od strukturalnej hipertrofii (pojawia się po miesiącach); MAFbx (Muscle Atrophy F-box) jest białkiem anabolicznym (nie katabolicznym); cross-education to zjawisko, w którym trening jednej kończyny poprawia siłę tej samej kończyny (not the other limb)', is_correct: false },
    ],
    correct_answer: ['A', 'B', 'C'],
    explanation: '(A) REGULACJA MYOSTATIN: INHIBITORY MYOSTATINU: follistatin (najsilniejszy), GASP-1, FLRG (follistatin-like) → blokują ActRIIB; ActRIIB-Fc (ACE-031, bimagrumab): eksperymentalny, dla muscular dystrophy; BULLDOG MUSCLING (Belgian Blue cattle): myostatin null → double-muscling; "Mighty mice" (McPherron 1997): myostatin KO → 2–3× muscle mass; HUMAN CASE: 1 przypadek (rzadki): MSTN mutation → hipertrofia u niemowlęcia; MIOSTATYNA A STARZENIE: ↑myostatin z wiekiem → sarkopennia; IGF-1 SIGNALING DETAILS: IGF-1 (liver, autocrine) → IRS-1/2 → PI3K (p85+p110) → PIP3 → PDK1 → Akt/PKB (Thr308 + Ser473: mTORC2) → (1) mTORC1 (przez TSC1/2 inhibicja + PRAS40) → anabolizm; (2) FOXO3 fosorylacja → cytoplazma → ↓atrogeny (MAFbx/atrogin-1 + MuRF1) → ↓UPS → ↓atrofia; (B) MOTOR UNIT RECRUITMENT: small MU (slow, typ I) → FIRST (low threshold); large MU (fast, typ II) → later (high threshold); EMG amplitude: ↑przy ↑force (↑rekrutacja); rate coding: ↑force → ↑firing frequency 10 (resting) → 80–100 Hz (max); DOUBLETS (high-freq bursts): szybkie force development (startowe ruchy sportowe); (C) mTOR COMPLEX 1 vs 2: mTORC1: anabolizm (rapamycin sensitive); mTORC2: Akt Ser473 + cytoskeleton; BRANCHED-CHAIN AMINO ACIDS: leucyna > isoleucyna > walina w aktywacji mTOR; D — Fałsz: mTORC1: AKTYWOWANY; myostatin: HAMUJE; satelitarne: uczestniczą aktywnie; neuronal: SZYBSZA niż hypertrofia; MAFbx: KATABOLICZNE (atrogin-1); cross-education: PRZECIWNA kończyna.',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },

  // ── CHOROBY UKŁADU RUCHU (7) ──────────────────────────────────────────────
  {
    topic_id: TOPIC, subtopic_id: S.choroby, question_type: 'single',
    question_text: 'Reumatoidalne zapalenie stawów (RZS) jest autoimmunologiczną chorobą zapalną. Które stwierdzenie POPRAWNIE opisuje patomechanizm i leczenie RZS?',
    options: [
      { id: 'A', text: 'RZS PATOMECHANIZM: TRIGGER: RF (czynnik reumatoidalny, IgM anty-Fc-IgG) + anty-CCP (anty-cykliczne cytrulinowane peptydy = anty-PAD4/Padi4 → citrullinacja protein [filaggrin, vimentin, fibrinogen]) → kompleksy immunologiczne → aktywacja dopełniacza + komórek dendrytycznych + makrofagów; SYNOVIUM: pannus (granulacyjna tkanka: ↑fibroblasty-FLS + ↑CD4+ T-limfocyty [Th1: ↑IFN-γ; Th17: ↑IL-17] + makrofagi: ↑TNF-α, ↑IL-1β, ↑IL-6) → destrukcja chrząstki (↑MMP-1/3/13) + erozyjna destrukcja kości (↑RANKL → ↑osteoklasty); KLASYCZNE OBJAWY: symetryczne zapalenie MCP + PIP (nie DIP!) + sztywność poranna > 1h + RF+ + anty-CCP+ + HLA-DR4 ryzyko; LECZENIE: MTX (metotreksat) = anchor drug; bDMARDs: anty-TNF (etanercept, adalimumab, infliksymab) + anty-IL-6R (tocilizumab) + abatacept (CTLA4-Ig, ↓T-cell costim.) + rituksymab (anty-CD20, ↓B-cells); JAK inhibitory: tofacytynib (JAK1/3), barycytynib (JAK1/2)', is_correct: true },
      { id: 'B', text: 'RZS atakuje głównie DIP (dystalne stawy międzypaliczkowe) — typowe dla RZS (nie OA); RF (czynnik reumatoidalny) jest autoprzeciwciałem skierowanym przeciw jądrowemu DNA; pannus jest zdrową tkanką synowialną stymulującą regenerację chrząstki; TNF-α jest inhibitorem RANKL i chroni kości przed erozją; MTX (metotreksat) jest biologicznym lekiem (bDMARD); anty-CCP jest markerem zapalaenia osteoarthritis (OA), a nie RZS; tocilizumab hamuje TNF-α (nie IL-6R)', is_correct: false },
      { id: 'C', text: 'RZS jest chorobą niezapalną stawów (bez ↑OB, CRP); sztywność poranna typowa dla RZS trwa < 15 min (jak przy OA); anty-CCP ma niską swoistość dla RZS (< 50%); HLA-DR4 zmniejsza ryzyko RZS (a nie zwiększa); abatacept (CTLA4-Ig) blokuje IL-6 (nie kostymulację T-komórek); MMP (metaloproteinazy) chronią chrząstkę przed degradacją', is_correct: false },
      { id: 'D', text: 'RF (czynnik reumatoidalny) jest swoistym markerem dla RZS (nieobecny w innych chorobach); pannus jest tkanka łączna zastępująca błonę maziową w OA; fibroblasty synowialne (FLS) nie wytwarzają MMP; rytuksymab jest anty-TNF lekiem (nie anty-CD20); etanercept jest syntetycznym antagonistą receptora IL-6 (nie receptorem fuzyjnym TNF); RANKL nie bierze udziału w destrukcji kości przy RZS', is_correct: false },
    ],
    correct_answer: ['A'],
    explanation: 'RZS ZAAWANSOWANE: CITRULLINACJA: PAD4 (peptidylarginine deiminase 4) → konwersja arginina → cytrulina; ↑PAD4 w zapalnym środowisku → ↑citrullinowane białka → anty-CCP u predysponowanych (HLA-DRB1 "shared epitope"); ANTI-CCP: swoistość 95–99% (wyższa niż RF), czułość 70–80%; pojawia się PRZED objawami klinicznymi (pre-clinical RA); RA EXTRA-ARTICULAR: węzły reumatoidalne (elbow, RN = histologia: necrotic center + palisading macrophages) + płuco (ILD, effusion, BOOP) + serce (pericarditis, ↑CAD) + nerki (amyloidoza AA z chronic inflammation) + oczy (scleritis, episcleritis, dry eye = secondary Sjögren); FELTY SYNDROME: RA + splenomegaly + granulocytopenia; ↑LGL (large granular lymphocyte); ↑infection; HLA-DR4: "shared epitope" (QKRAA sequence in HLA-DRB1 β1 chain) → ↑RA severity + RF+ + extra-articular; HLA-DR4: ook risk of ↑CV mortality; JAK-STAT PATHWAY W RZS: cytokiny (IL-6, IL-12, IL-23, IFN) → JAK1/2/3/TYK2 → STAT1/3/6 → transkrypcja genów zapalnych; JAK inhibitory (tofacytynib, barycytynib): ↓JAK1/2/3 → ↓signaling → ↓zapalenie; ryzyko: herpes zoster reactivation + ↑DVT/PE (baricitinib BLACK BOX).',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },
  {
    topic_id: TOPIC, subtopic_id: S.choroby, question_type: 'multiple',
    question_text: 'Które z poniższych stwierdzeń POPRAWNIE opisują patomechanizm i klasyfikację złamań kości? (zaznacz wszystkie prawdziwe)',
    options: [
      { id: 'A', text: 'KLASYFIKACJA ZŁAMAŃ: (1) ZGODNIE Z MECHANIZMEM: traumatyczne (↑energia → przeciążenie) + zmęczeniowe/stresowe (repetitive low-load: szczególnie III metatarsal "march fracture", tibia, fibula → ↑ryzyko: biegacze, żołnierze, osteoporoza) + patologiczne (kość osłabiona: osteoporoza, przerzuty, szpiczak); (2) KOMPLETNOŚĆ: pełne (complete) + niepełne (greenstick u dzieci: korowa kość na jednej stronie) + zaklinowane (impacted); (3) KONFIGURACJA: poprzeczne (transverse, stabilne) + spiralne (torsja, niestabilne) + skośne (oblique) + wieloodłamowe (comminuted) + kompresyjne (vertebral); (4) OTWARTE vs ZAMKNIĘTE: Gustilo-Anderson klasyfikacja (I, II, IIIa, IIIb, IIIc)', is_correct: true },
      { id: 'B', text: 'GOJENIE ZŁAMAŃ (FRACTURE HEALING): FAZY: (1) HEMATOMA + ZAPALENIE (1–3 dni): złamanie → ↑krwawienie → skrzep + degranulacja płytek → ↑PDGF + ↑TGF-β + ↑VEGF → zap. naciek (neutrofile → makrofagi) → ↑IL-1 + ↑IL-6 + ↑TNF → ↑osteogeniczne prekursory; (2) TWORZENIE KOSTNINY MIĘKKIEJ (soft callus, 1–3 tyg): chondrocyty (periosteum MSC) → chrząstka → ↑FGF + ↑BMP-2/4/7; (3) KOSTNINA TWARDA (hard callus/bony callus, 3–12 tyg): mineralizacja → woven bone; (4) REMODELING (miesiące–lata): ↑BMU (basic multicellular unit) → lamellar bone; Wolff\'s law: bone deposited along stress lines', is_correct: true },
      { id: 'C', text: 'CZYNNIKI ZABURZAJĄCE GOJENIE: SYSTEMOWE: ↓estrogenów (→ ↑osteoklasty → ↓callus jakość) + ↑glikokortykosteroidy (↓OB proliferacja + ↓Ca²⁺ absorpcja) + ↑nikotyno (↓VEGF → ↓angiogeneza callus) + cukrzyca (↑AGEs → ↓collagen cross-linking + ↑PPARγ → ↓OB) + ↓wit. D (↓mineralizacja) + ↓białko (↓OB funkcja); LOKALNE: ruch na szczelinie złamania (↑rotacja/skręcanie > lepiej tolerowane niż skrajne ruchem), ischemia, infekcja, ↑dead space; ROLA NSAID: ↓PG E₂ (COX-2) → ↓osteogeneza (PGE₂ stymuluje OB) → ↑ryzyko nonunion; COX-2 knock-out → ↓fracture healing; pamidronate + bisphosphonate: ↑callus BUT ↓remodeling → delayed', is_correct: true },
      { id: 'D', text: 'Złamania zmęczeniowe (stresowe) dotyczą wyłącznie kości długich u sportowców bez czynników ryzyka; złamania greenstick są typowe wyłącznie dla dorosłych (nie dzieci); NSAID (ibuprofen, naproksen) przyspieszają gojenie złamań przez ↑prostaglandyn; remodeling kości (Wolff\'s law) działa niezgodnie z kierunkiem sił naprężeń; faza zapalna gojenia złamania powinna być hamowana korykosteroidami dla przyspieszenia gojenia; złamania otwarte klasyfikowane są wg Salter-Harris (nie Gustilo-Anderson)', is_correct: false },
    ],
    correct_answer: ['A', 'B', 'C'],
    explanation: '(A) ZŁAMANIA SZCZEGÓŁOWE: GREENSTICK: u dzieci → bowing + incomplete cortical break (periosteum intact one side); BUCKLE/TORUS: compression → cortical buckling, stable; SALTER-HARRIS (physeal fractures u dzieci): I: physis only; II: physis + metaphysis (most common); III: physis + epiphysis; IV: both; V: crush; GUSTILO-ANDERSON: I: < 1cm wound, clean; II: 1–10cm, moderate contamination; IIIa: adequate soft tissue cover; IIIb: periosteal stripping, flap needed; IIIc: vascular injury requiring repair; (B) NONUNION vs MALUNION: NONUNION: brak gojenia > 6–9 mies.; RADIOLOGICAL: hypertrophic (↑callus, "elephant foot": ↑vascularization, stabilizacja + dynamizacja wystarczy) vs atrophic (↓callus, ↑devascularized: wymaga graft + stabilizacja); PSEUDARTHROSIS: fibrocartylaginous tissue fills gap → false joint; BMP-2/7: rhBMP-2 (INFUSE): otwarte złamania tibia + spine fusion; ektopowe kostnienie: powikłanie; (C) FRACTURE HEALING OPTYMALIZACJA: NAGRZEWANIE (ultrasound: LIPUS = low intensity pulsed ultrasound) → ↑angiogeneza + ↑callus; ELECTRICAL STIMULATION: piezoelectric effect → ↑OB; witamina D + Ca: suplementacja poprawia wyniki; smoking cessation: ↑VEGF → ↑angiogeneza; D — Fałsz: zmęczeniowe: też osteoporoza/endokrynopatie; greenstick: DZIECI; NSAID: HAMUJĄ gojenie (↓PGE₂); Wolff\'s law: wzdłuż naprężeń; kortykosteroidy HAMUJĄ gojenie; Gustilo-Anderson: otwarte; Salter-Harris: fizyczne u dzieci.',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },
  {
    topic_id: TOPIC, subtopic_id: S.choroby, question_type: 'true_false',
    question_text: 'Oceń prawdziwość poniższych stwierdzeń dotyczących dny moczanowej i chorób metabolicznych kości:',
    options: [
      { id: 'A', text: 'DNAL MOCZANOWA (GOUT): PATOMECHANIZM: ↑kwas moczowy (hyperuricemia ≥ 6.8 mg/dL) → kryształy moczanu sodu (MSU, monosodium urate) → strącanie w stawach (chłodne: I MTP = podagra [ang. "great toe"], staw skokowy, kolano) → FAGOCYTOZA MSU przez neutrofile → ↑NLRP3 inflammasome → ↑IL-1β → ↑zapalenie (gout attack: ↑ból + zaczerwienienie + obrzęk + ↑temp lokalna); PRZEWLEKŁA: tophi (depozyty MSU w tkankach: ocho, stawy, nerki → nefropatia moczanowa); LECZENIE OSTREGO NAPADU: kolchicyna (↓tubulinę mikrotubuli neutrofili → ↓fagocytoza → ↓IL-1β) + NLPZ (indomethacin) + GKS; PROFILAKTYKA: allopurinol (xanthine oxidase inhibitor, XO, ↓produkcja UA) + febuksostat (XO inh.) + probenecid (↑renal UA excretion)', is_correct: true },
      { id: 'B', text: 'OSTEOMALACJA vs OSTEOPOROZA: OSTEOPOROZA: ↓masa kostna (↓mineralizacja + ↓macierz) → ↑ryzyko złamań (vertebral, Colles, hip) → diagnoza: DXA T-score ≤ −2.5; LECZENIE: bisfosfoniany (alendronat: ↓OC → ↓resorpcja) + denosumab (anty-RANKL → ↓OC) + teryparatyd (PTH 1-34, przerywanie: ↑OB) + romosozumab (anty-sclerostin: ↑OB + ↓OC); OSTEOMALACJA: ↓mineralizacja ORGANICZNA MACIERZY (osteoid accumulation) przy prawidłowej lub ↓BMD; przyczyny: niedobór wit. D + malabsorpcja + hipofosfatemia (TIO: tumor-induced osteomalacia, FGF-23↑) + CKD; ↑ALP (↑aktywność OB próbujących mineralizować); RIKETS (krzywica) = osteomalacja u dzieci → deformacje długich kości', is_correct: true },
      { id: 'C', text: 'Dna moczanowa jest spowodowana przez kryształy pirofosforanu wapnia (CPPD) — tak samo jak pseudodna (mylone terminy); kolchicyna w dnie działa przez blokowanie NLRP3 bezpośrednio (nie przez ↓tubuliny); allopurinol zwiększa produkcję kwasu moczowego (jest induktorem XO); w osteoporozie następuje ↑mineralizacji kości (jest odwrotnie niż opisano); osteomalacja jest synonimem osteoporozy (ta sama choroba); T-score DXA ≤ −1.0 definiuje osteoporozę (a nie ≤ −2.5); probenecid hamuje wydalanie kwasu moczowego przez nerki', is_correct: false },
    ],
    correct_answer: ['A', 'B'],
    explanation: 'A — DNAL SZCZEGÓŁY: PRZYCZYNY ↑UA: ↑produkcja: PRPP syntase mutation (X-linked) + HPRT deficiency (Lesch-Nyhan: ↑UA + choreoathetosis + self-mutilation) + ↑cell turnover (psoriasis, lymphoproliferative) + ↑purine intake (red meat, shellfish, beer-purines) + fruktoza (↑ATP degradation); ↓wydalanie: CKD (↓filtracja) + diuretyki tiazydowe/loop (↑UA reabsorpcja) + niska dawka aspiryny (↑reabsorpcja); FAZA INTERKRYTYCZNA: między napadami bezobjawowa; TOPHI: przewlekłe depozyty MSU → destrukcja stawów; lokalizacje: helix ucha, olecranon, achilles, phalanges; CPPD (PSEUDOGOUT): kryształy Ca-pyrophosphate → chondrocalcinosis → "pseudogout" → MRI/RTG: linia wapna w chrząstce; ↑wiek + ↑hemochromatosis + ↑hyperparathyroidism; KOLCHICYNA MECHANIZM: tubulin depolimeryzacja → ↓neutrofil motility + ↓inflammasome (ale głównie: ↓NALP3 via ↓tubulina, nie bezpośredni NLRP3 blocker); ↓superoxide production; ↓surface expressions of ↑E-selectin on endothelium; B — BISFOSFONIANY SZCZEGÓŁY: alendronate/risedronate/ibandronate/zoledronate; mechanizm: FPP synthase (farnesyl pyrophosphate synthase) inhibicja → ↓isoprenylation → ↓osteoclast signaling → ↓bone resorption; oral: słaba absorpcja → na czczo + wyprostowana pozycja 30 min (esophagitis!); zoledronate: iv raz/rok; SCLEROSTIN (SOST): produkowany przez osteocyty → hamuje Wnt (↓OB); romosozumab: anty-sclerostin mAb → ↑OB + ↓OC (dual mechanism); ryzyko: ↑CV events; C — Fałsz: gout: MOCZANOWE (MSU); pseudogout: CPPD; kolchicyna: poprzez ↓tubuliny (głównie); allopurinol: HAMUJE XO; osteoporoza: ↓MINERALIZACJA + ↓MACIERZ; osteomalacja ≠ osteoporoza; T-score ≤ −2.5; probenecid: ZWIĘKSZA wydalanie UA.',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },
  {
    topic_id: TOPIC, subtopic_id: S.choroby, question_type: 'single',
    question_text: 'Dystrofie mięśniowe są dziedzicznymi chorobami mięśni. Które stwierdzenie POPRAWNIE opisuje dystrofię mięśniową Duchenne\'a (DMD) i dostępne terapie?',
    options: [
      { id: 'A', text: 'DMD (DUCHENNE MUSCULAR DYSTROPHY): GEN I EPIDEMIOLOGIA: DMD gen (Xp21.2, 79 egzonów, największy gen człowieka: 2.4 Mb); dziedziczenie X-linked recessive → chłopcy 1:3500; matka nosicielka (50% przekaże synom); MECHANIZM: mutacja (najczęściej frameshift deletion egzonów 45–55) → brak produkcji dystrofiny (427 kDa rod protein, specks of cytoskeletal protein linking F-actin via ABD1 to ECM via DGC) → niestabilność sarkolemy → ↑Ca²⁺ leak → aktywacja calpain/caspase → nekroza; regeneracja → fibroza; PRZEBIEG KLINICZNY: pierwsze objawy 2–5 r.ż.: ↑upadki, Gowers\' sign, chód na palcach, przerost łydek (pseudohypertrophy: fibroza + tłuszcz); utrata chodzenia: ~12 r.ż.; kardiomiopatia (DCM) + resp. insufficiency → śmierć (bez leczenia ~20–25 r.ż.); MARKERY: CK >10 000 U/L; TERAPIA: kortykosteroidy (prednizon/deflazacort: ↑siła, opóźniają utratę chodzenia ~2 lata) + EXON SKIPPING: eteplirsen (etep-51-AMD, antisense oligonucleotide ASO) skip 51 → przywraca ramkę → truncated dystrofina (BMD-like); ataluren (PTC124): readthrough PTC (premature stop codon) → pełna dystrofina; gene therapy: AAV9-mini-dystrofin (badania kliniczne)', is_correct: true },
      { id: 'B', text: 'DMD jest chorobą autosomalną dominującą (nie X-linked recessive); dystrofina łączy miozynę bezpośrednio z błoną (nie aktynę); Gowers\' sign (wstawanie przy pomocy rąk wzdłuż nóg) jest objawem neuropatii (nie miopatii proksymalnej); ↑CK przy DMD jest łagodnie podwyższone (100–200 U/L); eteplirsen (ASO) powoduje reathrough stop kodonów (nie exon skipping); ataluren jest ukierunkowany na pacjentów z frameshift deletion (nie premature stop codon); kortykosteroidy są przeciwwskazane w DMD', is_correct: false },
      { id: 'C', text: 'DMD jest spowodowany mutacją w genie dystrobrevin (nie dystrofin); przerost łydek (pseudohypertrophy) jest wynikiem ↑masy mięśniowej (nie fibrozy + tłuszczu); kardiomiopatia nie jest powikłaniem DMD; śmierć bez leczenia następuje przed 10. rokiem życia; ASO (antisense oligonucleotide) leki działają na poziomie DNA (nie pre-mRNA splicing); exon skipping przywraca pełną ramkę odczytu, produkując dystrofinę identyczną z prawidłową (nie truncated)', is_correct: false },
      { id: 'D', text: 'BMD (Becker MD) jest cięższą formą niż DMD; w DMD wykazano ↑ekspresję dystrofiny (za dużo dystrofiny); kortykosteroidy (prednizon) opóźniają utratę chodzenia o 10 lat; AAV9 (adeno-associated virus 9) jest bakteriofagiem stosowanym w terapii genowej; eteplirsen jest lekiem biologicznym (monoklonalem) — nie ASO; DAPC (dystrophin-associated protein complex) jest zlokalizowany w macierzy kostnej, nie w sarkolenie', is_correct: false },
    ],
    correct_answer: ['A'],
    explanation: 'DMD KLINICZNE I TERAPEUTYCZNE SZCZEGÓŁY: DIAGNOSTYKA: ↑CK (często 50–100× norma już w niemowlęctwie, przed objawami!); EMG: miopatyczny; biopsia: dystrophin IHC (absent); genetyczne: MLPA (multiplex ligation-dependent probe amplification) → delecje; sekwencjonowanie: punktowe mutacje; MONITORING: echo serca (co 2 lata → DCM screen); spirometria (FVC% → ventilatory support); TERAPIA WSPOMAGAJĄCA: ACE inhibitory + beta-blokery → ↑prognoza kardiologiczna; NIV (non-invasive ventilation) przy FVC < 50%; KORTYKOSTEROIDY: deflazacort: mniej przyrostu masy ciała niż prednizon; daily > intermittent (10 days on/10 off); EXON SKIPPING STATUS (2024): eteplirsen (skip 51, ~13% chorych z odpowiednim genotypem); FDA accelerated approval 2016; kasimersen (skip 45, FDA 2021); wiltolarsen (skip 53, FDA 2020); viltolarsen (skip 53, Japonii → → USA 2020); GENE THERAPY: SRP-9001 (Sarepta, AAV9-microdystrophin-SRP): phase 3 (EMBARK trial); delandistrogene (dygeny, FDA-approved 2023): microdystrophin (R1-3 + CR + CT + H2 deleted) → 80% patients produce protein; BECKER MD (BMD): in-frame mutation → truncated but functional; mild phenotype; chodzenie > 16 r.ż.; ↑kardiomiopatia (może dominować); EMERY-DREIFUSS: EDMD1 (emerin, X-linked) + EDMD2 (lamin A/C, AD); scapuloperoneal atrophy + rigid spine + cardiac conduction defects.',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },
  {
    topic_id: TOPIC, subtopic_id: S.choroby, question_type: 'multiple',
    question_text: 'Które z poniższych stwierdzeń POPRAWNIE opisują patomechanizm i leczenie zwyrodnienia stawów (osteoarthritis, OA)? (zaznacz wszystkie prawdziwe)',
    options: [
      { id: 'A', text: 'OA PATOMECHANIZM: PIERWOTNA: ↑wiek + otyłość (↑BMI → ↑obciążenie mechaniczne + adipokiny: leptyna, adiponektyna → ↑synoviocyty M1 + ↑chondrocyty anabolizm) + ↑płeć żeńska + genetyka (TGFB1, GDF5 polimorfizmy); WTÓRNA: uraz (↑ACL tear → meniscectomy → ↑OA 20 lat) + dysplazja + avascular necrosis; PATOLOGIA CHRZĄSTKI: ↑IL-1β + ↑TNF-α (z makrofagów + chondrocytów) → ↑MMP-1/3/13 (collagenase, stromelysin) + ↑ADAMTS-4/5 (aggrecanase → ↓aggrecan) → ↓chrząstka; chondrocyty: ↑hypertroficzne (↑collagen X + ↑VEGF + ↑alkaline phosphatase) → apoptosis; ↓anabolizm: ↓TGF-β + ↓IGF-1 → ↓aggrecan + ↓collagen II', is_correct: true },
      { id: 'B', text: 'OA OBJAWY I DIAGNOSTYKA: BÓL: mechaniczny (gorsza przy ↑aktywności, lepszy w spoczynku, ↑po odpoczynku "initial stiffness" < 30 min — odróżnienie od RZS > 1h) + krepitacje + ↓zakres ruchu + obrzęk (zimny, bezbolesny w spoczynku) + deformacja (Heberden nodes = DIP osteophytes; Bouchard = PIP; genu valgum/varum); RTG: JOINT SPACE NARROWING + osteophytes + subchondral sclerosis + subchondral cysts (geodes); MRI: chrząstka + łąkotki + BML (bone marrow lesions: ↑ból + ↑progresja); USG: effusion + synovitis + osteophytes', is_correct: true },
      { id: 'C', text: 'OA LECZENIE: NIEFARMAKOLOGICZNE: ↓masa ciała (każdy 1 kg ↓ → 3–4 kg ↓ obciążenie kolana) + fizjoterapia (↑siła mięśni Q) + ortezy/wkładki; FARMAKOLOGICZNE: NLPZ (local/oral): ↓ból + ↓zapalenie (COX-2 selektywne = ↓GI risk); paracetamol: słabszy efekt w OA (2019 NICE: preferuj NLPZ topicalne); duloksetyna (SNRI): ↓ból w OA kolana (centralna sensityzacja); iniekcje: GKS (intraarticular, ↓ból 4–8 tyg; ↓regeneracja chrząstki przy powtarzaniu) + kwas hialuronowy (kontrowersyjny, EULAR 2019: warunkowo); DMOAD (disease modifying OA drugs): BRAK zatwierdzonych; badania: sprifermin (FGF18, ↑chrząstka), lorecivivint (CLK/DYRK inhibitor, ↑Wnt), injekcje PRP', is_correct: true },
      { id: 'D', text: 'OA (osteoarthritis) charakteryzuje się symetrycznym zajęciem stawów MCP i PIP jak w RZS; sztywność poranna w OA trwa > 1 godziny (jak w RZS, nie < 30 min); ADAMTS-4/5 (aggrecanases) chronią aggrecan przed degradacją; osteofity (bone spurs) są widoczne tylko w RTG i nie wykrywa się ich w USG; Heberden nodes to zmiany w PIP (nie DIP); duloksetyna jest lekiem pierwszego wyboru w OA przed NLPZ i fizjoterapią', is_correct: false },
    ],
    correct_answer: ['A', 'B', 'C'],
    explanation: '(A) BIOMARKERY OA: CTX-II (C-terminal crosslinked telopeptide of collagen type II): degradacja chrząstki; COMP (cartilage oligomeric matrix protein): ↑wczesna OA; CS-846 (chondroitin sulfate epitope): neoepitop agrekanu; PIIANP: synteza kolagenu II (anabolizm); ADIPOKINY W OA: LEPTYNA: pro-inflammatory (↑MMP + ↑IL-6) → ↑OA severity; ADIPONEKTYNA: dualna rola (anti-inflammatory centralnie, ale ↑MMP w OA); rezystyna + visfatin: pro-inflammatory; ↓ważenie → ↓adipokiny → ↓OA zapalenie; (B) OA SZCZEGÓŁOWE RADIOGRAFICZNE: KL GRADE (Kellgren-Lawrence): 0 = normalne; 1 = doubtful (małe osteofity); 2 = minimal (definite osteofity + possible narrowing); 3 = moderate (moderate narrowing + multiple osteofits); 4 = severe (complete narrowing + sclerosis + deformity); MRI MOAKS (MRI Osteoarthritis Knee Score): systematyczna ocena: chrząstka + BML + synovitis + effusion + osteophytes; BONE MARROW LESIONS (BML): ↑korelacja z bólem + ↑progresja; widoczne T2 MRI; (C) OA ARTHROPLASTY: TKA (total knee arthroplasty): złoty standard end-stage OA; implants: metal femoral + PE tibial + PE patellar; przeżycie implantu: 15–20 lat > 95%; powikłania: PE wear + aseptic loosening + PJI (periprosthetic joint infection) + VTE; UKA (unicompartmental, unicondylar): jednostronne OA, mniejsza interwencja; HTO (high tibial osteotomy): varus deformity → korekcja obciążenia; D — Fałsz: OA: DIP+PIP+CMC (carpometacarpal, "bazal thumb joint"); RZS: MCP+PIP; sztywność OA: < 30 min; ADAMTS: DEGRADUJĄ aggrecan; USG: WYKRYWA osteofity; Heberden: DIP (Bouchard: PIP); duloksetyna: nie pierwsza linia.',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },
  {
    topic_id: TOPIC, subtopic_id: S.choroby, question_type: 'true_false',
    question_text: 'Oceń prawdziwość poniższych stwierdzeń dotyczących chorób kręgosłupa i dyskopatii:',
    options: [
      { id: 'A', text: 'DYSKOPATIA KRĘGOSŁUPA LĘDŹWIOWEGO: ANATOMIA KRĄŻKA: nucleus pulposus (NP: ↑woda, proteoglikany/aggrecan, kolagen II, komórki chondrocytopodobne) + annulus fibrosus (AF: kolagen I, skośne lamelki) + płytki graniczne (hyalinowa chrząstka); DEGENERACJA: ↓proteoglikany NP → ↓ciśnienie osmotyczne → ↓hydratacja → ↓wysokość krążka → ↑stres na AF → ↑mikroszczelin → annular tear; PRZEPUKLINA: NP przebija AF → ucisk na korzenie nerwowe: L4/L5: ucisk L5 → ból/drętwwoność boczna stopa + ↑osłabienie dorsiflexji (foot drop); L5/S1: ucisk S1 → ból/mrowienie podeszwa + ↑osłabienie plantar flexion + ↓refleks Achillesa; REGUŁA: poziom krążka = poziom niżej wychodzący korzeń u dołu', is_correct: true },
      { id: 'B', text: 'STENOZA KANAŁU KRĘGOWEGO (SPINAL STENOSIS): PRZYCZYNY: ↑osteofity (facet joints + uncovertebral/Luschka joints) + ↑ligamentum flavum (przerost/kalcyfikacja) + ↓wysokość krążka → ↓AP diameter kanału; NEUROGENNY CHWIEJNY CHÓD (neurogenic claudication): ból + osłabienie + parastezje KD po chodzeniu → ulga przy ↑zgięcie (siedzenie, cycling, pochylenie do przodu = "shopping cart sign") → odróżnienie od claudicatio vascular (↑ABI, nie ulga przy zgięciu) + OBJAWY: obustronne (często) + "stocking-glove distribution"; DIAGNOSTYKA: MRI; LECZENIE: epidural steroids (intrasp. injekcja) + fizjoterapia; surgery: decompression laminektomia + TLIF/PLIF (interbody fusion)', is_correct: true },
      { id: 'C', text: 'W dyskopatii lędźwiowej L4/L5 ucisk dotyczy korzenia L4 (nie L5 jak wskazano w opisie); ból S1 (L5/S1) promieniuje na tylną/boczną powierzchnię uda (nie podeszwę stopy); stenoza kanału kręgowego objawia się wyłącznie jednostronnym bólem korzeniowym (nie neurologicznym claudicatio); "shopping cart sign" (ulga przy pochyleniu do przodu) wskazuje na naczyniowy claudicatio intermittens (nie neurogenny); ligamentum flavum nie ulega przerostowi w stenozie kanału; jądro miażdżyste (nucleus pulposus) zawiera głównie kolagen I (nie proteoglikany)', is_correct: false },
    ],
    correct_answer: ['A', 'B'],
    explanation: 'A — KORZENIE NERWOWE SZCZEGÓŁY: ANATOMIA REGUŁY DERMATOM/MIOTOM: L1: pachwina; L2: przednie udo; L3: przyśrodkowe kolano; L4: przyśrodkowa stopa + ↑refleks kolanowy; L5: grzbiet stopy + I–III palec + ↓peroneal (EM: ↓tibialis anterior EMG) + brak refleksu charakterystycznego; S1: boczna stopa + V palec + ↓refleks Achilles + ↑gastrocnemius; S2–4: krocze + pęcherz/rectum (cauda equina syndrome!); CAUDA EQUINA SYNDROME: ↑ostry L4/L5 lub L5/S1 centralny ucisk → niedrożność cauda equina: saddle anesthesia + ↑zatrzymanie moczu/stolca → NAGŁE CHIRURGICZNE; HERNIATION TYPES: protrusion (AF intact, NP bulges); extrusion (AF ruptures, NP in canal); sequestration (NP fragment free in canal); migration; DISC LEVELS FREQUENCY: L4/L5 (45%) + L5/S1 (40%) > L3/L4 (10%) >> cervical L5/C6; B — CERVICAL STENOSIS: C5/C6 (↓C6: osłabienie bicepsa + ↓brachioradialis reflex + drętwota kciuk/wskazujący); C6/C7 (↓C7: osłabienie tricepsa + ↓triceps reflex + drętwota palce środkowe); MYELOPATHY (rdzeń kręgowy ucisk): ↑siła (pyramidal: ↑tonus, ↑refleksy, Babinski) + ataksja (tylne sznury: proprioception) + spastyczność; SPINAL CORD INJURY LEVEL: ASIA (American Spinal Injury Association) classification: A (complete) → E (normal); neurogenic bladder; C — Fałsz: L4/L5: ucisk L5 (nie L4, bo L5 wychodzi poniżej L4/L5 disc na poziomie L4/L5); S1: podeszwa + V palec; stenoza: OBUSTRONNE, neurogenic claudicatio; shopping cart sign: NEUROGENNY; ligamentum flavum: PRZERASTA; NP: PROTEOGLIKANY + kolagen II (AF: kolagen I).',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },
  {
    topic_id: TOPIC, subtopic_id: S.choroby, question_type: 'single',
    question_text: 'Zesztywniające zapalenie stawów kręgosłupa (ZZSK) to seronegatywna spondyloartropatia. Które stwierdzenie POPRAWNIE opisuje patomechanizm i kryteria diagnostyczne ZZSK?',
    options: [
      { id: 'A', text: 'ZZSK (Ankylosing Spondylitis, AS): EPIDEMIOLOGIA: 0.1–0.5% populacji; M:K = 2–3:1 (częściej mężczyźni); wiek onset: 15–35 lat; GENETYKA: HLA-B27 (95% pacjentów AS vs 8% populacja) → MECHANIZM: (1) Artritis peptide: HLA-B27 prezentuje artrogeniczne peptydów → ↑CD8+ T-cells; (2) Misfolding: ↑HLA-B27 homodimers + unfolded protein response → ↑IL-23 + ↑Th17 (↑IL-17A); IL-17A → ↑syndesmofyty (nowe formacje kostne przy kościach): ↑Wnt + ↑BMP → ↑OB; IL-23 → Th17 axis jest kluczowym; OBJAWY: ból kręgosłupa zapalny (nocny, < 40 lat, ↑przy odpoczynku, ↑spoczynek → budzi, ↑aktywność → poprawia) + zapalenie stawów krzyżowo-biodrowych (sacroiliitis) + enthesitis (zapalenie przyczepów: Achilles, plantar fascia) + uveitis (zapalenie błony naczyniowej oka: 25–40%); OBJAWY RTG: sacroiliitis → "bamboo spine" (syndesmofyty, ankylosis) + square vertebrae; LECZENIE: NLPZ (1. linia) + fizjoterapia + anty-TNF (etanercept, adalimumab, certolizumab) + anty-IL-17A (secukinumab, ixekizumab) + anty-IL-23 (rizankizumab)', is_correct: true },
      { id: 'B', text: 'ZZSK jest seropozytywną artropatią z ↑RF i ↑anty-CCP; HLA-B27 jest obecny u 8% chorych na ZZSK (jak w populacji ogólnej); ból zapalny kręgosłupa nasila się przy ruchu (nie przy odpoczynku jak opisano); sacroiliitis nie jest objawem ZZSK; "bamboo spine" to RTG-obraz choroby Pageta; IL-17A nie uczestniczy w ZZSK (to szlak RZS); secukinumab (anty-IL-17A) jest zatwierdzony dla RZS (nie ZZSK)', is_correct: false },
      { id: 'C', text: 'ZZSK dotyczy głównie kobiet w wieku 50–70 lat; HLA-B27 jest całkowicie swoistym markerem ZZSK (100% chorych na ZZSK ma HLA-B27); ból zapalny kręgosłupa jest gorszy przy ↑aktywności fizycznej (jak mechaniczny); uveitis (zapalenie błony naczyniowej) nie jest powiązane z ZZSK; enthesitis (zapalenie przyczepów ścięgien) jest typowe dla RZS (nie ZZSK); anty-TNF nie jest wskazane w ZZSK', is_correct: false },
      { id: 'D', text: 'ZZSK jest chorobą stawów obwodowych (nie kręgosłupa); sakroiliitis (zapalenie stawów krzyżowo-biodrowych) jest objawem osteoarthritis; HLA-B27 jest genem HLA klasy II (jak HLA-DR4); "bamboo spine" oznacza złośliwe przerzuty do kręgosłupa; NLPZ są przeciwwskazane w ZZSK; secukinumab blokuje TNF-α (nie IL-17A)', is_correct: false },
    ],
    correct_answer: ['A'],
    explanation: 'SPONDYLOARTROPATIE (SpA) KLASYFIKACJA: ANKYLOSING SPONDYLITIS + reactive arthritis (Reiter syndrome: urethritis + arthritis + uveitis po zakażeniu Chlamydia/GI) + psoriatic arthritis (PsA: asymetryczne, DIP, sausage digits/daktylitis, nail changes, enthesitis, HLA-B27 15–50%) + enteropathic arthritis (IBD: Crohn + UC) + undifferentiated SpA; WSPÓLNE CECHY SpA: HLA-B27 + sakroiliitis + zapalny ból pleców + enthesitis + uveitis + brak RF/anty-CCP ("seronegatywne") + IL-23/IL-17 szlak; HLA-B27 I ZZSK: HLA-B27+ → ryzyko ZZSK = 2–5% (bez FH) → 15–20% (z FH ZZSK); populacja ogólna: 80% HLA-B27+ NIGDY nie dostanie ZZSK; MEVT (missing self theory) + inne teorie; NOVA KLASYFIKACJA: axial SpA: radiographic (ZZSK) + non-radiographic (nr-axSpA, MRI zapalenie BEZ RTG zmian); ZZSK = late stage; DIAGNOZA: ASAS criteria (Assessment of SpondyloArthritis international Society): chronic low back pain < 45 lat + HLA-B27 + ≥ 2 SpA features OR sacroiliitis (MRI/RTG) + ≥ 1 SpA feature; EXTRAARTICULAR MANIFESTATIONS: uveitis (anterior: HLA-B27+, unilateral, acute, recurrent) + IBD (10%) + psoriasis (10%) + aortitis + amyloidosis; LECZENIE: NLPZ: ciągłe (słabnie progresja? kontrowersyjne) + fizjoterapia: kluczowa; biologiczne: anty-TNF (1. biologic line: etanercept, adalimumab, certolizumab, golimumab, infliximab) → jeśli NLPZ nieskuteczne; anty-IL-17A (secukinumab, ixekizumab): alternatywa; bimekizumab (anty-IL-17A + IL-17F): nowy; risankizumab/guselkumab (anty-IL-23): badania kliniczne; MAŁE CZĄSTECZKI: JAK inhibitory (tofacytynib, upadacytynib): badania kliniczne; upadacytynib: FDA 2022 AS.',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },

]

function post(body) {
  return new Promise((resolve, reject) => {
    const data = Buffer.from(JSON.stringify(body), 'utf8')
    const req = https.request({
      hostname: 'gzpxvfaftvkfwpvljcrk.supabase.co',
      path: '/rest/v1/questions', method: 'POST',
      headers: {
        apikey: KEY, Authorization: 'Bearer ' + KEY,
        'Content-Type': 'application/json', Prefer: 'return=minimal',
        'Content-Length': data.length,
      },
    }, res => {
      let r = ''; res.on('data', c => r += c)
      res.on('end', () => resolve({ status: res.statusCode, body: r }))
    })
    req.on('error', reject); req.write(data); req.end()
  })
}

async function main() {
  console.log(`Seeding batch 5 (${questions.length} questions)...`)
  for (const q of questions) {
    const { status, body } = await post(q)
    const ok = status === 201 || status === 204
    if (!ok) console.log('ERR', status, body.slice(0, 200))
    else console.log('OK', `[${q.question_type}]`, q.question_text.slice(0, 60).replace(/\n/g, ' '))
  }
  console.log('Done.')
}
main().catch(err => { console.error(err); process.exit(1) })
