// Seed batch 4/5 — Układ ruchu człowieka
// Mechanizm skurczu mięśnia (9) + Zmęczenie mięśni (1) = 10 questions

const https = require('https')
const KEY = process.env.SUPABASE_SERVICE_ROLE_KEY || ''
const TOPIC = '42b3edde-2027-4bbb-8a90-38568031d9b0'

const S = {
  skurcz:   '33ff4db4-4b68-4c16-846d-f6db534b5752',
  zmeczeie: '957b8505-0f02-4284-900d-854311b0952a',
}

const questions = [

  // ── MECHANIZM SKURCZU MIĘŚNIA (9) ────────────────────────────────────────
  {
    topic_id: TOPIC, subtopic_id: S.skurcz, question_type: 'single',
    question_text: 'Mechanizm skurczu mięśnia szkieletowego opiera się na teorii ślizgania filamentów. Który opis POPRAWNIE wyjaśnia kolejne etapy tego procesu?',
    options: [
      { id: 'A', text: 'TEORIA ŚLIZGANIA FILAMENTÓW (Huxley 1957): filamenty nie skracają się → ŚLIZGAJĄ aktyna po miozynie; KOLEJNOŚĆ: (1) AP w motoneuronie → NMJ → ACh → EPP → AP sarkolemy; (2) AP → kanaliki T (T-tubule: wpuklenia sarkolemy co Z-line) → DHPR (dihydropyridine receptor, L-type Ca²⁺ channel): konformacja → sprzężenie elektromechaniczne z RYR1 (ryanodine receptor type 1) SR → otwarcie RYR1 → wypływ Ca²⁺ z SR do sarkoplazmy; (3) Ca²⁺ (Kd ~1 μM) → TnC (subjednostka C troponiny) → zmiana konformacji TnI + TnT → przemieszczenie tropomiozyny → odsłonięcie miejsc wiązania miozyny na aktynie; (4) główki miozyny → cykl poprzecznych mostków → ślizganie aktyny → skrócenie sarkomery', is_correct: true },
      { id: 'B', text: 'Skurcz mięśniowy polega na skróceniu grubych filamentów miozyny (nie na ślizganiu); T-tubule są kanalami Cl⁻; DHPR jest receptorem na siateczce endoplazmatycznej (nie sarkolema); RYR1 uwalnia Ca²⁺ z mitochondriów; tropomiozyna aktywuje aktynę przez wiązanie Ca²⁺ (bez pośrednictwa troponiny); Ca²⁺ wiąże się z TnI (nie TnC); sprzężenie elektromechaniczne zależy od IP₃ (a nie DHPR-RYR1)', is_correct: false },
      { id: 'C', text: 'Filamenty aktyny skracają się w procesie skurczu; T-tubule przenoszą Ca²⁺ z siateczki do sarkoplazmy (nie AP); tropomiozyna w stanie spoczynku odsłania miejsca wiążące miozyny na aktynie; Ca²⁺ wiąże się wyłącznie z miozyną (nie troponinę); RYR1 to kinaza tyrozynowa fosforylująca miozynę; skurcz mięśni gładkich jest identyczny z mechanizmem mięśni szkieletowych (DHPR-RYR1)', is_correct: false },
      { id: 'D', text: 'T-tubule przekazują Ca²⁺ bezpośrednio na główki miozyny (bez pośrednictwa troponiny i tropomiozyny); siateczka sarkoplazmatyczna (SR) absorbuje Ca²⁺ podczas skurczu (nie uwalnia); DHPR = receptor ryanodynowy (te same białko); tropomiozyna uniemożliwia wiązanie aktyny z aktyną (nie miozyny z aktyną); skurcz mięśnia sercowego jest regulowany przez IP₃ receptory (nie RYR2)', is_correct: false },
    ],
    correct_answer: ['A'],
    explanation: 'KANALIKI T I SR SZCZEGÓŁY: TRIADA (skeletal): 1 T-tubule + 2 cysternae terminales SR = triad; zlokalizowane przy Z-disc (u ssaków); DIADA (cardiac): 1 T-tubule + 1 SR cisterna; przy Z-disc; SPRZĘŻENIE EK: SKELETAL: DHPR (Cav1.1) → mechanicznie sprzężony z RYR1 (foot protein) → otwiera RYR1 bez Ca²⁺ wejścia; CARDIAC: DHPR (Cav1.2) → Ca²⁺ wejście → CICR (Ca²⁺-induced Ca²⁺ release) przez RYR2 → ↑Ca²⁺ znacznie większy Ca²⁺ z SR; RYANODINE RECEPTOR (RYR): RYR1 (skeletal) + RYR2 (cardiac) + RYR3 (brain, smooth) → szybkie mega-kanały SR; modulatory: Ca²⁺ + FKBP12 + FKBP12.6 + calmodulin + PKA + CaM kinase; MALIGNANT HYPERTHERMIA (MH): mutacja RYR1 (lub DHPR) → nadwrażliwość na anestetycy wziewne (halotan, sevolluran) / sukcynylocholinę → niekontrolowane uwolnienie Ca²⁺ → hipertermia + rigor + rabdomioliza + ↑lactate + ↑CO₂; leczenie: DANTROLENE (RYR1 blocker) → pierwszy wybór; chłodzenie + wsparcie; CENTRAL CORE DISEASE: congenital myopathy, mutacja RYR1, ↓aktywność mitochondrialna.',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },
  {
    topic_id: TOPIC, subtopic_id: S.skurcz, question_type: 'multiple',
    question_text: 'Które z poniższych stwierdzeń POPRAWNIE opisują cykl poprzecznych mostków (cross-bridge cycle) i rolę ATP? (zaznacz wszystkie prawdziwe)',
    options: [
      { id: 'A', text: 'CYKL POPRZECZNYCH MOSTKÓW (LYMN-TAYLOR, 4 ETAPY): (1) UWOLNIENIE ADP+Pi: główka miozyny-ADP-Pi → aktyna → szybkie dołączenie (silna wiązanie) + uwolnienie Pi (power stroke inicjacja) → ADP odejście → ↑nakręcenie główki → POWER STROKE (siłowy ruch, ~5 nm): aktyna przesuwa się wzdłuż miozyny → sarkomera się skraca; (2) RIGOR STATE: główka mocno przywiązana do aktyny (brak ATP) → stężenie pośmiertne; (3) ATP DOŁĄCZENIE: ATP wiąże się z domeną S1 → szybkie ODERWANIE od aktyny ("detachment"); (4) HYDROLIZA ATP: ATP → ADP+Pi (przez ATPaze główki miozyny) → naciąganie główki ("cocking") → powrót do pozycji główki → gotowość do nowego cyklu', is_correct: true },
      { id: 'B', text: 'ENERGETYKA SKURCZU: ATP pełni 3 role w skurczu mięśniowym: (1) hydroliza → siłowy ruch mostku (power stroke energetyzacja); (2) oderwanie główki od aktyny po skurczu (detachment); (3) SERCA2 (SERCA = SR Ca²⁺-ATPase): pompowanie Ca²⁺ z powrotem do SR po skurczu (relaxation); fosfolamban (PLB): inhibitor SERCA2 w spoczynku → β1-AR → PKA → ↑PLB fosforylacja → ↓PLB inhibicja → ↑SERCA2 → ↑relaksacja (lusitropy); LUSITROPY: ↑szybkość relaksacji; ↑lusitropy: β1-agonista, PDE3-inhibitor, Ca²⁺-sensityzatory; ↓lusitropy: hipotyreoza, ischemia', is_correct: true },
      { id: 'C', text: 'RIGOR MORTIS (stężenie pośmiertne): po śmierci → ↓ATP (brak syntezy) → główki miozyny nie mogą się oderwać od aktyny → RIGOR STATE; pojawia się 2–6h po śmierci (zależy od temp, aktywności) → maksimum 12–24h → zanika 24–48h (autoliza białek mięśniowych); forensyczne znaczenie: czas śmierci + pozycja ciała; wyjątek: CADAVERIC SPASM (instantaneous rigor) przy nagłej śmierci z intensywnym wysiłkiem (utopienie, elektrowstrząs)', is_correct: true },
      { id: 'D', text: 'Power stroke (siłowy ruch główki miozyny) jest możliwy bez ATP (ATP nie uczestniczy w power stroke, tylko w cyklicznym odłączeniu); rigor mortis wynika z nagromadzenia ADP w mięśniach; SERCA (SR Ca²⁺ ATPase) pompuje Ca²⁺ z SR do sarkoplazmy; fosfolamban stymuluje (nie hamuje) SERCA2; główka miozyny wiąże ATP po power stroke aby oderwać się od aktyny (to prawda), ale ADP jest wymagane do inicjacji power stroke (błąd: Pi jest kluczowe)', is_correct: false },
    ],
    correct_answer: ['A', 'B', 'C'],
    explanation: '(A) SZCZEGÓŁY POWER STROKE: konformacja główki myozynowej: PRE-POWER STROKE (naciągnięty, "cocked" — ATP hydrolizowane, ADP+Pi na miejscu); POST-POWER STROKE (odprężony — ADP+Pi uwolniony); ANGLE: zmiana kąta główki ~45° → 90° → przemieszczenie ~5–8 nm per cykl; 50–100 cykli/s (szybkie włókna); MYOSIN ISOFORMS: MYH7 (β-MHC): sercowe (dominant dorosłych) + wolne szkieletowe (typ I); MYH6 (α-MHC): sercowe płodu + dorosłych (mało) → szybszy ATPase; MYH2: szkieletowe IIa; MYH1: IIx; HCM mutacje: głównie MYH7 (40%) + MYBPC3 (40%); (B) PHOSPHOLAMBAN KLINIKA: PLB mutacje → DCM (↑PLB inhibicja SERCA2 → ↓Ca²⁺ uptake → ↑diastoliczny Ca²⁺ → ↑afterdepolaryzacje → arytmie); ↑PLB (HF): ↓SERCA2 aktywność → ↓lusitropy → diastoliczna dysfunkcja; leczenie HF: milrinone (PDE3 inhibitor) → ↑cAMP → ↑PKA → ↑PLB fosforylacja → ↑SERCA2 → ↑CO; (C) CIEPŁOTA CIAŁA I RIGOR: przy niskiej temp: ↓szybkość hydrolizy ATP → wolniejszy rigor onset; przy wysokiej (gorączka, ogień): szybszy; CADAVERIC SPASM: kontrowersyjny; może być artefaktem; użyteczny w medycynie sądowej do rekonstrukcji pozycji; D — Fałsz: power stroke: wymaga HYDROLIZY ATP (ADP+Pi uwolnienie → energy); rigor: brak ATP (nie ↑ADP); SERCA: DO SR (re-uptake); PLB: HAMUJE SERCA2; ADP → power stroke: Pi jest kluczowe (Pi release → aktywacja power stroke), ale ADP na miejscu przez power stroke → ADP release po.',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },
  {
    topic_id: TOPIC, subtopic_id: S.skurcz, question_type: 'true_false',
    question_text: 'Oceń prawdziwość poniższych stwierdzeń dotyczących roli wapnia w skurczu mięśniowym:',
    options: [
      { id: 'A', text: 'KINETYKA CALCIUM W SKURCZU SZKIELETOWYM: spoczynkowe [Ca²⁺]i < 0.1 μM; podczas skurczu: → 1–10 μM; ½-czas wzrostu: < 1 ms (bardzo szybkie); ½-czas relaksacji: 30–100 ms (pompowanie do SR przez SERCA); ŹRÓDŁA Ca²⁺: > 95% z SR (DHPR-RYR1); < 5% zewnątrzkomórkowe; SERCA1 (szkielet, szybkie włókna) vs SERCA2a (wolne włókna + sercowe, regulowane przez PLB) vs SERCA2b (powszechny, gładki); PMCA (plasma membrane Ca²⁺ ATPase): wolna pompa Na⁺/Ca²⁺ exchange → NCX: 3 Na⁺:1 Ca²⁺ → wyrzut Ca²⁺ (serce: ~ 25% relaksacyjny Ca²⁺ przez NCX)', is_correct: true },
      { id: 'B', text: 'MIĘSIEŃ GŁADKI — CA²⁺ REGULACJA: ↑Ca²⁺ (z SR przez IP₃R lub zewnątrz przez VGCC/ROC) → Ca²⁺ + kalmodulina (CaM, 4 Ca²⁺-miejsca) → Ca²⁺/CaM kompleks → aktywacja MLCK (myosin light chain kinase) → fosforylacja MLC (Ser19) → aktywacja miozyny → skurcz; ROZKURCZ: MLCP (myosin light chain phosphatase) defosoryluje MLC → rozkurcz; PHARMAKOLOGIA: fenoksybenzamina (α-blokuje → ↓IP₃ → ↓Ca²⁺ → ↓skurcz naczyniowy); nitroprusydek, NO → ↑cGMP → PKG → ↑MLCP → rozkurcz naczyń; CALCIUM-SENSITIZATION: RhoA/ROCK → fosforylacja MLCP → inhibicja MLCP → ↑MLC-P → ↑skurcz przy tym samym Ca²⁺; fasudil (ROCK inhibitor) → rozkurcz', is_correct: true },
      { id: 'C', text: 'W mięśniu szkieletowym Ca²⁺ pochodzi głównie z zewnątrz komórki (nie z SR); SERCA pompuje Ca²⁺ z SR do sarkoplazmy (na zewnątrz SR); kalmodulina jest regulatorem skurczu mięśnia szkieletowego (tak jak w gładkim); relaksacja mięśnia szkieletowego nie wymaga ATP (Ca²⁺ dyfunduje samoczynnie do SR); w mięśniu gładkim brak troponiny jest kompensowany przez kaldesmon i kalmodulinę bez udziału MLCK; regulacja skurczu mięśnia gładkiego i szkieletowego jest identyczna', is_correct: false },
    ],
    correct_answer: ['A', 'B'],
    explanation: 'A — Prawda: EXCITATION-CONTRACTION COUPLING RÓŻNICE: SKELETAL: DHPR (mechanicznie) → RYR1; szybkie (< 1 ms); < 5% zewnątrzkomórkowe Ca²⁺; CARDIAC: DHPR (Cav1.2, L-type) → Ca²⁺ wejście (ICaL) → CICR przez RYR2 (większa amplituda); ~25% Ca²⁺ z zewnątrz, 75% z SR; SMOOTH: IP₃R (ER) + ROC (receptor-operated) + VGCC (typ L) → ↑Ca²⁺i; brak T-tubule (caveolae ≈ pełnią analogiczną funkcję); LEKI ANTY-CA²⁺: dantrolene: blokuje RYR1 → leczenie MH; CCB (dihydropyridines: nifedipina, amlodipin → naczynia; non-DHP: verapamil, diltiazem → serce + naczynia); B — Prawda: RHOKINASE PATHWAY: ang II + ET-1 + TXA₂ → Gα12/13 → RhoGEF → RhoA-GTP → ROCK (Rho-associated kinase) → fosorylacja MYPT1 (subunit of MLCP) → ↓MLCP aktywność → ↑MLC-P → ↑skurcz; CALCIUM SENSITIZATION: ważna w: pulmonary hypertension (PAH), vasospasm (Raynaud, subarachnoid hemorrhage vasospasm), bladder overactivity; FASUDIL: ROCK inhibitor; Japan-approved for cerebral vasospasm; badania w PAH + HF; C — Fałsz: Ca²⁺ szkieletowy: GŁÓWNIE z SR (> 95%); SERCA: DO SR (nie z SR); kalmodulina: w GŁADKIM (nie szkieletowym, który ma troponinę); relaksacja: WYMAGA ATP (SERCA); w gładkim: brak troponiny → kalmodulin/MLCK zastępuje troponinę; regulatory szkieletowy (troponina) ≠ gładki (MLCK/kalmodulin).',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },
  {
    topic_id: TOPIC, subtopic_id: S.skurcz, question_type: 'single',
    question_text: 'Złącze nerwowo-mięśniowe (NMJ) jest miejscem przekazywania sygnału między nerwem a mięśniem. Który opis POPRAWNIE wyjaśnia farmakologię i choroby NMJ?',
    options: [
      { id: 'A', text: 'NMJ FARMAKOLOGIA I CHOROBY: (1) TOKSYNY PRESYNAPTYCZNE: botulinum toxin (BTX, Clostridium botulinum, 7 serotypów A–G): proteinaza cynkowa → cleavage SNARE proteins: typ A/E → SNAP-25; B/D → VAMP (synaptobrevin); C → syntaxin → ↓ACh egzocytoza → flaccid paralysis; KLINICZNE: botulizm pokarmowy (canning), niemowlęcy (miód), ranowy; leczenie: antytoksyna + wsparcie oddechu; TERAPEUTYCZNE: OnabotulinumA (Botox): spastyczność, dystonia, kosmetyka, migrena, pęcherz nadczynny; (2) SNAKEVENOM: α-bungarotoxin (Bungarus multicinctus) → nieodwracalne blokowanie nAChR; badania naukowe + diagnostyka; (3) DEPOLARYZUJĄCE BLOKERY NMJ: succinylcholine (suxamethonium) → nAChR agonista → depolaryzacja → fascylacje → blokada (phase I); metabolizm: plazmatyczna cholinesteraza (pseudoChE, BuChE)', is_correct: true },
      { id: 'B', text: 'Botulinum toxin stymuluje wydzielanie ACh (nie hamuje); succinylcholine jest antagonistą nAChR (nie agonistą); botulizm leczony jest neostygminą (nie antytoksyną); α-bungarotoxin pochodzi z motylicy (nie węża); SNAP-25 jest białkiem mitochondrialnym; neostygmina hamuje uwalnianie ACh z pęcherzyków synaptycznych; spastyczność leczona jest succilinestą (depolaryzującym blokerem)', is_correct: false },
      { id: 'C', text: 'SNARE proteins (SNAP-25, VAMP/synaptobrevin, syntaxin) nie uczestniczą w egzocytozie ACh; botulinum toxin jest antybiotykiem stosowanym w leczeniu zakażeń Clostridium; neostygmina jest agonistą nAChR (nie inhibitorem AChE); Lambert-Eaton Myasthenic Syndrome (LEMS) jest chorobą autoimmunologiczną skierowaną przeciw nAChR (nie VGCC); blokery niedepolaryzujące (pancuronium) działają jak agonisty nAChR', is_correct: false },
      { id: 'D', text: 'Botulinum toxin działa postsynaptycznie, blokując nAChR; succinylcholine jest inhibitorem AChE i zwiększa ilość ACh w szczelinie; α-bungarotoxin stymuluje VGCC; płaszczkowiec zacski (manta ray) produkuje botulinum toxin; neostygmina jest agonistą muskarynowym; LEMS jest chorobą spowodowaną autoprzeciwciałami przeciwko receptor miozynowy', is_correct: false },
    ],
    correct_answer: ['A'],
    explanation: 'NMJ FARMAKOLOGIA SZCZEGÓŁY: NIEDEPOLARYZUJĄCE (NON-DEPOLARIZING) BLOKERY: konkurencyjni antagoniści nAChR: pankuronium (steroyd, długi), wekuronium (śr), atrakurium (ok. 25 min, spontaniczny rozkład Hofmann), rocuronium (szybki onset, sugammadeks odwraca); odwracalność: sugammadeks (cyklodekstryna, encapsulates rocuronium/vecuronium), neostygmina/pirydostygmina (AChE inhibitory → ↑ACh → kompetuje); SUCCINYLCHOLINE: phase I (depolaryzacja/fascylacje → blokada 5–10 min) → phase II (desensytyzacja, po długim); PSEUDOCHE DEFICIENCY: dziedziczna (dibucaine number test) → ↑czas działania sukcynylocholiny → "scoline apnoea"; BOTULINUM TOXIN MECHANISM DETAILS: light chain = Zn²⁺ metalloproteinaza; VAMP/synaptobrevin = presynaptyczna pęcherzykowa błonka; SNAP-25 = presynaptyczna; syntaxin = presynaptyczna SNARE (kotwica); BTX-A i -C → nie całkowita inaktywacja → efekt reversible (3–6 mies.); po reinerwacji: nowe sprouts → powrót funkcji; NEOSTIGMINE: penetracja BBB słaba → nie leczy centralnych muskarynowych efektów; PHYSOSTIGMINE: przenika BBB → leczenie cholinergicznego niedoboru centralnego (Alzheimer, atropine overdose → cholinergiczny kryzys).',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },
  {
    topic_id: TOPIC, subtopic_id: S.skurcz, question_type: 'multiple',
    question_text: 'Które z poniższych stwierdzeń POPRAWNIE opisują regulację skurczu mięśnia sercowego (EC coupling cardiac)? (zaznacz wszystkie prawdziwe)',
    options: [
      { id: 'A', text: 'CARDIAC EC COUPLING: ICaL (L-type Ca²⁺ channel, DHPR, Cav1.2) → Ca²⁺ wejście w każdym AP → CICR (Ca²⁺-induced Ca²⁺ release) przez RYR2 (ryanodine receptor 2) siateczki SR → [Ca²⁺]i ↑ 0.1 → 1 μM → TnC wiąże Ca²⁺ → przemieszczenie tropomiozyny → cross-bridge → skurcz; RELAKSACJA: SERCA2a (SR Ca²⁺-ATPase) → 75% Ca²⁺ powrót do SR; NCX (Na⁺/Ca²⁺ exchanger, 3Na:1Ca) → 25% Ca²⁺ wyrzut; SERCA2a regulowana przez PHOSPHOLAMBAN (PLB): niefosforylowany PLB = inhibitor SERCA; β1-AR → PKA → fosforylacja PLB (Ser16) + TnI (Ser23/24) → ↑SERCA2a + ↑TnI → ↑relaksacja (positive lusitropy)', is_correct: true },
      { id: 'B', text: 'FRANK-STARLING MECHANISM: ↑preload → ↑EDV → ↑sarcomere length (do L0) → ↑cross-bridge overlap → ↑aktyna-miozyna interaction + ↑TnC Ca²⁺ sensitivity (titin stretch → ↑lattice spacing → ↑cross-bridge): efekty: ↑SV + ↑CO; INOTROPIA: ↑inotropy: β1-AR (↑cAMP → PKA → ↑Ca²⁺ wejście + ↑SERCA) + digoksyna (↓Na/K ATPase → ↑Na⁺i → ↑NCX reverse → ↑Ca²⁺i) + Ca²⁺ sensityzatory (levosimendan: TnC stabilizacja + PDE inhibition); ↓inotropy: β1-blokery + CCB (werapamil, diltiazem) + kwasica (H⁺ kompetuje z Ca²⁺ o TnC)', is_correct: true },
      { id: 'C', text: 'HF I EC COUPLING: CHRONIC HF: ↓RYR2 (mniej RYR + lek fosforylacji przez PKA → leaky RYR) → ↑Ca²⁺ LEAK → ↑Ca²⁺ sarkoplazma w diastole → ↓SERCA2a (↓ekspresja + ↑PLB hamowanie) → ↓Ca²⁺ do SR → ↓transient Ca²⁺ → ↓skurcz; ↑NCX (compensatory) → ↓Ca²⁺ + ↑depolaryzacja (3Na⁺ → DAD delayed afterdepolarization → VT/VF risk); TERAPIE EKSPERYMENTALNE: AAV-SERCA2a gene therapy (CUPID trial → neutralne wyniki); MYK-461 (CK-274): inhibitor myozyny (↓ATPase) → ↓hypercontractility HCM; danicamtiv (myosin activator) → ↑systolic function', is_correct: true },
      { id: 'D', text: 'ICaL (L-type Ca²⁺ channel) w kardiomiocytach jest głównym kanałem K⁺ (nie Ca²⁺); CICR oznacza "Ca²⁺ inhibited Ca²⁺ release" (nie indukowane); SERCA2a pompuje Ca²⁺ z SR do sarkoplazmy (a nie w odwrotnym kierunku); NCX wymienia 1 Na⁺ za 1 Ca²⁺; PLB (phospholamban) stymuluje SERCA2a (nie hamuje); levosimendan (Ca²⁺ sensitizer) zmniejsza skurcz (negatywna inotropy)', is_correct: false },
    ],
    correct_answer: ['A', 'B', 'C'],
    explanation: '(A) SPARKS I WAVES: Ca²⁺ SPARKS: lokalne, spontaniczne otwarcia RYR2 (1–10 jednostek) w spoczynku → Ca²⁺ "iskry" (widoczne confocal); normalne → nowe cykl; HF: ↑spark frequency (↑leak); Ca²⁺ WAVES: łańcuch sparks → "fala" przez kardiomiocyt → DAD (delayed afterdepolarization) → EAD (early) → triggered arrhythmia; LEKI: flekainid: Nav1.5 bloker (antyarytmia) ale TAKŻE blokuje RYR2 → ↓Ca²⁺ leak → zmniejsza DAD/EAD; dantrolene: RYR bloker → eksperymentalnie w HF; (B) DIGOXIN MECHANISM DETAILS: ↓Na⁺/K⁺-ATPase (α-subunit Ser+His) → ↑Na⁺i → NCX reverse → ↑Ca²⁺i → ↑SV (positive inotropy); NARROW THERAPEUTIC INDEX: terapeutyczny 0.5–0.9 ng/mL; toksyczny > 2 ng/mL; objawy toksyczności: GI (N/V) + neurological (yellow-green halos = xanthopsia) + arytmie (PVC, heart block); leczenie: DigiFab (antibody fragments); hyperkaliemia: protects against toxicity (K+ competes at ATPase); hypokalemia: ↑toxicity; (C) LEVOSIMENDAN: dual mechanism: (1) Ca²⁺ sensitizer (TnC binding at Ser → stabilizacja Ca²⁺/TnC → ↑skurcz bez ↑Ca²⁺i); (2) K-ATP opener (vasodilator, preload/afterload ↓); POSITIVE INOTROPY bez ↑O₂ zużycia; Wskazanie: acute decompensated HF; D — Fałsz: ICaL: Ca²⁺ (nie K⁺); CICR: Ca²⁺-INDUCED; SERCA: Ca²⁺ DO SR (nie z SR); NCX: 3 Na⁺ : 1 Ca²⁺; PLB: HAMUJE; levosimendan: POZYTYWNA inotropy.',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },
  {
    topic_id: TOPIC, subtopic_id: S.skurcz, question_type: 'true_false',
    question_text: 'Oceń prawdziwość poniższych stwierdzeń dotyczących białek motorycznych i cytoszkieletu mięśnia:',
    options: [
      { id: 'A', text: 'BIAŁKA SARKOMERY: GŁÓWNE: miozyna II (grube filamenty, S1 = domena motoryczna, S2 = łodyga; LMM = lewy meromery; HMM = heavy meromeryosin) + aktyna (cienkie; F-aktyna 2 nici) + titin (I-band: sprężynowata, elastyczna; A-band: rigid; N2B + N2BA izofomy serca; I-165 + I-188 szkieletu) + nebulin (thin filament ruler, szkielet tylko) + nebulette (serce); REGULATORY: tropomiozyna (TM, αβ heterodimer) + troponina (TnC+TnI+TnT); α-ACTININ: krzyżuje aktynę w Z-disc; TITIN FUNCTION: (1) pasywna sprężystość (PEVK domena + immunoglobulin springs); (2) sarkomery centering; (3) mechanosensing (N2B: PKA, PKG fosforylacja → ↓stiffness; PEVK: Ca²⁺/CaM interaction → ↑stiffness); kardiomiopatie: RBM20 truncating → ↑titin PEVK-containing isoform → HCM/DCM', is_correct: true },
      { id: 'B', text: 'DYSTROFIN-ASSOCIATED PROTEIN COMPLEX (DAPC): dystrofina (427 kDa, rod-shaped) łączy wewnątrzkomórkowy cytoszkielet (F-aktyna) z ECM (przez dystroglikan-α [DG-α, glikoproteina, zewnątrz] + DG-β [transmembranowy] + sarkoglikan [α, β, γ, δ, transmembrane] + sarkospan + syntrofiny + dystrobrevin); FUNKCJA: stabilizacja błony podczas skurczów; przeniesienie siły skurczu na ECM + ochrona sarkolemy przed mikrouszkodzeniami; DMD (Duchenne): nonsense/frameshift mutacja dystrofin → brak dystrofiny → niestabilność → Ca²⁺ leak → nekroza; BMD (Becker): in-frame → skrócona ale funkcjonalna dystrofina → łagodniejsza', is_correct: true },
      { id: 'C', text: 'Nebulin jest białkiem regulującym grube filamenty miozyny; titin nie pełni funkcji sprężynowej w sarkomerze; α-aktynina łączy tropomiozynę w M-line; dystrofina łączy zewnątrzkomórkową macierz (ECM) z miozyną bezpośrednio; w chorobie Duchenne (DMD) dystrofina jest nadmiernie ekspresjonowana; DAPC (dystrophin-associated protein complex) jest zlokalizowany wyłącznie w mitochondriach mięśnia; RBM20 mutacja powoduje skrócenie (nie wydłużenie) izoformy titin', is_correct: false },
    ],
    correct_answer: ['A', 'B'],
    explanation: 'A — Prawda: ISOFORMY TITIN: serce: N2B (mały, sztywny → ↑pasywna sztywność, stałe obciążenie) + N2BA (duży, sprężysty → ↑compliance; więcej w diastolicznej dysfunkcji?); szkielet: I-165 (fast twitch) + I-188 (slow twitch); HCM: ↑stiffness; DCM: ↑compliance; TITIN CUT: RBM20 (RNA binding motif protein 20): alternatywny splicing titin; mutacja (LOF) → ↑PEVK isoform → DCM (RBM20-DCM: złośliwy, arytmie, kardiomiopatia dilated); TTN TRUNCATING: 1% populacji, ↑DCM risk 20–25%; ACTININ ISOFORMS: α-actinin-2 (serce + slow skeletal) + α-actinin-3 (fast skeletal); ACTN3 polymorphism R577X: stop codon → brak α-actinin-3 → zmniejszony szybki skurcz; atleci sprinterzy: częściej ACTN3 RR genotype; B — Prawda: DMD KLINICZNE: X-linked recessive (chr Xp21.2); chłopcy 1:3500; dystrofia (gowers sign: wstawanie z podłogi używając rąk wzdłuż nóg); ↑CK (10–100× norma); biopsia: ↓dystrofin immunostaining; dystrophin: 79 egzonów; najczęstszy frameshift: egzon 45–55; TERAPIA GENETYCZNA DMD: exon skipping (pomijanie egzonów 51): eteplirsen (AVI-4658): ASO → skip 51 → przywraca ramkę → truncated dystrofina (BMD-like); FDA-approved 2016; kasimersen (exon 45); ataluren: małocząsteczkowy → readthrough nonsense codon (nie dotyczy frameshift); C — Fałsz: nebulin: CIENKIE filamenty (aktyna); titin: MA funkcję sprężynową; α-aktynina: Z-DISC (nie M-line); dystrofina łączy aktyną z ECM (nie miozynę); DMD: BRAK dystrofiny (nie nadekspresja); DAPC: sarkolema (nie mitochondria); RBM20 LOF: ↑PEVK (WYDŁUŻENIE izoformy).',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },
  {
    topic_id: TOPIC, subtopic_id: S.skurcz, question_type: 'single',
    question_text: 'Skurcz mięśnia gładkiego różni się mechanizmem od skurczu mięśnia szkieletowego. Które stwierdzenie POPRAWNIE opisuje regulację skurczu mięśnia gładkiego w naczyniach krwionośnych?',
    options: [
      { id: 'A', text: 'REGULACJA NACZYNIOWEGO MIĘŚNIA GŁADKIEGO: (1) WAZOKONSTRYKCJA: NA (α1-AR → Gq → PLC → IP₃ → ↑Ca²⁺ z ER + DAG → PKC) + angiotensyna II (AT1R → Gq) + ET-1 (ETA → Gq) + TXA₂ (TP-R → Gq) + serotonina (5-HT₂ → Gq) + histamina (H1 → Gq); (2) WAZODYLATACJA: NO (śródbłonek → eNOS → NO → VSMCi → sGC → ↑cGMP → PKG → ↑MLCP + ↓Ca²⁺) + PGI₂ (prostacyklina, śródbłonek, COX-1 → ↑cAMP → PKA → ↑MLCP + ↓Ca²⁺) + EDHF (endothelium-derived hyperpolarizing factor: EET, H₂O₂ → K+ channel opening → hyperpolarization → ↓VGCC); śródbłonek jako parakrynny regulator napięcia naczyniowego', is_correct: true },
      { id: 'B', text: 'Wazokonstrykcja przez noradrenalinę odbywa się przez receptor β1-AR; eNOS (endothelial nitric oxide synthase) produkuje tlenek azotu (NO) w mięśniach gładkich naczyń (nie w śródbłonku); cGMP powoduje wazokonstrykcję przez aktywację PKG → ↑MLCK; TXA₂ (tromboksan A₂) powoduje wazodylatację; AT1R jest sprzężony z białkiem Gs (nie Gq); histamina wyłącznie powoduje wazodylatację (bez wazokonstrykcji)', is_correct: false },
      { id: 'C', text: 'NO jest produkowane przez iNOS w spoczynkowych warunkach naczyniowych; PGI₂ (prostacyklina) powoduje wazokonstrykcję przez ↑cAMP; śródbłonek nie uczestniczy w regulacji napięcia naczyniowego; IP₃ produkuje MLCP (myosin light chain phosphatase) w celu rozkurczu; ET-1 (endotelina-1) powoduje wazodylatację przez receptor ETA; ACh na mięśnie gładkie naczyń bezpośrednio powoduje skurcz (bez pośrednictwa śródbłonka)', is_correct: false },
      { id: 'D', text: 'eNOS jest stale aktywna bez żadnej regulacji wapniowej; RhoA/ROCK jest szlakiem wazodylatacyjnym; PDE5 (fosfodiesteraza-5) jest enzymem aktywującym cGMP (nie degradującym); nifedypina (CCB) zwiększa wazokonstrykcję przez blokowanie K⁺ kanałów; EDHF (endothelium-derived hyperpolarizing factor) powoduje hipopolaryzację (depolaryzację) VSMC; PGI₂ jest produkowana przez COX-2 wyłącznie w procesach zapalnych naczyń', is_correct: false },
    ],
    correct_answer: ['A'],
    explanation: 'ENDOTHELIUM BIOLOGY: eNOS (NOS3, konstytutywna): lokalizacja: caveolae + błona = CAV1 (kaveolina-1) hamuje eNOS; ↑Ca²⁺/CaM → aktywacja; Akt (PKB) → fosforylacja Ser1177 → ↑aktywność; shear stress (przepływ) → ↑eNOS; L-arginina → cytrulina + NO; iNOS (NOS2, indukowalna): makrofagi/fibroblasty przy zapaleniu → ↑NO (pro-inflammatory); nNOS (NOS1): neurony; NO SIGNALING: sGC (soluble guanylate cyclase) → ↑cGMP → PKG (PRKG1) → (1) ↑MLCP (MBS/MYPT1 fosforylacja → aktywacja) + (2) ↑BKCa (big conductance K+ channels) → ↑K⁺ → hyperpolarization → ↓VGCC → ↓Ca²⁺; PDE5 (fosfodiesteraza-5): degraduje cGMP → ↑cGMP przy PDE5 inhibitorach (sildenafil, tadalafil) → ↑vasodilatacja (penalna, płucna); VASC DYSFUNCTION DISEASE: ↓eNOS (diabetes, smoking, inflammation) → ↓NO → ↑vasoconstriction + ↑oxidative stress + ↑adhesion molecules + ↑platelet activation = atherosclerosis risk; ACh EFFECT: ACh → M3 na śródbłonku → Gq → ↑Ca²⁺ + eNOS → NO → VSMC relaxation (wazodilatacja); ale uszkodzony śródbłonek: ACh → bezpośrednio M3 na VSMC → konstrikcja (Gq → ↑Ca²⁺ → MLCK → skurcz); TEST DYSFUNKCJI: ACh test → przy zdrowym: dilatacja; endothelial dysfunction: paradoxical constriction.',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },
  {
    topic_id: TOPIC, subtopic_id: S.skurcz, question_type: 'multiple',
    question_text: 'Które z poniższych stwierdzeń POPRAWNIE opisują zmiany sarkomeryczne podczas skurczu mięśnia (ślizganie filamentów)? (zaznacz wszystkie prawdziwe)',
    options: [
      { id: 'A', text: 'ZMIANY PODCZAS SKURCZU: (1) SARKOMERA SKRACA SIĘ: Z-disc zbliżają się → ↓I-band (zona aktyny bez nakładki) → ↑A-band pozostaje STAŁY (długość grubych filamentów niezmieniona!) → ↓H-zone (↓aktyny w A-band nakładka: aktyna "najeżdża" na centrum) → zanikanie H-zone przy pełnym skurczu; (2) MECHANIZM: główki miozyny chwytają F-aktynę → hydrolizują ATP → "space stroke" → aktyna przesuwa się ku centrum sarkomery; każdy cykl: ~5–8 nm przemieszczenie; STAŁOŚĆ A-BAND: klasyczny dowód Huxleyów (1950s, interference microscopy) = HL theory; filamenty nie skracają się → ŚLIZGAJĄ', is_correct: true },
      { id: 'B', text: 'OPTYMALNA DŁUGOŚĆ SARKOMERY: ~2.0–2.4 μm (L0) dla mięśnia szkieletowego → maksymalne nakładanie aktyna-miozyna → ↑sił; poniżej ~1.5 μm: filamenty nakładają się + ↑titinowe napięcie + wewnętrzne opory → ↓aktywna siła; powyżej ~3.6 μm: brak nakładania (zero force) → pasywna siła (titin) dominuje; pasywna krzywa napięcie-długość: TITIN (główna) + kolagen (tylko przy długich rozciągnięciach); FUNCTIONAL CONSEQUENCES: serce operat na ~2.0–2.2 μm (poniżej L0) → zawsze "ascending limb of length-tension curve" → Frank-Starling law: ↑EDV → ↑SV (do L0); dysfunkcja: HCM (↑sarcomere protein mutations) → diastolyczna sztywność', is_correct: true },
      { id: 'C', text: 'FILAMENT LENGTHS: F-AKTYNA (cienki): ~1.0 μm (skeletal) + 1.1 μm (cardiac); MIOZYNA II (gruby): ~1.6 μm (skeletal) + 1.65 μm (cardiac); TITINA: ~1 μm (I-band) + anchors; SARKOMERA SPOCZYNKOWA: ~2.2 μm (szkielet) + ~1.9–2.2 μm (serce zależnie od napełniania); A-BAND: 1.6 μm (= długość grubych filamentów, STAŁA); I-BAND: zmienia się (= 2 × część aktyny bez nakładki); H-ZONE: środek A-band bez aktyny; linia M: środek A-band (białka: myomesin + M-protein), utrzymuje porządek grubych filamentów; linia Z: kotwica cienkich filamentów + titin N-terminus', is_correct: true },
      { id: 'D', text: 'A-band (anizotropowa, ciemna) zmienia długość podczas skurczu (skraca się jak sarkomera); I-band (izotropowa, jasna) pozostaje stała podczas skurczu; H-zone zwiększa się podczas pełnego skurczu (bo aktyna odchodzi od środka); Z-disc oddalają się od siebie podczas skurczu; M-line zawiera aktynę (nie miozynę); sarkomera wydłuża się podczas skurczu izometrycznego', is_correct: false },
    ],
    correct_answer: ['A', 'B', 'C'],
    explanation: '(A) EXPERIMENTAL EVIDENCE ŚLIZGANIA: INTERFERENCYJNY MIKROSKOP: Huxley + Hanson (1954) + Huxley + Niedergerke (1954): A-band stała przy zmianie długości mięśnia; X-RAY DIFFRACTION: zmiany perioyczności siatki przy skurczu (H.E. Huxley 1953); POJEDYNCZA CZĄSTECZKA MYOZYNY: optical trap + glass needle → single molecule mechanics → power stroke ~5 nm, ~3 pN; fluorescence visualization of actin filaments (Spudich lab); (B) PASSIVE STIFFNESS CARDIAC DISEASE: DCMRM20 → giant titin isoform (N2BA↑) → ↓passive stiffness (↑compliance) → ↑EDV (eccentric remodeling); HFpEF (diastolic): ↑passive stiffness → ↓filling → ↓SV; titin defosorylacja (↑in HF) → ↑stiffness; PKA/PKG fosorylacja PEVK + N2B → ↓stiffness; (C) BAND PATTERN I PRĄŻKOWANIE: CIEMNE BAND (A, anisotropic): dwójłomne w świetle spolaryzowanym (EM: grube filamenty + nakładka aktyny); JASNE BAND (I, isotropic): aktyna tylko; PASUJE DO NAZWY: anisotropic = ciemna = A = grube; isotropic = jasna = I = cienkie; D — Fałsz: A-band: STAŁA (filament length constant); I-band: MALEJE przy skurczu; H-zone: MALEJE lub ZANIKA; Z-disc: ZBLIŻAJĄ SIĘ; M-line: MIOZYNA (myomesin); sarkomera przy izometrycznym: STAŁA długość (lecz sarkomer shape may change locally).',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },
  {
    topic_id: TOPIC, subtopic_id: S.skurcz, question_type: 'single',
    question_text: 'Miopatia jest ogólną nazwą chorób mięśni szkieletowych. Które stwierdzenie POPRAWNIE opisuje różnicę między miopatiami pierwotnie mięśniowymi a miopatiami neuropatycznymi?',
    options: [
      { id: 'A', text: 'MIOPATIE (myopathies) vs NEUROPATIE: MIOPATIA (pierwotnie mięśniowa): uszkodzenie włókien mięśniowych → CECHY: (1) osłabienie proksymalne (pasy barkowe, biodra; "duck walk", wchodzenie po schodach, Gowers\' sign); (2) ↑CK (Creatine kinase) surowicy (zniszczenie sarkolemy → wyciek CK); (3) EMG: krótkie, małe potencjały (MUAP) + szybka rekrutacja (nhiż siła skurczu); (4) biopsia: różnokalibrowe włókna + nekroza + regeneracja (centralne jądra!) + fiber splitting; NEUROPATIA/DENERWACJA: osłabienie dystalne (stopy/ręce, "peroneal pattern") + atrofia + fascyklacje + ↑CK mniejszy + EMG: duże, wydłużone MUAP + denervation potentials (fibrilacje, sharp waves)', is_correct: true },
      { id: 'B', text: 'Miopatie charakteryzują się osłabieniem dystalnym (nie proksymalnym); CK (kinaza kreatynowa) jest prawidłowa lub obniżona w miopatiach; biopsja mięśnia w miopatii wykazuje grupowe zaniki (group atrophy) jak przy denerwacji; fascylacje są typowe dla miopatii (nie neuropatii); EMG w miopatii wykazuje duże, wydłużone potencjały MUAP (jak w neuropatii); neuropatia obwodowa powoduje proksymalne osłabienie', is_correct: false },
      { id: 'C', text: 'Osłabienie proksymalne (bark, biodra) jest typowe dla neuropatii (nie miopatii); centralne jądra w biopsji mięśnia wskazują na denerwację (nie regenerację w miopatii); ↑CK w surowicy sugeruje uszkodzenie nerwu (nie mięśnia); Gowers\' sign (używanie rąk do wstawania) jest objawem neuropatii obwodowej; EMG w miopatii wykazuje duże potencjały z ↓rekrutacją (jak przy denerwacji)', is_correct: false },
      { id: 'D', text: 'Miopatia i neuropatia mają identyczny obraz EMG i identyczne zmiany w biopsji; ↑CK surowicy jest markerem wyłącznie neuropatii (nie miopatii); osłabienie proksymalne dotyczy zarówno miopatii jak i neuropatii w równym stopniu; centralne jądra (internal nuclei) w biopsji są prawidłowym znajdowiskiem u wszystkich dorosłych; biopsia mięśnia nie ma zastosowania diagnostycznego w różnicowaniu', is_correct: false },
    ],
    correct_answer: ['A'],
    explanation: 'MIOPATYCZNE vs NEUROPATYCZNE EMG: EMG MYOPATHY: MUAP (motor unit action potential): ↓amplituda + ↓czas trwania + ↑poliphasicity; ↑rekrutacja (wiele małych MU na małą siłę); brak fibrilacji (mięsień unerwiony); DENERVATION: fibrilacje + positive sharp waves (spontaniczne aktywności denerwowanego mięśnia) + duże MUAP (reinerwacja: ↑territorium MU) + ↓rekrutacja; MIOPATIE WRODZONE: central core disease (RYR1) + multiminicore + nemaline + centronuclear → biopsia: charakterystyczne zmiany histologiczne; MYOTONIA: ↓relaksacja po skurczu; DM1 (myotonic dystrophy): DMPK gen (CTG repeat) → splicing dysregulation (CLCN1, SCN5A, INSR) → myotonia + dystrofia + kardiomiopatia + katarakt + ↓gonad; EMG: "dive bomber" discharge; INFLAMMATORY MYOPATHIES: dermatomyositis (perifascikularne zaniki + DM-skin: heliotrope rash, Gottron papules; anty-Jo-1, anty-TIF1γ, anti-MDA5) + polymyositis (CD8+ limfocytowe naciek endomysial) + IBM (inclusion body myositis: ↑wiek, finger flexors + quadriceps weakness, rimmed vacuoles + amyloid inclusions w biopsji; oporna na leczenie) + necrotizing (HMGCR, SRP autoprzeciwciała).',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },

  // ── ZMĘCZENIE MIĘŚNI (1) ─────────────────────────────────────────────────
  {
    topic_id: TOPIC, subtopic_id: S.zmeczeie, question_type: 'single',
    question_text: 'Zmęczenie mięśniowe jest wynikiem wielu mechanizmów biochemicznych. Który opis POPRAWNIE wyjaśnia centralne i obwodowe mechanizmy zmęczenia mięśni?',
    options: [
      { id: 'A', text: 'ZMĘCZENIE MIĘŚNIOWE: CENTRALNE (central fatigue): ↓napęd z OUN → ↓rekrutacja MU → ↓siła; mechanizm: ↑serotonina (5-HT, zmęczenie/sen) + ↓dopamina (motywacja) → ↑subiektywne zmęczenie; OBWODOWE: (1) deplecja substratów energetycznych: ↓glikogen mięśniowy (po ~90 min przy 70% VO₂max) → ↓glikoliza → ↓ATP; ↓fosfokreatyna (PCr, szybki zasób, pierwsze 10–30 s, Cr + Pi ↔ PCr + ATP przez kinazę kreatynową); ↓ATP → rigor-like → ↓performance; (2) PRODUKTY METABOLICZNE: Pi (fosforan nieorganiczny): ↓TnC Ca²⁺ affinity + ↓Pi release z główki → ↓power stroke prędkość; H⁺ (kwasica): ↓pH (7.4 → 6.8) → ↓TnC + ↓PFK + ↓cross-bridge cycling; (3) ↑ADP: ↓cross-bridge detachment; (4) ↑K⁺ ekstrakol.: ↓depolaryzacja sarkolemy', is_correct: true },
      { id: 'B', text: 'Kwas mlekowy (mleczan) jest główną przyczyną zmęczenia mięśni przez bezpośrednie wiązanie z miozyną; serotonina zmniejsza zmęczenie ośrodkowe (nie zwiększa); deplecja fosfokreatyny nie wpływa na produkcję ATP; Pi (fosforan nieorganiczny) stymuluje skurcz przez ↑TnC sensitivity; H⁺ (kwas) poprawia skurcz mięśni przez aktywację MLCK; zmęczenie centralne dotyczy wyłącznie mięśni oddechowych', is_correct: false },
      { id: 'C', text: 'Zmęczenie obwodowe polega na ↑Ca²⁺ z SR (nie ↓); ↑fosfokreatyna pojawia się przy zmęczeniu (nie ↓); fosforan nieorganiczny (Pi) nie ma wpływu na zmęczenie mięśni; kwasica (↓pH) aktywuje kinazę kreatynową i przywraca ATP; centralne zmęczenie jest wynikiem ↑dopaminy; ↑mleczan powoduje alkalozę metaboliczną, która sprzyja skurczom', is_correct: false },
      { id: 'D', text: 'Zmęczenie mięśniowe wynika wyłącznie z ↓glikogenu bez innych mechanizmów; H⁺ (proton) poprawia skurcz mięśni przez ↑cross-bridge cycling speed; Pi (fosforan) poprawia power stroke; serotonina jest neuroprzekaźnikiem pobudzającym rekrutację MU (nie hamującym); K⁺ wychodzący z aktywnych włókien powoduje hiperpolaryzację; zmęczenie centralne nie istnieje (wyłącznie mięśniowe)', is_correct: false },
    ],
    correct_answer: ['A'],
    explanation: 'ZMĘCZENIE SZCZEGÓŁY: MLECZAN vs H⁺: NOWOCZESNY POGLĄD: mleczan sam w sobie nie powoduje zmęczenia (może nawet chronić); H⁺ z kwasicy metabolicznej (beztlenowa glikoliza → ↑H⁺) → ↓skurcz; mleczan: szybki substrat aerobowy (Cori cycle + laktat shuttle między mięśniami + mózg); PHOSPHOCREATINE SYSTEM: Cr + ATP ↔ PCr + ADP (CK, creatine kinase); ↑PCr → buforuje ADP + szybki ATP; deplecja PCr: < 30 s sprintu; resynteza: aerobowo, 3–5 min; suplementacja kreatyny: ↑PCr → ↑peak power sprinters + ↑lean mass; CENTRAL FATIGUE MEASUREMENT: TWI (twitch interpolation technique): supramaximal electrical stimulation mid-contraction → jeśli ↑siła → mięsień nie jest maksymalnie aktywowany przez OUN; dotyczy to głównie przy długich wysiłkach; SEROTONIN-DOPAMINE HYPOTHESIS: wysiłek → ↑centralny 5-HT/DA ratio → ↑subiektywne zmęczenie; kafein: ↑DA → ↓fatigue; klomipramin (↑5-HT): ↑fatigue; OVERTRAINING SYNDROME: chroniczne ↑5-HT/↓DA → ↓performance + ↓motywacja + zaburzenia snu + ↑CK; treatment: odpoczynek, ↓intensywność; PERIPHERAL FATIGUE MECHANISMS SEQUENCE: 1–10 s: ↓PCr; 10 s–2 min: ↑Pi + ↑H⁺ (anaerobic); > 2 min aerobowe: ↓glikogen (po 60–120 min); > 30 min: ↑K⁺ extracellular (accumulation from K⁺ leaking during AP) → ↓Na⁺/K⁺-ATPase → T-tubule accumulation → ↓AP propagation.',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },

]

function post(body) {
  return new Promise((resolve, reject) => {
    const data = Buffer.from(JSON.stringify(body), 'utf8')
    const req = https.request({
      hostname: 'gzpxvfaftvkfwpvljcrk.supabase.co',
      path: '/rest/v1/questions', method: 'POST',
      headers: {
        apikey: KEY, Authorization: 'Bearer ' + KEY,
        'Content-Type': 'application/json', Prefer: 'return=minimal',
        'Content-Length': data.length,
      },
    }, res => {
      let r = ''; res.on('data', c => r += c)
      res.on('end', () => resolve({ status: res.statusCode, body: r }))
    })
    req.on('error', reject); req.write(data); req.end()
  })
}

async function main() {
  console.log(`Seeding batch 4 (${questions.length} questions)...`)
  for (const q of questions) {
    const { status, body } = await post(q)
    const ok = status === 201 || status === 204
    if (!ok) console.log('ERR', status, body.slice(0, 200))
    else console.log('OK', `[${q.question_type}]`, q.question_text.slice(0, 60).replace(/\n/g, ' '))
  }
  console.log('Done.')
}
main().catch(err => { console.error(err); process.exit(1) })
