// Seed batch 2/5 — Układ ruchu człowieka
// Kości i ich połączenia (5) + Budowa stawu (5) = 10 questions

const https = require('https')
const KEY = process.env.SUPABASE_SERVICE_ROLE_KEY || ''
const TOPIC = '42b3edde-2027-4bbb-8a90-38568031d9b0'

const S = {
  kosci:  '41d461d3-7688-475f-bd67-3c61d46b0127',
  staw:   '4b0f4c0b-7c18-48c4-9599-a7f7d619db94',
}

const questions = [

  // ── KOŚCI I ICH POŁĄCZENIA (5) ────────────────────────────────────────────
  {
    topic_id: TOPIC, subtopic_id: S.kosci, question_type: 'single',
    question_text: 'Kręgosłup człowieka jest zbudowany z kręgów i pełni wiele funkcji. Który opis POPRAWNIE charakteryzuje budowę kręgosłupa i jego krzywizny?',
    options: [
      { id: 'A', text: 'KRĘGOSŁUP: 33–34 kręgi: C1–C7 (szyjne 7) + Th1–Th12 (piersiowe 12) + L1–L5 (lędźwiowe 5) + kość krzyżowa (S1–S5, zrośnięte 5) + kość ogonowa (Co1–Co4, szczątkowe 3–4); KRZYWIZNY FIZJOLOGICZNE w płaszczyźnie strzałkowej (sagitalnej): (1) lordoza szyjna (C, wypukłość do przodu) — wtórna; (2) kifoza piersiowa (Th, wypukłość do tyłu) — pierwotna; (3) lordoza lędźwiowa (L, do przodu) — wtórna; (4) kifoza krzyżowa/ogonowa — pierwotna; "pierwotne" (płodowe) = kifotyczne; "wtórne" (nabyte przy pionizacji = lordotyczne); ATLAS (C1): bez trzonu; AXIS (C2): ząb (dens) = wyrostek zębowy; staw szczytowo-obrotnikowy: obrót głowy', is_correct: true },
      { id: 'B', text: 'Kręgosłup ludzki składa się z 12 kręgów szyjnych i 7 piersiowych; kifoza jest wygięciem do przodu a lordoza do tyłu; krzywizny kręgosłupa są wyłącznie wrodzone (nie nabywane przy pionizacji); Atlas (C1) ma wyrostek zębowy; krzywizny piersiowa i krzyżowa są wtórnymi (nabytymi); kręgosłup piersiowy ma 5 kręgów; lordoza lędźwiowa jest krzywizną pierwotną (płodową)', is_correct: false },
      { id: 'C', text: 'Kość krzyżowa składa się z 7 zrośniętych kręgów; lordoza szyjna i lędźwiowa są pierwotnymi krzywizną płodowymi; kifoza piersiowa jest wtórną krzywizną nabywaną; atlas (C1) ma wyrostek zębowy (dens); axis (C2) nie ma trzonu; kręgosłup ma 40 kręgów łącznie; staw szczytowo-obrotnikowy umożliwia głównie zgięcie głowy do przodu/tyłu', is_correct: false },
      { id: 'D', text: 'Kręgosłup szyjny ma 12 kręgów; kręg C2 (atlas) pozbawiony jest wyrostka zębowego; krzywizny kręgosłupa w płaszczyźnie czołowej (frontalnej) są fizjologiczne u wszystkich dorosłych; kifoza i lordoza rozwijają się wyłącznie u niemowląt i nie mają związku z postawą; kość ogonowa (os coccygis) jest zrośnięta z kością krzyżową i razem tworzą 1 kość', is_correct: false },
    ],
    correct_answer: ['A'],
    explanation: 'PATOLOGIE KRZYWIZN KRĘGOSŁUPA: SKOLIOZA (scoliosis): boczne wygięcie (w płaszczyźnie czołowej) + rotacja trzonów; idiopatyczna (80%, adolescent girls); AIS (adolescent idiopathic scoliosis): Cobb angle > 10°; screening: Skoliometria / Adam forward bend test; leczenie: < 25° obserwacja; 25–40° gorset (brace); > 40° op. (posterior spinal fusion + rod); KIFOZA PATOLOGICZNA: Scheuermann disease (adolescents): ↑wedging 3+ kręgów Th > 5° → kyfoza > 45°; Tb (tuberculosis kręgów): Pott disease: destrukcja kręgu (TH) → kąt kyfotyczny "gibbus"; LORDOZA LĘDŹWIOWA: ↑lordoza → przeciążenie facet joints → ból; spondyloliza: stres fraktura pars interarticularis L5 (młodzi sportowcy: gimnastyki, rzut oszczepem) → spondylolisteza (ześlizgnięcie L5 do przodu na S1); ATLAS/AXIS: atlantoaxial subluxation: reumatoidalne zapalenie stawów (RA) → uszkodzenie więzadła poprzecznego → niestabilność → ucisk rdzenia; Odontoid fracture: C2 złamanie przez ząb przy wypadku komunikacyjnym.',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },
  {
    topic_id: TOPIC, subtopic_id: S.kosci, question_type: 'multiple',
    question_text: 'Które z poniższych stwierdzeń POPRAWNIE opisują szkielet kończyny górnej i dolnej? (zaznacz wszystkie prawdziwe)',
    options: [
      { id: 'A', text: 'KOŃCZYNA GÓRNA: obręcz (łopatka + obojczyk) + ramię (kość ramieniowa, humerus) + przedramię (promień = radius po stronie kciuka; łokieć = ulna po stronie małego palca) + nadgarstek (8 kości: bliższy rząd: łódeczkowata-księżycowata-trójgraniasta-grochowata; dalszy: czworoboczna większa, czworoboczna mniejsza, główkowata, haczykowata, łac. S-L-T-P / Tm-Td-C-H) + śródręcze (I–V) + palce (paliczki: kciuk=2, pozostałe=3); HEAD HUMERI: kulisty, wiąże się z glenoid (mała panewka) → rotator cuff = SITS: supraspinatus + infraspinatus + teres minor + subscapularis', is_correct: true },
      { id: 'B', text: 'KOŃCZYNA DOLNA: obręcz (miednica: kość biodrowa ilium + łonowa pubis + kulszowa ischium) + udo (kość udowa, femur) + podudzie (kość piszczelowa tibia — środkowa/przyśrodkowa, kość strzałkowa fibula — boczna; strzałka NIE dźwiga ciężaru) + stopa: stęp (7: skokowa talus, piętowa calcaneus, łódkowata navicular, graniastosłup cuboid, III kości klinowate cuneiform I–III) + śródstopie (5 kości) + palce; staw kolanowy: kości udowa + piszczelowa + rzepka (patella)', is_correct: true },
      { id: 'C', text: 'PORÓWNANIE KOŃCZYN: kończyna górna: bardziej ruchoma, mniej obciążeniowa; kończyna dolna: obciążeniowa, stabilna; łuk stopy (plantar arch): podłużny (przyśrodkowy + boczny) + poprzeczny; amortyzacja przy chodzie; OBWÓD BIODROWY: acetabulum (kości ilium + ischium + pubis, zrastają się w 3 częściach) → głęboka panewka + labrum (fibrocartilage) + więzadło głowy kości udowej (ligamentum capitis femoris, zawiera gałąź tętnicy zasłonowej → ryzyko AVN przy złamaniu); SZYJA FEMUR: anteversion 10–15° (kąt między szyjką a osią kolana) + kąt szyjkowo-trzonowy 125–135°', is_correct: true },
      { id: 'D', text: 'Promień (radius) leży po stronie małego palca (ulnarnie); kość strzałkowa (fibula) jest główną kością nośną kończyny dolnej i dźwiga cały ciężar ciała; glenoid (panewka barkowa) jest większa i głębsza niż acetabulum (panewka biodrowa); kość piszczelowa (tibia) leży bocznie a fibula przyśrodkowo; stęp składa się z 8 kości nadgarstkopodobnych; miednica składa się wyłącznie z kości biodrowej (ilium)', is_correct: false },
    ],
    correct_answer: ['A', 'B', 'C'],
    explanation: '(A) ROTATOR CUFF KLINICZNE: supraspinatus: odwiedzenie 0–90° (ARC 60–120°: "painful arc"); najczęstsze uszkodzenie (tendinopathy + tear); test Jobe\'s; infraspinatus + teres minor: rotacja zewnętrzna; test Hornblower; subscapularis: rotacja wewnętrzna; test belly-press; SPECIAL TESTS: Neer sign (impingement — naciśnięcie na bark przy wewnętrznej rotacji); Hawkins-Kennedy; empty can; drop arm (complete supraspinatus tear); SHOULDER DISLOCATIONS: 95% przednie (anterior, subcoracoid); Bankart lesion: oderwanie labrum przednio-dolnego od glenoid; Hill-Sachs: impresyjne złamanie tylno-boczne główki kości ramiennej; leczenie: redukcja → unieruchomienie → fizyko lub artroskopowa naprawa; (B) FIBULA ROLE: stabilizacja LAS (lateral ankle sprain → ATFL, CFL); nie dźwiga (10% ciężaru vs 90% tibia); fibula fracture alone = "fibula-only fracture" → stable; TIBIA STRESS FRACTURE: biegacze (100 km/tydz+); anteromedial cortex (dreaded black line = non-union risk); posteromedial (safer, compression side); (C) ŁUK STOPY: pes planus (płaskostopie): ↓łuk przyśrodkowy → ↑pronacja → ↑ryzyko tibial stress, plantar fasciitis; pes cavus: ↑łuk → ↑lateral stress; D — Fałsz: radius = kciuk (lateral), ulna = łokieć (medial); fibula: NIE nośna; glenoid: MNIEJSZA i płytsza niż acetabulum; tibia: przyśrodkowa (medial); stęp: 7 kości (nie 8); miednica: 3 kości (ilium + pubis + ischium).',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },
  {
    topic_id: TOPIC, subtopic_id: S.kosci, question_type: 'true_false',
    question_text: 'Oceń prawdziwość poniższych stwierdzeń dotyczących czaszki człowieka i kości twarzy:',
    options: [
      { id: 'A', text: 'CZASZKA (cranium): sklepienie (calvaria): kości parzyste ciemieniowe (ossa parietalia) + kość czołowa (os frontale, parzysta u dziecka) + kość potyliczna (os occipitale); kości podstawy czaszki: czołowa + sitowa (ethmoid) + klinowa (sphenoid) + skroniowe (temporal, parzyste, zawierają: wyrostek sutkowy = mastoid, wyrostek rylcowaty = styloid, skałę petrozum z błędnikiem + ślimak + kosteczki słuchowe) + potyliczna; otwór wielki (foramen magnum) w kości potylicznej → rdzeń przedłużony; KOŚCI TWARZY: żuchwa (mandibula) — jedyna ruchoma kość czaszki; kości nosowe parzyste; szczęki parzyste (maxillae); jarzmowe (zygomatic); łzowe (lacrimal); podniebienne (palatine); małżowiny nosowe dolne (inferior nasal conchae)', is_correct: true },
      { id: 'B', text: 'SZWY CZASZKI: szew wieńcowy (coronalis): czołowa ↔ ciemieniowe; szew strzałkowy (sagittalis): między 2 ciemieniowymi; szew lambdoidalny (lambdoidalis): ciemieniowe ↔ potyliczna; szew łuskowy (squamosus): ciemieniowa ↔ skroniowa; PUNKTY KRANIOMETRYCZNE: bregma (koronalny ∩ strzałkowy); lambda (strzałkowy ∩ lambdoidalny); nasion (nos-czoło); opisthion (tylny brzeg foramen magnum); EAR OSSICLES (kosteczki słuchowe): młoteczek (malleus) + kowadełko (incus) + strzemiączko (stapes) — wszystkie w jamie bębenkowej (ucho środkowe)', is_tml: true, is_correct: true },
      { id: 'C', text: 'Żuchwa (mandibula) jest parzystą kością twarzy; kość skroniowa nie zawiera kosteczek słuchowych; czaszka dorosłego człowieka jest jednolitą kością bez szwów; kość czołowa (os frontale) jest kością podstawy czaszki (nie sklepienia); otwór wielki (foramen magnum) jest w kości klinowej (sphenoidale); szew strzałkowy łączy kości ciemieniowe z czołową; strzemiączko (stapes) jest największą kosteczką słuchową', is_correct: false },
    ],
    correct_answer: ['A', 'B'],
    explanation: 'A — Prawda: KLINIKA CZASZKI: KRANIOSYNOSTOZA (przedwczesna fuzja szwu): scaphocephaly (sagitalny → długa, wąska); brachycephaly (obu koronalnych); plagiocephaly (jednego koronalnego lub lambdoidalnego); trigonocephaly (metopical); PAGET DISEASE KOŚCI: mozaikowy wzór kości (woven + lamellar) + ↑osteoblasty + ↑osteoklasty; czaszka: ↑grubość + bawole czoło (frontal bossing); DEPRESSED SKULL FRACTURES: liniowe vs zagłębione; zagłębione: usunięcie fragmentu (ucisk mózgu); linear: obserwacja; RACOON EYES: siniak wokół oczodołu = złamanie podstawy czaszki (anterior fossae); Battle sign: siniak za uchem (mastoid) = temporal bone fracture; B — Prawda: STAPES (strzemiączko): NAJMNIEJSZA kość ciała (3 mm); zapewnia połączenie z okienkiem owalnym (fenestra ovalis) → przenosi drgania do ucha wewnętrznego; OTOSCLEROSIS: patologiczne usztywnienie stapes → przewodnieniowe ubytek słuchu; leczenie: stapedektomia + proteza; MALLEUS: przyczep do błony bębenkowej; INCUS: środkowe, łączy malleus i stapes; OSSICLES EMBRYOLOGY: malleus + incus z 1. łuku gardłowego (Meckela cartilage); stapes + styloid z 2. łuku (Reichert cartilage); C — Fałsz: mandibula: NIEPARZYSTA; kość skroniowa: ZAWIERA kosteczki; szwy: WIDOCZNE i OBECNE u dorosłych (zrastają się wolno przez całe życie); czołowa: sklepienie + częściowo podstawa; foramen magnum: potyliczna; szew strzałkowy: MIĘDZY 2 CIEMIENIOWYMI (nie z czołową; strzałkowy ∩ koronalny = bregma); stapes: NAJMNIEJSZA (nie największa).',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },
  {
    topic_id: TOPIC, subtopic_id: S.kosci, question_type: 'single',
    question_text: 'Klatka piersiowa chroni narządy klatki piersiowej i uczestniczy w oddychaniu. Który opis POPRAWNIE charakteryzuje jej budowę?',
    options: [
      { id: 'A', text: 'KLATKA PIERSIOWA (thorax): 12 par żeber + mostek (sternum) + 12 kręgów piersiowych; MOSTEK: rękojeść (manubrium) + trzon (corpus) + wyrostek mieczykowaty (processus xiphoideus); kąt Louisa (sternal angle = manubriosternal junction): poziom Th4–5 + 2. żebro + rozwidlenie tchawicy + łuk aorty; ŻEBRA: (1–7) prawdziwe (verae): połączone przez chrząstkę bezpośrednio z mostkiem; (8–10) rzekome (spuriae): przez chrząstkę do wyżej leżącej; (11–12) wolne (fluctuantes): tylko mięśniowe zakończenia; żebra mają: głowę (caput) + szyjkę (collum) + guzek (tuberculum) + trzon (corpus); kąt żebrowy (costal angle): fizjologicznie 70–75°', is_correct: true },
      { id: 'B', text: 'Klatka piersiowa składa się z 10 par żeber; żebra (1–5) to żebra prawdziwe; żebra (8–12) to żebra wolne (fluctuantes); mostek składa się z 4 części; manubrium leży na poziomie Th8; kąt Louisa odpowiada poziomowi 4. żebra (nie 2.); wyrostek mieczykowaty (xiphoid) jest zrośnięty z kręgosłupem', is_correct: false },
      { id: 'C', text: 'Kąt podżebrowy (subcostal angle) między łukami żebrowymi jest u wszystkich ludzi taki sam (90°); żebra 1–5 są żebrami rzekomymi połączonymi z mostkiem przez chrząstki; wyrostek mieczykowaty to górna część mostka; łuk aorty leży na poziomie kąta Louisa (sternal angle) odpowiadającym Th1; żebra 11 i 12 są połączone z chrząstkami żeber powyżej', is_correct: false },
      { id: 'D', text: 'Klatka piersiowa ma 14 par żeber; mostek składa się wyłącznie z rękojeści i trzonu (brak wyrostka mieczykowatego); żebra rzekome (spuriae) to żebra 1–7; kąt Louisa odpowiada poziomowi 5. przestrzeni międzyżebrowej; klatka piersiowa jest zrośnięta z łopatkami; żebra wolne (fluctuantes) to żebra 6–10', is_correct: false },
    ],
    correct_answer: ['A'],
    explanation: 'KLINICZNE KLATKI PIERSIOWEJ: ZŁAMANIA ŻEBER: ≥ 3 żebra w 2 miejscach → flail chest (klata cepowata) → paradoksalny ruch + hipowentylacja → intubacja; ból przy oddychaniu → ↓wentylacja → atelektaza → zapalenie płuc; TENSION PNEUMOTHORAX: powietrze w opłucnej → mediastinum przesuwa w przeciwna stronę → ucisk SVC + serca → ↓CO → śmierć; leczenie: natychmiastowa igłowa dekompresja 2. mRŻ, MCL → potem dren; HEMOTHORAX: krew w opłucnej → dren 5. mRŻ, MAL; STERNAL ANGLE (KĄT LOUISA) MARKERY KLINICZNE: poziom Th4/5; 2. żebro (identyfikacja przestrzeni międzyżebrowych przy osłuchiwaniu); rozwidlenie tchawicy (carina); łuk aorty (aortic knuckle na CXR); żyła główna górna (SVC) — zaczyna się; prawa gałąź tętnicy płucnej; przewód limfatyczny piersiowy — krzyżuje; EXSANGUINATION: osierdziowe złamanie mostka → stłuczenie serca → arytmia; PECTUS EXCAVATUM: lejkowata klatka → ucisk serca/płuc → ↓VO₂max; leczenie: bar Nuss (minimally invasive); PECTUS CARINATUM: kurza klatka; zwykle kosmetyczny; WAGA KĄTA PODŻEBROWEGO: szeroki kąt (> 90°) → typ empiryczny; wąski (< 90°) → typ asteniczny; różni się konstytucjonalnie.',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },
  {
    topic_id: TOPIC, subtopic_id: S.kosci, question_type: 'multiple',
    question_text: 'Które z poniższych stwierdzeń POPRAWNIE opisują miednicę i jej znaczenie kliniczne? (zaznacz wszystkie prawdziwe)',
    options: [
      { id: 'A', text: 'MIEDNICA (pelvis): kości miednicy = 2 × os coxae (kość biodrowa ilium + kość łonowa pubis + kość kulszowa ischium; zrastają się w panewkę [acetabulum] ok. 15–17 lat) + kość krzyżowa (sacrum) + kość ogonowa (coccyx); POŁĄCZENIA: staw krzyżowo-biodrowy (sacroiliac joint, SI joint): synchondrosis z elementem synovial (semi-diarthrosis); spojenie łonowe (symphysis pubica): fibrocartilage; PODZIAŁ MIEDNICY: granica: linia graniczna (linea terminalis/innominata) = linea arcuata (biodrowa) + pecten ossis pubis + górny brzeg spojenia łonowego; miednica wielka (pelvic major, false) powyżej; miednica mała (pelvic minor, true) poniżej', is_correct: true },
      { id: 'B', text: 'RÓŻNICE PŁCIOWE MIEDNICY: KOBIECA: kąt podłonowy > 90° (100°) + okrągłe/owalne wejście do miednicy małej + większy wymiar poprzeczny + płytka + szeroka + stercząca kolec kulszowy mało + kość ogonowa elastyczna (ku tyłowi) → PORÓD; MĘSKA: kąt < 90° (70°) + wejście sercowate + głęboka + wąska + wystające kolce kulszowe + sacrum dłuższe i bardziej zakrzywione; KLINICZNE: wymiary rodności: sprzężna anatomiczna (konjugata vera), skośne (oblique), poprzeczna; dystocia: ↓wymiary + makrosomia płodu', is_correct: true },
      { id: 'C', text: 'ZŁAMANIA MIEDNICY: niestabilne (Tile B/C, Young-Burgess): rozejście SI joint lub symphysis pubis + złamania gałęzi kości łonowych → masywne krwawienie (arteria iliaca interna, żyły miednicy); leczenie: stabilizacja zewnętrzna (klama miednicy = pelvic binder → ↓objętość) → angiografia z embolizacją lub preperitoneal packing; ACETABULAR FRACTURES: po wypadkach → proteza biokrzyżowa lub ORIF; INSUFFICIENCY FRACTURES: u starszych (OP) → pęknięcia gałęzi łonowych przy zwykłych ruchach', is_correct: true },
      { id: 'D', text: 'Miednica składa się wyłącznie z dwóch kości (os coxae); staw krzyżowo-biodrowy (SI joint) jest wyłącznie stawem maziowym bez elementów fibrochondralnych; w miednicy kobiecej kąt podłonowy wynosi < 70° (węższy niż u mężczyzny); linia graniczna (linea terminalis) oddziela miednicę małą od jamy brzusznej (nie od miednicy wielkiej); panewka (acetabulum) zbudowana jest wyłącznie z kości biodrowej (ilium); spojenie łonowe to staw maziowy z jamą stawową', is_correct: false },
    ],
    correct_answer: ['A', 'B', 'C'],
    explanation: '(A) OS COXAE EMBRYOLOGIA: trzy ośrodki kostnienia (ilium, ischium, pubis) → fuzja w panewce (Y-cartilage = triradiate cartilage) → zamknięcie ~15–17 lat; TRENDELENBURG SIGN: słaby mięsień odwodziciel (gluteus medius) → opada miednica po stronie uniesionej nogi → kompensacja: tułów przechyla się ku choremu biodru; PIRIFORMIS SYNDROME: piriformis → ucisk na nerw kulszowy (sciatic) wychodzący przez otwór kulszowy większy; kopiuje rwę kulszową; (B) WYMIARY RODNOŚCI: AP: konjugata anatomica (od szczytu wzgórka krzyżowego do górnego brzegu spojenia: 11 cm); konjugata diagonalis (od szczytu wzgórka do dolnego brzegu spojenia: 12.5 cm); konjugata vera (sprzężna prawdziwa: AP wejście = 11 cm); ograniczone: ↓operacyjne (≤ 10 cm); (C) OPEN BOOK INJURY: zewnętrzny uraz rotacyjny → rozejście symphysis + SI joint → "otwarta książka" → krwawienie → zagrożenie życia; (D) Fałsz: miednica: 4 kości (2 × os coxae + sacrum + coccyx); SI joint: hybrydowy (synchondrosis z małym wysiłkiem maziowym); kobieca: kąt > 90°; linea terminalis: między miednicą wielką a małą (nie jamą brzuszną); acetabulum: 3 kości (ilium + ischium + pubis); symphysis pubica: FIBROCARTILAGE (nie maziowy).',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },

  // ── BUDOWA STAWU (5) ──────────────────────────────────────────────────────
  {
    topic_id: TOPIC, subtopic_id: S.staw, question_type: 'single',
    question_text: 'Staw maziowy (diarthrosis) jest najczęstszym typem stawu w organizmie człowieka. Który opis POPRAWNIE wymienia elementy obowiązkowe i dodatkowe stawu maziowego?',
    options: [
      { id: 'A', text: 'STAW MAZIOWY — ELEMENTY OBOWIĄZKOWE: (1) POWIERZCHNIE STAWOWE: pokryte chrząstką szklistą stawową (articular cartilage, brak periosteum i naczyń); (2) TOREBKA STAWOWA (capsula articularis): zewnętrzna warstwa włóknista (fibrous layer = błona włóknista, kolagen I + kolagen III → mocna) + wewnętrzna warstwa maziowa (błona maziowa = synovium: komórki type A [makrofagi-like] + type B [fibroblasty-like] → maź stawowa); (3) JAMA STAWOWA (cavum articulare): szczelina wypełniona mazią; ELEMENTY DODATKOWE: więzadła (ligaments) — zewnętrzne lub wewnątrzkapsularne; obrąbki (labra): fibrocartilage; łąkotki (menisci); kaletki maziowe (bursae); tarczki stawowe (disci); trzeszczki (sesamoidea); fałdy maziowe (plica)', is_correct: true },
      { id: 'B', text: 'Staw maziowy obligatoryjnie musi mieć łąkotki i kaletki; jama stawowa wypełniona jest krwią (nie mazią); błona maziowa produkuje kolagen I; komórki type A błony maziowej to fibroblasty syntezujące kwas hialuronowy; chrząstka stawowa jest bogato unaczyniona i unerwiona; torebka stawowa nie ma warstwy włóknistej; więzadła stawowe są zawsze zewnątrzkapsularne', is_correct: false },
      { id: 'C', text: 'Obowiązkowe elementy stawu maziowego to łąkotki + kaletki + obrąbki; jama stawowa jest elementem dodatkowym (fakultatywnym); błona maziowa (synovium) wytwarza maź przez specjalne gruczoły z przewodem wyprowadzającym; chrząstka stawowa zawiera perichondrium; komórki B błony maziowej to komórki układu odpornościowego (B-limfocyty); połączenia fibrocartilaginous (symphysis) mają jamę stawową', is_correct: false },
      { id: 'D', text: 'Elementy obowiązkowe stawu maziowego to kość + szpik kostny + chrząstka + naczynia; błona maziowa wytwarza hemoglobinę i tlen dla chrząstki; jama stawowa jest wypełniona płynem wewnątrzkomórkowym bogatym w Na⁺; więzadła zewnętrzne (extracapsular) nie stabilizują stawu; chrząstka szklistą stawową jest syntetyzowana przez synoviocyty type B; obrąbki (labra) to blaszki kostne zwiększające powierzchnię stawu', is_correct: false },
    ],
    correct_answer: ['A'],
    explanation: 'MAŹ STAWOWA (SYNOVIAL FLUID): skład: dializat osocza + kwas hialuronowy (HA, syntetyzowany przez type B synoviocyty) + lubricina (proteoglycin 4, PRG4, produkowana przez chondrocyty powierzchniowe: lubrikacja; mutacja → camptodactyly-arthropathy); normalnie: 0.1–4 ml; żółta, klarowna, lepka (HA → tiksotropia: lepkość ↓przy ruchu); ANALIZA MAZI: non-inflammatory: < 2000 WBC (OA); inflammatory: 2000–50000 (RA, pseudogout, gout, SpA); septic: > 50000 (bakteryjne zapalenie); kryształy: moczanowe (urate, negatywna birefringence, gout) vs CPPD (calcium pyrophosphate, positive, pseudogout); LABRA: PANEWKOWY OBRĄBEK (acetabular labrum): ↑głębokość + ↑stabilność + ↑negatywne ciśnienie; uszkodzenie (labral tear) → ból biodra + clicking → diagnoza MR arthrografii; GLENOID LABRUM (bark): Bankart lesion (anterior inferior); SLAP (superior labrum anterior-posterior) tear: u miotaczy; PLC (plicae) KOLANA: fałdy maziowe; plica syndrome: zapalenie fałdu przyśrodkowego → ból przednio-przyśrodkowy kolana; leczenie: fizyko → artroskopowe usunięcie.',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },
  {
    topic_id: TOPIC, subtopic_id: S.staw, question_type: 'true_false',
    question_text: 'Oceń prawdziwość poniższych stwierdzeń dotyczących stanu stawu kolanowego i jego struktur:',
    options: [
      { id: 'A', text: 'STAW KOLANOWY (art. genus): największy i najbardziej złożony staw człowieka; kości: femur + tibia + patella (fibula NIE wchodzi w skład stawu kolanowego); ELEMENTY: (1) ŁĄKOTKI (menisci): przyśrodkowa (C-kształt, szersza, mniej ruchoma = częściej uszkadzana) + boczna (okrągła, bardziej ruchoma); fibrocartilage; funkcja: amortyzacja + stabilizacja + dystrybucja obciążenia + lubrikacja; unaczynienie: 2/3 zewnętrzne (czerwona strefa) → goi się; 1/3 wewnętrzne (biała strefa) → nie goi się; (2) WIĘZADŁA KRZYŻOWE: ACL (anterior cruciate): tibia → femur (tylno-boczny); zapobiega przedniemu ześlizgnięciu podudzia; ATF test (Lachman, anterior drawer); PCL (posterior): silniejsze', is_correct: true },
      { id: 'B', text: 'WIĘZADŁA POBOCZNE I TOREBKA KOLANA: MCL (medial collateral ligament): stabilizuje przed valgus (koślawość); uszkodz przy urazie koślawym (valgus force); LCL (lateral collateral ligament): varus; leczenie: MCL I–II → zachowawcze; III → operacyjne; LCL III → operacyjne; "UNHAPPY TRIAD" (O\'Donoghue): jednoczesne uszkodzenie ACL + MCL + łąkotki przyśrodkowej; typowy uraz: nagłe zatrzymanie + obrót (piłka nożna, narty); RZEPKA (PATELLA): sesamoid w ścięgnie mięśnia czworogłowego; rowek rzepkowy (trochlea femoral) → ślizganie; rzepkowo-udowy ból (PFPS = patellofemoral pain syndrome): najczęstsza przyczyna bólu kolana u młodych; objawy: ból przednio-przyśrodkowy przy schodach/klęczeniu', is_correct: true },
      { id: 'C', text: 'Fibula (kość strzałkowa) wchodzi w skład stawu kolanowego; łąkotka przyśrodkowa jest bardziej ruchoma niż boczna i rzadziej się uszkadza; ACL (więzadło krzyżowe przednie) zapobiega tylnemu ześlizgnięciu piszczeli względem kości udowej; "unhappy triad" obejmuje uszkodzenie ACL + LCL + łąkotka boczna; PCL jest słabszym więzadłem niż ACL; MCL stabilizuje staw przed siłami szpotawymi (varus force)', is_correct: false },
    ],
    correct_answer: ['A', 'B'],
    explanation: 'A — Prawda: ACL ANATOMIA: 2 pasma: anteromedial (AM, napięte w zgięciu) + posterolateral (PL, napięte w wyproście); PIVOT SHIFT TEST: przy ucisku bocznym + wewnętrznej rotacji + wyproście → podudzie "skacze" do przodu → patognomoniczne ACL; ACL REKONSTRUKCJA: przeszczep: BTB (bone-tendon-bone = środkowa 1/3 ligamentum patellae, złoty standard), hamstring (gracilis + semitendinosus), allograft (cadaver); fixacja: titanian kaniulowanych śrub lub interferensyjnych; powrót do sportu: 6–9 mies.; B — Prawda: RZEPKA KLINICZNE: LUXACJA RZEPKI: boczna (90%); lateral patella dislocation; czynniki ryzyka: duże Q-kąt (u kobiet), TT-TG > 20 mm, shallow trochlea (trochlear dysplasia); testy: lateral pull test + apprehension sign; leczenie: nastawienie + bracing → artroskopowe MPFL reconstruction (medial patellofemoral ligament); Q-ANGLE: kąt między wektor QF a oś rzepka-tuberkulet tibii; normalny: kobiety 15–20°, mężczyźni 10–15°; JUMPER\'S KNEE: tendinopatia więzadła rzepki (tendinosis); u skoczków i piłkarzy; bóle poniżej rzepki; USG: hypooechoic focus w ścięgnie; leczenie: ćwiczenia ekscentryczne; C — Fałsz: fibula: nie wchodzi w staw kolanowy (staw piszczelowo-strzałkowy proksymalny jest osobnym); przyśrodkowa: mniej ruchoma → częściej uszkadzana; ACL: PRZEDNIEGO ześlizgnięcia; unhappy triad: przyśrodkowa (nie boczna) łąkotka; PCL: SILNIEJSZY; MCL: VALGUS (koślawość).',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },
  {
    topic_id: TOPIC, subtopic_id: S.staw, question_type: 'multiple',
    question_text: 'Które z poniższych stwierdzeń POPRAWNIE opisują staw biodrowy i mechanizmy jego uszkodzeń? (zaznacz wszystkie prawdziwe)',
    options: [
      { id: 'A', text: 'STAW BIODROWY (art. coxae): kulisty + panewkowy (spheroideus); kości: głowa kości udowej (caput femoris) + panewka (acetabulum z labrum); STABILIZACJA: (1) głęboka panewka + labrum (↑kontakt + ↑ciśnienie ujemne); (2) więzadła: iliofemoral (Y-ligament Bigelowa, najsilniejsze w ciele!) + pubofemoral + ischiofemoral; (3) mięśnie: gluteus medius/minimus (odwodziciel, stabilizator miednicy), rotatory zewnętrzne (piriformis, obturator, gemelli, quadratus femoris), iliopsoas (zginacz); RUCH: zgięcie (120°) + wyprost (20°) + abdukcja (45°) + adddukcja (30°) + rotacja wew./zew. (45°)', is_correct: true },
      { id: 'B', text: 'ZŁAMANIE SZYJKI KOŚCI UDOWEJ (femoral neck fracture): u starszych kobiet (OP) + złamania niskoenergetyczne lub urazy; klasyfikacja Garden: I (niezupełne) → IV (pełne przemieszczenie); RYZYKO AVN (aseptic/avascular necrosis, jałowa martwica głowy kości udowej): przerwanie naczyń (tętnica okalająca boczna + przyśrodkowa) → ↓ukrwienie → martwica → zapaść głowy; Garden III–IV → wysoka AVN risk → endoproteza (hemiarthroplasty lub THA = total hip arthroplasty); Garden I–II + < 65 lat → ORIF (osteosynteza śruby); AVASCULAR NECROSIS (pozatraumatyczna): kortykosteroidy (↑lipidy → naczynia) + alkohol + SCD (sickle cell) + kesonowa choroba + Gaucher + HIV', is_correct: true },
      { id: 'C', text: 'FAI (FEMOROACETABULAR IMPINGEMENT): (1) Cam type: niekulista deformacja głowy/szyjki (brak offset) → podczas zgięcia wciska się w labrum/chrząstkę; (2) Pincer type: przerosnięta panewka (overcoverage) → ucisk brzegiem panewki na głowę podczas ruchu; (3) Mixed: oba; objawy: ból w pachwinie/przy długim siedzeniu/przy zgięciu; testy: FADIR (Flexion-Adduction-Internal Rotation) → ból; MRA (MR arthrografia): labral tear; leczenie: artroskopowa osteoplastyka (cam-resection) + naprawa labrum', is_correct: true },
      { id: 'D', text: 'Więzadło biodrowo-udowe (iliofemoral, Y-ligament) jest najsłabszym więzadłem w ciele; panewka jest zbudowana wyłącznie z kości łonowej (pubis); AVN (jałowa martwica) po złamaniu szyjki wynika z uszkodzenia tętnicy krzyżowej; FADIR test jest ujemny przy FAI; staw biodrowy jest stawem zawiasowym (1 oś); złamanie szyjki kości udowej Garden I zawsze wymaga endoprotezy', is_correct: false },
    ],
    correct_answer: ['A', 'B', 'C'],
    explanation: '(A) ILIOPSOAS (ZGINACZ BIODRA): iliopsoas = iliacus (kość biodrowa) + psoas major (L1–L5 kręgosłup); ścięgno przyczepione do krętarza mniejszego (lesser trochanter); palpacja w pachwinie; ILIOTIBIAL BAND (IT band): pasmo powięziowe (gluteus maximus + TFL) → biegnie po boku uda → guzek Gerdy (tibia); IT BAND SYNDROME: u biegaczy → tarcie o boczny nadkłykieć kości udowej → ból boczny kolana; (B) OSTEOTOMIE MIEDNICY (PELVIC OSTEOTOMIES): dysplazja panewki (shallow acetabulum, shallow coverage) → ↑ryzyko OA; leczenie u młodych: PAO (periacetabular osteotomy) = obracanie panewki ku przedniowi-bocznej → ↑coverage; (C) LABRAL PATHOLOGY: labral tears: w 90% u FAI; klasyfikacja: Czerny/Lage; MRA: gold standard; artroskopia: debrydement vs naprawa (re-attachment suture anchors); reinsertion → lepsze długoterminowe wyniki vs debrydement; (D) Fałsz: Y-ligament: NAJSILNIEJSZE (nie najsłabsze); acetabulum: 3 kości (ilium 2/5 + ischium 2/5 + pubis 1/5 = Y-chrząstka środek); AVN: ↓naczynia okalające (circumflex); FADIR: POZYTYWNY (ból) przy FAI; staw biodrowy: KULISTY (3 osie); Garden I: ORIF (nie endoproteza, przy niskim ryzyku AVN).',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },
  {
    topic_id: TOPIC, subtopic_id: S.staw, question_type: 'single',
    question_text: 'Zwyrodnienie stawów (choroba zwyrodnieniowa, osteoarthritis, OA) jest najczęstszą chorobą stawów. Który opis POPRAWNIE wyjaśnia jej patofizjologię?',
    options: [
      { id: 'A', text: 'OSTEOARTHRITIS PATOFIZJOLOGIA: pierwotna utrata chrząstki stawowej → reakcja kości podchrzęstnej; MECHANIZM: (1) ↓proteoglikany (aggrekan): ↓GAG → ↓hydratacja → ↓sprężystość; (2) ↑MMP (kolagenazy: MMP-1, -8, -13; aggrekanazy: ADAMTS-4,-5) z chondrocytów i synoviocytów → degradacja; (3) ↑IL-1β + TNF-α → ↑MMP + ↑COX-2 → ↑PGE2 → zapalenie + ↑VEGF → angiogeneza kości podchrzęstnej; (4) ↓IGF-1, TGF-β (naprawcze) → ↓synteza kolagenu; ANATOMIA OA: fibrylacja (fibrillation) → uwłóknnienie → szczeliny (fissure) → erozja do kości podchrzęstnej → cysty + osteofity (wyrośla kostne przy krawędziach) + ↑sklerotyzacja kości podchrzęstnej; RTG: zwężenie szpary stawowej + osteofity + skleroza + torbiele', is_correct: true },
      { id: 'B', text: 'OA jest chorobą autoimmunologiczną wywoływaną przez autoprzeciwciała przeciwko kolagenowi II; główną komórką odpowiedzialną za degradację chrząstki jest osteoklast; ADAMTS-4 i -5 to enzymy syntetyzujące aggrekan (nie degradujące); IL-1β w OA hamuje syntezę MMP; RTG w OA wykazuje ↑szerokość szpary stawowej (nie zwężenie); osteofity są złośliwymi guzami kostnymi; kości podchrzęstne cysty to wynik infekcji bakteryjnych', is_correct: false },
      { id: 'C', text: 'OA jest identyczna z reumatoidalnym zapaleniem stawów (RA) pod względem patofizjologicznym; chrząstka stawowa w OA regeneruje się samoczynnie dzięki komórkom macierzystym synoviocytom; proteoglikany w OA wzrastają (nie maleją); osteofity zapobiegają progresji OA i są reakcją ochronną bez objawów klinicznych; IL-1β hamuje zapalenie w OA; MRI nie jest przydatne w rozpoznaniu OA (OA widoczne tylko na RTG)', is_correct: false },
      { id: 'D', text: 'OA dotyczy wyłącznie stawów rąk; chrząstka w OA traci wodę i staje się bardziej sprężysta (nie mniej); ADAMTS-4 i -5 są inhibitorami degradacji chrząstki; osteofity w OA nigdy nie pojawiają się na krawędziach stawu; RF (czynnik reumatoidalny) jest zawsze obecny w OA (jak w RA); fizjoterapia i kontrola masy ciała nie mają wpływu na progresję OA', is_correct: false },
    ],
    correct_answer: ['A'],
    explanation: 'OA KLINICZNE: LOKALIZACJA: kolano (gonarthrosis), biodro (coxarthrosis), kręgosłup (spondylarthrosis), ręka (DIP: Heberden nodes, PIP: Bouchard nodes; CMC kciuka: rhizarthrosis); OBJAWY: ból przy ruchu (nie w spoczynku jak RA), poranna sztywność < 30 min, trzeszczenie (krepitus), ↓zakres ruchu; LECZENIE: NIEOPERACYJNE: ↓masa ciała (1 kg ↓ → 4 kg ↓ siły na kolano), ćwiczenia aerobowe + siłowe, fizjoterapia, NSAID (topical > systemowe ze względu na GI), paracetamol, iniekcje kortykosteroidy (krótkoterminowe), PRP (platelet-rich plasma, kontrowersyjne), wiscoosupplementacja (kwas hialuronowy, kontrowersyjne); OPERACYJNE: artroskopiczne debrydement (nie zmienia progresji!), osteotomia korygująca (młodzi z osią), TKA/THA (totalna endoproteza); BIOMARKERY: hsCRP (lekki ↑), CTX-II (C-telopeptyd kolagenu II z moczu), COMP (cartilage oligomeric protein), YKL-40; PROGNOZA OA: ↑BMI, ↓aktywność, koślawość/szpotawość, wcześniejszy uraz, dysplazja → szybsza progresja.',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },
  {
    topic_id: TOPIC, subtopic_id: S.staw, question_type: 'true_false',
    question_text: 'Oceń prawdziwość poniższych stwierdzeń dotyczących reumatoidalnego zapalenia stawów (RA) i jego odróżnienia od osteoarthritis (OA):',
    options: [
      { id: 'A', text: 'RA: choroba autoimmunologiczna; autoprzeciwciała: RF (czynnik reumatoidalny, IgM anty-IgG Fc) + anty-CCP (anty-cykliczne cytrulinowane peptydy, bardziej specyficzne); PATOFIZJOLOGIA: aktywowane CD4+ Th → ↑TNF-α + IL-1β + IL-6 + IL-17 → synoviocyty type A (makrofagi) → ↑MMP → pannus (agresywna tkanka maziowa) → erozja chrząstki + kości = uszkodzenie stawu; STAWY: SYMETRYCZNE MCP + PIP rąk/nadgarstki/stopy (MTP); oszczędza DIP; "morning stiffness" > 1 h; LECZENIE: metotreksat (MTX, anchor drug) + HCQ/SSZ; biologiczne: anty-TNF (adalimumab, etanercept) + abatacept (CTLA4-Ig) + tocilizumab (anty-IL-6R) + rituximab (anty-CD20); JAK inhibitory: tofacytynib, baricitynib', is_correct: true },
      { id: 'B', text: 'RÓŻNICOWANIE OA vs RA: OA: > 50 lat, mechaniczny ból (przy ruchu), sztywność < 30 min rano, nie symetryczne (lub asymetryczne), DIP + PIP + CMC; badania: RTG (zwężenie + osteofity), CRP normalny/lekko ↑, RF ujemny; RA: 30–50 lat (kobiety > mężczyźni 3:1), zapalny ból (w spoczynku, noc), sztywność > 60 min rano, symetryczne MCP + PIP, badania: ↑ESR + CRP + RF/anty-CCP, RTG: erosje + osteopenia (nie osteofity), USG: power Doppler synovitis; RA: SYSTEMOWE: guzki reumatoidalne (podskórne) + Rheumatoid lung + serositis + vasculitis + anemia of chronic disease', is_correct: true },
      { id: 'C', text: 'RA i OA są tą samą chorobą (różnią się tylko stadium); w RA stawy DIP są najczęściej zajętymi; RF (czynnik reumatoidalny) jest specyficzny wyłącznie dla RA i nie pojawia się w innych chorobach; OA powoduje symetryczne zapalenie MCP obustronnie; metotreksat (MTX) jest stosowany jako leczenie z wyboru w OA; anty-CCP jest markerem potwierdzającym OA', is_correct: false },
    ],
    correct_answer: ['A', 'B'],
    explanation: 'A — Prawda: PANNUS: łacina "szmata/płachta"; tkanka maziowa w RA: ↑fibroblasty + ↑makrofagi + ↑neovascularyzacja → nachodzi na chrząstkę + kość → ↑MMP (MMP-1,-3) + ↑katepsyna K → erozje; ANTI-CCP vs RF: anty-CCP: czułość 67%, swoistość 98% (vs RF: 69%/85%); anty-CCP może wyprzedzać RA o lata (preclinical RA); citrullination: PAD4 (peptidylarginine deiminase 4) → Arg → citrullina; NETosis (neutrophil extracellular traps) → citrullinowane peptydy → anty-CCP; ZMIANY POZASTAWOWE RA: guzki (najczęstsze, MCP, łokieć, ucisk: histologicznie = palissading granuloma z włóknikowym centrum); ILD (interstitial lung disease, UIP pattern); pericarditis, pleuritis; amyloidoza AA; vasculitis (palce, mononeuritis multiplex); FELTY: RA + neutropenia + splenomegalia; B — Prawda: LECZENIE RA — TREAT-TO-TARGET (T2T): cel: remisja (DAS28 < 2.6) lub low disease activity (DAS28 < 3.2); jeśli cel nie osiągnięty w 3 mies.: zmiana leku; MTX 15-25 mg/tydz + kwas foliowy; efekty uboczne MTX: hepatotoksyczność, cytopenienie, pneumonitis; biologiki biologiczne: anty-TNF (pierwszy wybór po MTX failure); ochronna: szczepienia (pneumokoki, grypa, VZV PRZED biologikami); C — Fałsz: OA i RA: różne choroby; DIP: zajęte w OA (Heberden nodes), oszczędzane w RA; RF: niespecyficzny (5-10% zdrowych, SS, SLE, hep C); OA: NIE symetryczna MCP; MTX: w RA (nie OA); anty-CCP: RA (nie OA).',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },

]

function post(body) {
  return new Promise((resolve, reject) => {
    const data = Buffer.from(JSON.stringify(body), 'utf8')
    const req = https.request({
      hostname: 'gzpxvfaftvkfwpvljcrk.supabase.co',
      path: '/rest/v1/questions', method: 'POST',
      headers: {
        apikey: KEY, Authorization: 'Bearer ' + KEY,
        'Content-Type': 'application/json', Prefer: 'return=minimal',
        'Content-Length': data.length,
      },
    }, res => {
      let r = ''; res.on('data', c => r += c)
      res.on('end', () => resolve({ status: res.statusCode, body: r }))
    })
    req.on('error', reject); req.write(data); req.end()
  })
}

async function main() {
  console.log(`Seeding batch 2 (${questions.length} questions)...`)
  for (const q of questions) {
    const { status, body } = await post(q)
    const ok = status === 201 || status === 204
    if (!ok) console.log('ERR', status, body.slice(0, 200))
    else console.log('OK', `[${q.question_type}]`, q.question_text.slice(0, 60).replace(/\n/g, ' '))
  }
  console.log('Done.')
}
main().catch(err => { console.error(err); process.exit(1) })
