// Seed batch 1/5 — Układ ruchu człowieka
// Tkanka kostna (8) + Kości i ich połączenia (2) = 10 questions

const https = require('https')
const KEY = process.env.SUPABASE_SERVICE_ROLE_KEY || ''
const TOPIC = '42b3edde-2027-4bbb-8a90-38568031d9b0'

const S = {
  kostna:  '81b1ff0e-35ce-4ab3-9442-cbe175a409e2',
  kosci:   '41d461d3-7688-475f-bd67-3c61d46b0127',
}

const questions = [

  // ── TKANKA KOSTNA (8) ─────────────────────────────────────────────────────
  {
    topic_id: TOPIC, subtopic_id: S.kostna, question_type: 'single',
    question_text: 'Tkanka kostna jest wyspecjalizowaną tkanką łączną. Który opis POPRAWNIE charakteryzuje skład i strukturę macierzy kostnej?',
    options: [
      { id: 'A', text: 'Macierz kostna składa się z (1) CZĘŚĆ ORGANICZNA (35%): kolagen typu I (~90% org.) → osteoid (niezwapniała macierz), proteoglikany (chondroitynian, dermantan siarczanu, osteokalcyna, osteopontyna, osteonektyna, sialoprotein kostna); (2) CZĘŚĆ NIEORGANICZNA (65%): hydroksyapatyt [Ca₁₀(PO₄)₆(OH)₂] (~70% suchej masy) + węglany + cytryniany + fluor + magnez; hydroksyapatyt krysztalizuje na włóknach kolagenowych → wytrzymałość na ściskanie + sprężystość kolagenu = kompromis twardość–elastyczność', is_correct: true },
      { id: 'B', text: 'Macierz kostna składa się głównie z kolagenu typu II (jak chrząstka szklista); część nieorganiczna to wyłącznie wapień (CaCO₃) bez fosforanów; hydroksyapatyt jest produkowany przez chondrocyty; proteoglikany nie są składnikiem macierzy kostnej; część organiczna stanowi 90% masy suchej kości; osteokalcyna jest białkiem mięśniowym', is_correct: false },
      { id: 'C', text: 'Kość składa się wyłącznie z wody i wapnia; kolagen typu IV tworzy sieć macierzy kostnej; hydroksyapatyt jest substancją amorficzną (niekrystaliczną); osteoid to zwapniała macierz kostna; część nieorganiczna stanowi 10% masy suchej kości; białka niekolagenowe macierzy (osteokalcyna, osteopontyna) nie pełnią żadnej funkcji biologicznej', is_correct: false },
      { id: 'D', text: 'Macierz kostna nie zawiera kolagenu; część organiczna kości to wyłącznie sole wapnia; hydroksyapatyt tworzy kryształy wyłącznie w przestrzeniach szpikowych; skład mineralny kości jest identyczny ze szkliwem zębowym (100% HAP); osteopontyna i osteokalcyna są hormonami wydzielanymi do krwi przez komórki kostne', is_correct: false },
    ],
    correct_answer: ['A'],
    explanation: 'BIAŁKA NIEKOLAGENOWE MACIERZY KOSTNEJ: OSTEOKALCYNA (OC, BGP): zależna od witaminy K (γ-karboksylacja Glu) → wiąże hydroksyapatyt; marker resorpcji kości w surowicy (uwalniana przy osteoklazie); efekt hormonalny: ↑insulina (przez GPRC6A) + ↑testosteron + ↑energia (metabolizm glukozowy); OSTEOPONTYNA (OPN): fosfoproteina; wiąże osteoblasty + osteoklasty do macierzy (integrin RGD); sygnał remodelingowy; OSTEONEKTYNA (SPARC): wiąże kolagen + HAP + komórki; inicjuje mineralizację; SIALOPROTEIN KOSTNA (BSP): RGD-motyw → integryna αvβ3 na osteoklastach; nukleuje hydroksyapatyt; KOMPROMIS MECHANICZNY: kolagen (elastyczność) + HAP (twardość) → kość jest ok. 3-5× mocniejsza na ściskanie niż beton przy znacznie mniejszej masie; starzenie → ↑crosslinks kolagenu + ↑krystaliczność HAP → bardziej krucha; osteomalacja: ↑osteoid (↓mineralizacja) → giętka; OA (osteoporoza): ↓ilość kości ale normalna mineralizacja; WITAMINA K i KOŚĆ: warfaryna → ↓γ-karboksylacja OC → ↓OC aktywność → ↑ryzyko złamania (u pacjentów na long-term warfaryna).',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },
  {
    topic_id: TOPIC, subtopic_id: S.kostna, question_type: 'multiple',
    question_text: 'Które z poniższych stwierdzeń POPRAWNIE opisują komórki tkanki kostnej i ich funkcje? (zaznacz wszystkie prawdziwe)',
    options: [
      { id: 'A', text: 'OSTEOBLASTY: komórki kościotwórcze; syntetyzują macierz organiczną (osteoid: kolagen I + proteoglikany + białka niekolagenowe) + inicjują mineralizację (pęcherzyki macierzy = matrix vesicles, ↑ALP alkaliczna fosfataza → ↑Pi + ↓PPi → HAP nukleacja); regulacja: PTH (PTH1R → Gs → ↑cAMP) + 1,25D (VDR) + IGF-1/GH (↑proliferacja) + BMP (bone morphogenetic protein) + Wnt (LRP5/6 → β-katenina → ↑osteoblastogeneza); po osadzeniu → dojrzewają do OSTEOCYTÓW (80–95% wszystkich komórek kostnych) lub BONE LINING CELLS', is_correct: true },
      { id: 'B', text: 'OSTEOKLASTY: wielojądrowe olbrzymy (2–100 jąder); pochodzenie: monocyty/makrofagi (linia mieloidalna); dojrzewanie: RANKL (na osteoblastach/limfocytach T) → RANK (receptor na preosteoklaście) → NF-κB + NFAT → fuzja → dojrzały osteoklast; OPG (osteoprotegeryna, z osteoblastów): "decoy receptor" dla RANKL → ↓osteoklastogeneza; aktywność resorpcyjna: "ruffled border" (fałdowana błona) → zamknięta lakuna Howship → H⁺ (V-ATPaza) + proteazy: katepsyna K, MMP → rozpuszczenie HAP + kolagenu; wskaźniki: TRAP (tartranian-resistant acid phosphatase), CTX (C-telopeptyd kolagenu)', is_correct: true },
      { id: 'C', text: 'OSTEOCYTY: dojrzałe osteoblasty uwięzione w lakunach kostnych; połączone długimi wyrostkami przez kanaliculi → sieć syncytialna; FUNKCJE: (1) mechanosensoring: odkształcenie kości → przepływ płynu przez kanaliculi → Ca²⁺ + NO + PGE2 → sygnały do osteoblastów/osteoklastów; (2) produkcja FGF-23 (fosfaturyna) + SOST (sklerostyna) → ↓osteoblasty (parakrynne); (3) "perilacunar remodeling": lokalne lakkuny powiększane przez osteoklastyczną aktywność osteocytów; SCLEROSTIN: inhibitor Wnt (LRP5/6 antagonizm) → ↓osteoblastogeneza; romosozumab (anty-SOST Ab) → ↑kość', is_correct: true },
      { id: 'D', text: 'Osteoblasty są wielojądrowymi komórkami olbrzymimi powstającymi z monocytów; osteoklasty produkują kolagen i macierz organiczną kości; OPG (osteoprotegeryna) jest ligandem dla RANK i stymuluje resorpcję kości; osteocyty nie mają funkcji mechanosensorycznej; RANKL stymuluje osteoblastogenezę (nie osteoklastogenezę); alkaliczna fosfataza (ALP) jest markerem resorpcji kości (nie kościotworzenia)', is_correct: false },
    ],
    correct_answer: ['A', 'B', 'C'],
    explanation: '(A) BMP (BONE MORPHOGENETIC PROTEINS): TGF-β superfamily; BMP2/4/7 → BMPR2/ALK2,3,6 → SMAD1/5/8 → CBF-α1/RUNX2 (master TF osteoblastogenezy); NOCOGGIN (inhibitor BMP) → ↓osteoblastogeneza; WĄTROBA vs KOŚĆ ALP: ALP całkowita w surowicy: wątrobowa (najobfitsza) + kostna + jelitowa + łożyskowa; kostna ALP (BAP): specyficzny marker kościotworzenia; ↑w: Paget, osteomalacja, przerzuty kostne, HPT pierwotny; (B) KATEPSYNA K (CTSK): cysteinowa proteaza; główna proteinaza osteoklastyczna do kolagenu I; mutacja CTSK → pyknodesostoza (Toulouse-Lautrec disease); odontol CII (katepsyna K inhibitor, odanacatib) → ↓resorpcja; BISFOSFONIANY: analogi pirofosforanu → inkorporują się do HAP w "ruffled border" → spożywane przez osteoklasty → inhibicja FPP syntazy (farnesylopirofosforanu) → ↓prenylacja Ras/Rho → apoptoza osteoklastów; DENOSUMAB: anty-RANKL Ab (IgG2) → ↓osteoklastogeneza → ↓resorpcja → ↑BMD; (C) SCLEROSTIN KLINICZNE: SCLEROSTEOSIS (mutacja SOST) + VAN BUCHEM DISEASE → ↑BMD (brak hamowania Wnt) → kości nadmiernie gęste → ucisk nerwów; romosozumab (evenity): anty-SOST + promouje formację + hamuje resorpcję; Postmenopausal osteoporosis 1 rok terapii; D — Fałsz: osteoblasty: jednojądrzaste, z mezenchymy; osteoklasty: resorpcja (nie synteza); OPG: HAMUJE resorpcję (decoy RANKL); osteocyty: kluczowy mechanosensor; RANKL: osteoklastogeneza; ALP: marker KOŚCIOTWORZENIA.',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },
  {
    topic_id: TOPIC, subtopic_id: S.kostna, question_type: 'single',
    question_text: 'Kość może być zbudowana na dwa sposoby pod względem mikrostruktury. Które stwierdzenie POPRAWNIE opisuje różnicę między kością zbitą (kortykalną) a kością gąbczastą (beleczkową)?',
    options: [
      { id: 'A', text: 'KOŚĆ ZBITA (kortykalna, compacta): 80% masy szkieletu; twarda zewnętrzna powłoka długich kości (diafiza) i blaszki kości płaskich; mikrostruktura: OSTEON (system Haversa): cylindryczne jednostki Ø ~200 μm; centrał: kanał Haversa (naczynie, nerw) → koncentryczne blaszki lamelarne (3–20) → lakkuny z osteocytami + kanaliculi; kanały Volkmanna: łączą kanały Haversa poprzecznie + z periosteum; funkcja: mechaniczna (wytrzymałość, ochrona); metabolicznie mniej aktywna; KOŚĆ GĄBCZASTA (beleczkowa, spongiosa): 20% masy; beleczki i płytki (trabeculae) → sieć 3D; bez osteonów → osteocyty w lakunach blaszek beleczkowych; kanały szpiku → szpik czerwony (hematopoeza) lub żółty (tłuszcz); metabolicznie bardzo aktywna (↑powierzchnia); lokalizacja: trzony kręgów, głowy kości długich, kości płaskie (diploe)', is_correct: true },
      { id: 'B', text: 'Kość zbita nie ma mikrostruktury (jest jednorodna jak cement); osteon (system Haversa) jest strukturą kości gąbczastej; kość gąbczasta jest cięższa od kości zbitej; kanały Haversa biegną prostopadle do osi długiej kości; kość zbita nie ma unaczynienia; szpik kostny żółty jest miejscem hematopoezy u dorosłych; kość gąbczasta stanowi 80% masy szkieletu', is_correct: false },
      { id: 'C', text: 'Kość zbita jest zbudowana z beleczek bez określonej orientacji; osteon jest nieunaczynioną strukturą; osteocyty w kości zbitej są zlokalizowane na powierzchni kości (nie w lakunach); kanały Volkmanna biegną równolegle do osi długiej kości (jak kanały Haversa); kość gąbczasta zajmuje wyłącznie epifizę i jest całkowicie pozbawiona aktywności metabolicznej; periosteum jest błoną wyściełającą szpik kostny', is_correct: false },
      { id: 'D', text: 'Osteony (systemy Haversa) są charakterystyczne dla kości gąbczastej, a kość zbita ma strukturę beleczkowatą; kanały Haversa łączą się poprzecznie kanałami Volkmanna (prawda), ale oba są wypełnione szpikiem (błąd: są wypełnione naczyniami i nerwami); kość gąbczasta jest odporna na ściskanie ze względu na swój lity charakter; periosteum jest obecne na wewnętrznej powierzchni kości; diploe to przestrzeń między blaszkami kości długich (powinno być kości płaskich)', is_correct: false },
    ],
    correct_answer: ['A'],
    explanation: 'MECHANIKA KOŚCI: KOŚĆ ZBITA: wytrzymałość na zginanie i skręcanie (diaphysis rur długich — minimalizuje masę przy max. wytrzymałości); orientacja osteonów: równolegle do osi długiej kości → optymalne dla sił ściskania wzdłuż osi; KOŚĆ GĄBCZASTA: trabeculae orientowane wzdłuż linii naprężeń (Wolff\'s law) → architekttura truss (kratownica) → min masa, max absorbcja energii; → osteoporoza: ↓grubość + ↓liczba beleczek + dezorganizacja → ↑ryzyko złamania (szczególnie trzon kręgowy + szyjka kości udowej); REMODELING: BMU (basic multicellular unit): osteoklasty (resorpcja, 2–3 tyg.) → osteoblasty (wypełniają, 3–4 mies.); lokalizacja: intrakortykalne (w osteonach) + endostalne (powierzchnia spongiosa); cykl: resorpcja → reversal → formacja; PERIOSTEUM vs ENDOSTEUM: periosteum: zewnętrzna okostna (2 warstwy: fibrous + osteogenic); bardzo unerwiona → ból przy złamaniu; endosteum: wewnętrzna okostna (jama szpikowa + trabekularna powierzchnia); cienka, bogata w komórki; LAMELLARNOŚĆ: dojrzała kość = lamelarna (blaszki); pierwotna/wczesnopłodowa = splotowata (woven bone): szybka, nieuporządkowana → złamanie naprawcze, Paget, nowotwory (↑woven).',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },
  {
    topic_id: TOPIC, subtopic_id: S.kostna, question_type: 'true_false',
    question_text: 'Oceń prawdziwość poniższych stwierdzeń dotyczących procesu kostnienia (ossification):',
    options: [
      { id: 'A', text: 'KOSTNIENIE ŁĄCZNOTKANKOWE (desmalne, intramembranous): tkanka mezenchymalna → bezpośrednio osteoblasty (bez modelu chrzęstnego); dotyczy: kości płaskie czaszki (ciemieniowe, czołowe) + żuchwa + obojczyk; centrum kostnienia pierwotne → osteoblasty syntetyzują osteoid → mineralizacja → osteony; przez całą embriogenegę i w ciągu życia (naprawa złamań flat bones); ciemiączka (fonticuli) — obszary niezwapnionej tkanki łącznej między kośćmi sklepienia czaszki → zrastają się do 18–24 m.ż. (wielkie ciemiączko) i 2–3 m.ż. (małe)', is_correct: true },
      { id: 'B', text: 'KOSTNIENIE CHRZĘSTNOZASTĘPCZE (enchondral): szablon chrzęstny (model hyalinowy) → zastępowany kością; etapy: (1) kondensacja mezenchymy → chondroblasty → chrząstka; (2) perichondrium → strefa hialinowa powiększa się; (3) chondrocyty hypertroficzne → ↑ALP + ↑VEGF → apoptoza + naczynia → osteoprogenitory; (4) pierwotne centrum kostnienia (diaphysis, płodowe): osteoklasty usuwają chrząstkę + osteoblasty kładą kość; (5) wtórne centrum kostnienia (epiphysis, wiek noworodkowy–nastolatek): między → chrząstka nasadowa (growth plate, physis); (6) zamknięcie nasad (closure): kobiety 18–20, mężczyźni 20–25', is_correct: true },
      { id: 'C', text: 'Kości długie (np. kość udowa) kościeją przez kostnienie łącznotkankowe (desmalne) bez szablonu chrzęstnego; chrząstka nasadowa (growth plate) produkuje kość przez aktywność osteoblastów chrzęstnych (chondroblastów, które stają się osteoblastami in situ); ciemiączka na głowie noworodka to niezwapnione chrząstki szkliste; obojczyk kościeje wyłącznie enchondralnie; centrum ossyficacji wtórne (epifizalne) pojawia się u płodów w 3. miesiącu ciąży', is_correct: false },
    ],
    correct_answer: ['A', 'B'],
    explanation: 'A — Prawda: CRANIOSYNOSTOSIS: przedwczesne zamknięcie szwów → ↑ICP (ucisk na mózg) + deformacja czaszki; pozew: scaphocephaly (sagital syn.), trigonocephaly (metopic), plagiocephaly (coronal/lambdoid); leczenie: chirurgiczne otwarcie szwu; FONTANELLES: duże (anteriorne): zamknięcie 18 m. (u pacjentów z rachityzmem, niedoczynność tarczycy → opóźnione); małe (posteriorne): 6–8 tygodni; pulsujące ciemiączko → echo ICP; B — Prawda: GROWTH PLATE ZONES (OD EPIFIZALNE DO DIAFIZALNE): (1) reservoir (resting) zone: spoczynkowe chondrocyty; (2) proliferative zone: kolumny chondrocytów ↑mitoza → GH/IGF-1 → ↑elongacja; (3) hypertrophic zone: ↑chondrocyty (5-10×), ↑ALP → mineralizacja macierzy chrzęstnej; (4) provisional calcification: wapnienie chrząstki; (5) ossification zone: naczynia + osteoblasty → kość; REGULACJA WZROSTU KOŚCI: GH (somatotropy) → IGF-1 (wątrobowy + lokalny) → ↑proliferacyjna zona; PTHrP (parathyroid hormone related peptide z chrząstki) → PTH1R → ↓hypertrophy (hamuje za wczesne); Ihh (indian hedgehog, z hypertroficznych) → PTHrP + ↑osteoblasty; FGF (FGFR3): negatywny regulator (achondroplazja: FGFR3 gain-of-function mutation → ↓proliferacja → karłowatość); C — Fałsz: kości długie: ENCHONDRALNIE (nie desmalne); chrząstka nasadowa: odrębne chondrocyty + napływające osteoblasty z okostnej (nie to samo); ciemiączka: łączna tkanka (nie chrząstka); obojczyk: DESMALNE (jeden z nielicznych wyjątków + śródbłonkowe centrum); wtórne centrum epifizalne: POPORODOWO (przy urodzeniu zazwyczaj tylko pierwotne, wtórne pojawiają się od 0–3 lat zależnie od kości).',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },
  {
    topic_id: TOPIC, subtopic_id: S.kostna, question_type: 'single',
    question_text: 'Przebudowa (remodeling) kości jest procesem ciągłym przez całe życie. Który opis POPRAWNIE wyjaśnia znaczenie i regulację remodelingu kostnego?',
    options: [
      { id: 'A', text: 'REMODELING KOSTNY: proces zastępowania starej kości nową; cel: (1) naprawa mikrouszkodzeń (fatigue cracks) — kumulacyjne → złamanie bez remodelingu; (2) utrzymanie homeostazy mineralnej (Ca²⁺ i PO₄³⁻); (3) adaptacja architektoniki do obciążeń mechanicznych (prawo Wolffa: kość przebudowuje wzdłuż linii naprężeń); obrót kostny (bone turnover): ok. 10% szkieletu rocznie; u dzieci: wyższy (wzrost); menopauzalnie: ↑resorpcja > formacja → ↑obrót → ↓BMD; MARKERY SUROWICZE: formacja: ALP kostna (BAP), osteokalcyna (OC), P1NP (prokolagen I N-propeptyd); resorpcja: CTX-I (β-crosslaps, C-telopeptyd kolagenu I), NTX, TRAP-5b (tartranian-resistant ACP 5b)', is_correct: true },
      { id: 'B', text: 'Remodeling kostny zachodzi wyłącznie w kościach gąbczastych (nie w zbitych); celem remodelingu jest wyłącznie regulacja stężenia glukozy we krwi (nie Ca²⁺); kość nie podlega mikrouszkodzeniom przy normalnym użytkowaniu; prawo Wolffa mówi, że kość przebudowuje się prostopadle do linii naprężeń; markery resorpcji kości to ALP i osteokalcyna; remodeling jest aktywny wyłącznie u dzieci', is_correct: false },
      { id: 'C', text: 'Osteoklasty działają przed osteoblastami w cyklu remodelingu (kość najpierw naprawa, potem resorpcja); obrót kostny u zdrowego dorosłego obejmuje 80% szkieletu rocznie; PTH hamuje aktywność osteoblastów i zmniejsza remodeling; wzrost mechaniczny (ćwiczenia) zmniejsza gęstość kości przez prawo Wolffa; CTX-I jest markerem kościotworzenia; menopauza zmniejsza resorpcję kości przez ↓estrogenu', is_correct: false },
      { id: 'D', text: 'Sekwencja remodelingu: osteoblasty (formacja) → osteoklasty (resorpcja) — czyli resorpcja zawsze następuje PO formacji; BMU (basic multicellular unit) zawiera tylko osteoblasty; P1NP jest markerem resorpcji (nie formacji); prawo Wolffa dotyczy wyłącznie chrząstki; bisfosfoniany blokują kościotworzenie (nie resorpcję)', is_correct: false },
    ],
    correct_answer: ['A'],
    explanation: 'SEKWENCJA BMU (BASIC MULTICELLULAR UNIT): ACTIVATION → RESORPTION → REVERSAL → FORMATION → QUIESCENCE (ARFQ): (1) Aktywacja (1–3 d): mechaniczne/chemiczne sygnały → "bone lining cells" cofają się → osteoclast progenitors rekrutacja; (2) Resorpcja (2–4 tyg.): osteoklasty → lakuny Howship → ↑Ca²⁺ + PO₄³⁻ + kolagen fragmenty (CTX) w surowicy; (3) Reversal (1–2 tyg.): osteoblast progenitors rekrutacja (TGF-β, IGF-1 z macierzy); (4) Formacja (3–4 mies.): osteoblasty → osteoid → mineralizacja; (5) Spoczynek: "lining cells" przykrywają; CORTICAL BMU: przebija tunel (cutting cone: osteoklasty) → filling cone (osteoblasty) → nowy osteon; trabecular BMU: na powierzchni beleczek; COUPLING: osteoklasty → ↑TGF-β, IGF-1, BMP, PDGF z macierzy → ↑osteoblasty; EFEKTYWNOŚĆ: szczyt BMD: kobiety 25–30 lat; mężczyźni 30–35; po szczyt → powolna utrata; menopauza: ↓E2 → ↑RANKL (T-komórki, synovialne fibroblasty) + ↓OPG → ↑osteoklasty → high turnover osteoporosis; CALCIUM-PTH OS: ↓Ca²⁺ → ↑PTH → ↑osteoklasty (szybki Ca²⁺) + ↑nerkowa Ca²⁺ reabsorpcja + ↑1,25D → ↑jelitowe Ca²⁺ + ↑resorpcja.',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },
  {
    topic_id: TOPIC, subtopic_id: S.kostna, question_type: 'multiple',
    question_text: 'Które z poniższych stwierdzeń POPRAWNIE opisują chrząstkę i jej rodzaje? (zaznacz wszystkie prawdziwe)',
    options: [
      { id: 'A', text: 'CHRZĄSTKA SZKLISTA (hyalinowa): najobfitsza; kolagen II + aggrekan (duży PG z chondroitn/keratansiarczan, GAG) → wysoka zawartość wody (70–80%) → wytrzymałość na ściskanie; brak naczyń (odżywianie: dyfuzja) + brak nerwów + brak naczyń limfatycznych; chondrocyty w lakunach (izogrupach = isogenous groups); perichondrium (ochrzęstna): zewnętrzna okostna chrząstki → źródło chondroblastów; LOKALIZACJA: końce nasad (articular cartilage), żebra (chrząstki żebrowe), krtań/tchawica/oskrzela; chrząstka stawowa: bez perichondrium (odżywianie z mazi stawowej)', is_correct: true },
      { id: 'B', text: 'CHRZĄSTKA WŁÓKNISTA (fibrocartilage): kolagen I + II (dominuje I → ↑wytrzymałość na rozciąganie); brak perichondrium; chondrocyty w rzędach/kolumnach; LOKALIZACJA: krążki międzykręgowe (annulus fibrosus + nucleus pulposus [galaretowaty, duże PG]), łąkotki kolana, spojenie łonowe, wstawka ścięgien/więzadeł do kości; funkcja: absorpcja sił ścinających + kompresji; HERNIATION: nucleus pulposus wypycha przez annulus → ucisk korzenia/rdzenia = rwa kulszowa lub ból szyjny', is_correct: true },
      { id: 'C', text: 'CHRZĄSTKA SPRĘŻYSTA (elastyczna): kolagen II + ELASTYNA (włókna elastyczne) + fibrylin; zachowuje kształt po odkształceniu; koloru żółtego (elastyna); bez perichondrium; LOKALIZACJA: małżowina uszna (auricula), nagłośnia (epiglottis), trąbka słuchowa (Eustachiusza), krtań (niektóre chrząstki: III/A,corniculate,cuneiform); ELASTIN gen (ch7): mutacje → Williams syndrome (elfin face + kardiovascularne + superuczucia muzyki) lub supravalvular aortic stenosis (SVAS)', is_correct: true },
      { id: 'D', text: 'Chrząstka szklista zawiera kolagen I (jak kość) a włóknista zawiera kolagen II (jak chrząstka szklista); chrząstka nie posiada komórek (jest acelularna); perichondrium jest obecne we wszystkich rodzajach chrząstki (w tym w chrząstce stawowej i fibrocartilage); chrząstka stawowa jest unaczyniona przez sieć naczyń wnikających z kości podchrzęstnej; aggrekan jest białkiem kolagenowym', is_correct: false },
    ],
    correct_answer: ['A', 'B', 'C'],
    explanation: '(A) ARTICULAR CARTILAGE ZONES (od powierzchni): (1) superficial (tangential): kolagen II równolegle → mała tarcie; chondrocyty spłaszczone; (2) transitional (middle): kolagen ukośny; okrągłe chondrocyty; (3) deep (radial): kolagen prostopadle; kolumny; (4) calcified: mineralizacja → tidemark → integracja z kością podchrzęstną; DEGENERACJA: OA (osteoarthritis): ↓proteoglikany + ↓kolagen II → ↓wodochłonność → ↑obciążenie kości podchrzęstnej → ból + osteofity; (B) IVD (INTERVERTEBRAL DISC): ANNULUS FIBROSUS: kilkanaście warstw fibrocartilage (kolagen I, ukośnie orientowany) → resist rotacja + kompresja; NUCLEUS PULPOSUS: notochord remnant; duże PG (aggrekan, versykan) → wysoka zawartość wody → hydrostatyczne ciśnienie przy kompresji; DISC DEGENERATION: ↓woda + ↓PG + ↑kolagen I → ↓wysokość dysku → ↑zakres ruchu → ↑annulus tears → herniation; (C) ELASTIN BIOLOGIA: tropoelastyna → LOX (lysyl oxidase) → crosslinki (desmozyna, izodesmozyna) → elastyna; fibryliny (FBN1, FBN2): scaffold dla elastyny; MARFAN: FBN1 mutacja → ↓fibrilin → ↓TGF-β sekwestracja → ↑TGF-β → aorta aneuryzm + ectopia lentis + arachnodactyly; D — Fałsz: szklista: kolagen II; włóknista: kolagen I (dominuje); chrząstka MA komórki (chondrocyty); fibrocartilage + stawowa: BEZ perichondrium; chrząstka stawowa: NIEUNACZYNIONA; aggrekan: proteoglikan (nie kolagen).',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },
  {
    topic_id: TOPIC, subtopic_id: S.kostna, question_type: 'single',
    question_text: 'Osteoporoza jest najczęstszą chorobą metaboliczną kości. Który opis POPRAWNIE wyjaśnia patofizjologię i podział osteoporozy?',
    options: [
      { id: 'A', text: 'OSTEOPOROZA: ↓BMD (gęstość mineralna kości) + ↓jakość mikroarchitektury → ↑ryzyko złamania niskoenergetycznego; KLASYFIKACJA: (1) PIERWOTNA: typ I (postmenopauzalna): kobiety 50–70 lat; ↓E2 → ↑RANKL + ↓OPG → ↑osteoklasty → high-turnover → ↑resorpcja spongiosa → złamania trzonów kręgów + dystalny promień; typ II (starcza): oba płcie > 75 lat; ↓1,25D + ↓Ca²⁺ jelitowe + ↑PTH wtórny → kortykal + trabecular utrata → szyjka kości udowej; (2) WTÓRNA: GKS-indukowana (najczęstsza wtórna), hipertyreoza, hiperparathyroidyzm, CKD, malabsorpcja; DIAGNOZA: DXA (dual-energy X-ray absorptiometry): T-score: ≥ −1 norma; −1 do −2.5 = osteopenia; ≤ −2.5 = osteoporoza', is_correct: true },
      { id: 'B', text: 'Osteoporoza jest chorobą wyłącznie kości gąbczastej; T-score > −1 oznacza osteoporozę; typ I osteoporozy dotyczy mężczyzn po 75. roku życia; ↓estrogen powoduje ↓osteoklasty i ↓resorpcję; GKS (glikokortykosteroidy) chronią przed osteoporozą; bisfosfoniany są wskazane wyłącznie w osteoporozie stępowatej; BMD (bone mineral density) mierzy się metodą PET', is_correct: false },
      { id: 'C', text: 'Osteoporoza jest definiowana jako T-score < −3.5 w DXA; typ II osteoporozy dotyczy wyłącznie kobiet przed menopauzą; PTH (parathormon) w osteoporozie jest obniżony (nie podwyższony); GKS-indukowana osteoporoza dotyczy wyłącznie kości czaszki; bisfosfoniany zwiększają resorpcję kości; złamania szyjki kości udowej są typowe dla osteoporozy typ I (postmenopauzalnej, dominuje spongiosa)', is_correct: false },
      { id: 'D', text: 'Osteoporoza powoduje ↑mineralizację macierzy kostnej (nie ↓); osteoblasty są hiperaktywne w osteoporozie; złamania kręgowe są typowe wyłącznie dla stępowatej osteoporozy (typ II); RANKL zmniejsza osteoklastogenezę; DXA mierzy stężenie Ca²⁺ we krwi; estrogen zwiększa RANKL i zmniejsza OPG', is_correct: false },
    ],
    correct_answer: ['A'],
    explanation: 'OSTEOPOROZA — LECZENIE: PROFILAKTYKA: Ca²⁺ (1000–1200 mg/d) + witamina D (800–1000 IU/d) + aktywność fizyczna (obciążeniowa) + unikanie tytoniu/alkoholu; FARMAKOLOGIA: (1) BISFOSFONIANY: alendronat, rizedronat, ibandronian, zoledronat (iv 1×rok); hamowanie FPP syntazy → ↓prenylacja Ras/Rho → apoptoza osteoklastów; efekty uboczne: esophageal irritation (oralne) + ONJ (osteonecrosis of jaw, przy iv) + ATF (atypical femur fracture, long-term); (2) DENOSUMAB: anty-RANKL Ab; ↓osteoklastogeneza; efekt: szybki; trzeba kontynuować (rebound resorption przy odstawieniu); (3) TERYPARATYD/ABALOPARATYD: PTH analogu (anaboliczne); ↑osteoblasty; wskazanie: ciężka OP + złamania lub failed bisfosfoniany; (4) ROMOSOZUMAB (anty-SOST): ↑formacja + ↓resorpcja; 12 mies. kurs; (5) SELEKTYWNE MODULATORY ER: raloksyfen: ER agonista w kości → ↑BMD + ↓ER antagonista w piersi → ↓CA; GKS-INDUCED OP: ↓Ca²⁺ jelitowe (↓1,25D) + ↑Ca²⁺ nerkowe (↑ekskrecja) + ↓GH/IGF-1 + bezpośrednie: ↓osteoblastogeneza + ↑RANKL → ↑osteoklasty; leczenie: bisfosfoniany PROFILAKTYCZNIE gdy ≥ 3 m. GKS w dawce ≥ 5 mg/d prednizonu; ZŁAMANIA OSTEOPOROTYCZNE: szyjka kości udowej (20% hospitalizowanych umiera w 1 rok); trzon kręgowy (ból pleców + kyphosis = "wdowy garb"); dystalny promień (Colles\' fracture).',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },
  {
    topic_id: TOPIC, subtopic_id: S.kostna, question_type: 'true_false',
    question_text: 'Oceń prawdziwość poniższych stwierdzeń dotyczących roli czynników hormonalnych i mechanicznych w regulacji masy kostnej:',
    options: [
      { id: 'A', text: 'ESTROGENY I KOŚĆ: E2 → ERα na osteoblastach i osteoklastach → ↑OPG + ↓RANKL → ↓osteoklasty + ↑apoptoza osteoklastów; E2 → ↑TGF-β (pro-apoptotyczny dla osteoklastów); E2 → ↑IL-6 (pro-osteoklastyczny) ← TO SĄ SPRZECZNOŚCI: główny efekt E2 = ANTI-RESORPTIVE; menopauza: ↓E2 → ↑IL-6, IL-1, TNF (z monocytów/T-limfocytów) → ↑RANKL → ↑osteoklasty → ↑resorpcja; PRAWO WOLFFA (MECHANOTRANSDUKCJA): wzrost mechaniczny → osteocyty (płyn w kanaliculach → PLC → Ca²⁺ + NO + PGE2) → ↑osteoblastogeneza + ↓SOST (sklerostyna) → ↑Wnt → ↑osteoblasty; brak obciążenia (immobilizacja, kosmonauta) → ↑resorpcja + ↓formacja → ↓BMD', is_correct: true },
      { id: 'B', text: 'WAPŃ I KOŚĆ: całkowity wapń organizmu ~1000 g; 99% w kości (HAP); 1% krew + płyny; norma Ca²⁺ surowicy: 8.5–10.5 mg/dl; REGULACJA DOBOWA: nocna resorpcja (↑PTH nocny) → wzrost Ca²⁺ rano; DOBOWY BILANS: u dorosłego: absorpcja jelitowa (Ca 200 mg) = ekskrecja nerkowa (Ca 200 mg) = wydzielanie kałowe (800 mg); ciąża: ↑absorpcja (↑1,25D) → pozytywny bilans dla płodu; laktacja: ok. 300 mg Ca/d idzie do mleka → ↑resorpcja kostna (PTHrP z sutka) → odwracalna utrata 5–10% BMD; po odstawieniu: odbudowa', is_correct: true },
      { id: 'C', text: 'Ćwiczenia statyczne (pływanie) bardziej zwiększają BMD niż obciążeniowe (bieg, trening siłowy); estrogen zwiększa osteoklastogenezę przez ↑RANKL; immobilizacja i stan nieważkości nie wpływają na metabolizm kostny; brak obciążeń mechanicznych stymuluje osteoblasty przez ↑sklerostynę (SOST); Ca²⁺ w surowicy stanowi 99% całkowitego wapnia w organizmie; norma T-score wynosi > −2.5', is_correct: false },
    ],
    correct_answer: ['A', 'B'],
    explanation: 'A — Prawda: MECHANOTRANSDUKCJA DETALE: PIEZOELECTRIC efekt: odkształcenie kości → lokalne pole elektryczne → stymulacja komórek kostnych; osteocyty: CONNEXIN 43 (Cx43) hemi-kanały + gap junctions → ATP/PGE2/NO do środowiska; YAP/TAZ (mechanosensory TF): ↑obciążenie → ↑YAP/TAZ → jądro → ↑Wnt5a → ↑osteoblastogeneza; PIEZOELECTRIC BONE STIMULATORS: PEMF (pulsed electromagnetic field) → ↑osteoblasty → wspomaganie gojenia złamań (FDA zatwierdzone); ASTRONAUCI: 1–2% BMD/miesiąc utraty w stanie nieważkości → ↑Ca²⁺ w moczu → ↑ryzyko kamicy; leczenie: bisfosfoniany (profilaktyczne dla misji długotrwałych); B — Prawda: ABSORPCJA JELITOWA Ca: aktywna (25D-zależna): TRPV6 (apikalna błona enterocytów jelita czczego/krętego) + calbindin D9k (cytoplazmatyczny nośnik) + PMCA1b (bazolateralny; Ca²⁺-ATPaza) → 30–40% z pożywienia wchłaniane; bierna (paracelularna): niespecyficzna, proporcjonalna do stężenia; 1,25D: ↑TRPV6 + ↑calbindin + ↑PMCA → ↑absorpcja; lakoza (z mleka) + kwasowe środowisko → ↑absorpcja; szczawiany (szpinak) + fityniany (ziarna) → chelacja Ca → ↓absorpcja; C — Fałsz: obciążeniowe: silniej niż aerobowe bez obciążenia; pływanie: ↑mięśnie ale ↓wpływ na BMD vs bieg; E2: HAMUJE osteoklasty (antyresorptywne); immobilizacja: ↑resorpcja; brak obciążeń → ↑SOST → ↑hamowanie osteoblastów; 99% Ca: W KOŚCI (nie surowicy); T-score norma: ≥ −1.0.',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },

  // ── KOŚCI I ICH POŁĄCZENIA (2) ────────────────────────────────────────────
  {
    topic_id: TOPIC, subtopic_id: S.kosci, question_type: 'single',
    question_text: 'Szkielet człowieka zbudowany jest z różnych typów kości. Które stwierdzenie POPRAWNIE klasyfikuje kości według kształtu i podaje przykłady?',
    options: [
      { id: 'A', text: 'KLASYFIKACJA KOŚCI WG KSZTAŁTU: (1) DŁUGIE (ossa longa): jedna oś dłuższa niż poprzeczna; epifiza (dwa końce) + diafiza (trzon) + metafiza (między); jama szpikowa (medullary cavity); przykłady: kość udowa (femur), piszczelowa (tibia), strzałkowa (fibula), ramieniowa (humerus), promieniowa (radius), łokciowa (ulna), śródstopne, śródręczne, paliczki (dłuższe); (2) KRÓTKIE (ossa brevia): zbliżone 3 wymiary; np. kości nadgarstka (carpal), stępu (tarsal); (3) PŁASKIE (ossa plana): 2 blaszki zbitej + diploe (gąbczasta); np. kości czaszki (ciemieniowa, czołowa, potyliczna), łopatka, mostek, miednica (os ilium); (4) NIEREGULARNE (ossa irregularia): kręgi, kość klinowa, jarzmowa, żuchwa; (5) TRZESZCZKI (ossa sesamoidea): w ścięgnach; patella (rzepka) — największa', is_correct: true },
      { id: 'B', text: 'Kość udowa jest kością krótką; żebra należą do kości długich; patella (rzepka) jest kością płaską; kości nadgarstka są kościami długimi; kości czaszki należą do kości nieregularnych; mostek jest kością długą; kości śródstopia to kości krótkie; kręg jest kością krótką (nie nieregularną); miednica należy do kości długich', is_correct: false },
      { id: 'C', text: 'Kości płaskie mają jamę szpikową jak kości długie; diploe to sieć naczyń śródbłonkowych w kościach długich; kości krótkie (np. kość udowa) są zbudowane wyłącznie z kości gąbczastej bez otoczki zbitej; trzeszczki (sesamoid) to kości całkowicie pozbawione okostnej; kości czołowa i ciemieniowa są kościami nieregularnymi; żebra to kości długie ze względu na swoją długość', is_correct: false },
      { id: 'D', text: 'Kości krótkie (np. kości nadgarstka) mają epifizę, diafizę i metafizę jak kości długie; kości płaskie (np. łopatka) nie mają gąbczastej warstwy wewnętrznej; kości nieregularne (np. kręgi) są zbudowane wyłącznie z kości zbitej; kość piszczelowa (tibia) jest kością płaską; patella nie jest kością trzeszczkowatą; kość klinowa (os sphenoidale) jest kością płaską', is_correct: false },
    ],
    correct_answer: ['A'],
    explanation: 'ZNACZENIE KLINICZNE TYPÓW KOŚCI: KOŚCI DŁUGIE: złamania: Salter-Harris classification (złamania przez growth plate u dzieci): typ I–V; typ II najczęstszy (przez growth plate + metafizę); lokalizacja szpiku: diafiza → żółty szpik (tłuszcz) u dorosłych; epifiza → czerwony szpik; RED MARROW SITES U DOROSŁYCH: trzon kręgowy + mostek + żebra + miednica (os ilium) + bliższy koniec kości udowej i ramiennej; ŻEBRA: kości o kształcie pośrednim (długie ale zbudowane jak płaskie), dlatego często klasyfikowane jako "płaskie" lub jako osobna kategoria "pneumatized" (żebra, bo zawierają szpik); DIPLOE: w kościach płaskich: dwie blaszki zbitej (table externa + interna) oddzielone gąbczastą (diploe z żyłami diploę) → udar: epidural hematoma (middle meningeal artery między tablicą wew. a oponą twardą); SESAMOID KOŚCI: w obrębie ścięgien + chroniące przed tarciem; oprócz rzepki: 2 kości sezamowate pod głową I śródkostną stopy (często widoczne na Rtg); pisiform (kość grochowata) = sesamoid w ścięgnie mięśnia łokciowego nadgarstka.',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },
  {
    topic_id: TOPIC, subtopic_id: S.kosci, question_type: 'true_false',
    question_text: 'Oceń prawdziwość poniższych stwierdzeń dotyczących połączeń kości (articulatio):',
    options: [
      { id: 'A', text: 'POŁĄCZENIA KOŚCI — KLASYFIKACJA: (1) SYNARTHROSES (połączenia nieruchome): szwy (suturae): między kościami czaszki; materiał łączący: tkanka łączna włóknista; całkowita fusion (synostoza) u dorosłych; SYNDESMOZA: więzadło / błona łącznotkankowa; np. więzozrost kości piszczelowej i strzałkowej (tibiofibular); CHRZĘSTOZROST (synchondrosis): chrząstka szklista; np. chrząstki żebrowe, nasadowe; SYMPHYSIS: fibrocartilage; np. spojenie łonowe, krążki miedzykręgowe; (2) DIARTHROSES (stawy maziowe, synovial): jama maziowa + maź stawowa; nieograniczona ruchomość; większość stawów kończyn', is_correct: true },
      { id: 'B', text: 'RODZAJE STAWÓW MAZIOWYCH wg KSZTAŁTU: (1) zawiasowy (ginglimus): ruch w 1 płaszczyźnie (zgięcie/wyprost); np. staw łokciowy (humeroulnar), staw skokowo-goleniowy, stawy międzypaliczkowe IP; (2) obrotowy (trochoid): obrót wokół osi pionowej; np. staw promieniowo-łokciowy bliższy (radial head), staw szczytowo-obrotnikowy (atlanto-axial); (3) elipsoidalny (condyloid): 2 osie; np. staw promieniowo-nadgarstkowy (radiocarpal), MCP (śródręczno-paliczkowy); (4) siodłowy (sellaris): 2 osie, większy zakres; np. CMC kciuka (carpometacarpal I thumb); (5) kulisty (spheroideus): 3 osie; np. staw biodrowy, barkowy; (6) płaski (planus): ślizgowy; np. stawy nadgarstka, stępu', is_correct: true },
      { id: 'C', text: 'Szwy (suturae) czaszki są przykładem stawów maziowych z pełną ruchomością; chrząstozrost (synchondrosis) jest połączeniem maziowym z jamą stawową; spojenie łonowe (symphysis pubica) jest stawem maziowym z maczią stawową; staw biodrowy jest stawem zawiasowym (ruch w 1 płaszczyźnie); staw łokciowy to staw kulisty; staw skokowo-goleniowy (górny skokowy) jest stawem elipsoidalnym', is_correct: false },
    ],
    correct_answer: ['A', 'B'],
    explanation: 'A — Prawda: SUTURAE CZASZKI NAZWY: coronalis (czołowy + ciemieniowe), sagittalis (między 2 ciemieniowymi), lambdoidalis (ciemieniowe + potyliczne); CIEMIĄCZKA: fonticulus anterior (grande, 4 rogi, rhomboid) + posterior (małe, trójkąt) + 2 boczne (anterolateral/sphenoidal + posterolateral/mastoideal); kraniosynostoza: przedwczesne zamknięcie → deformacja; KLINICZNE: FIBULA-TIBIA SYNDESMOZA: "high ankle sprain" — uszkodzenie więzozrostu → niestabilność stopy; leczenie: gips 6 tyg. lub fixation; SYMPHYSIS PUBICA: rozejście (symphysiolysis) w ciąży → ból łonowy; widoczne Rtg gdy szczelina > 10 mm; B — Prawda: KLINICZNE TYPY STAWÓW: CMC KCIUKA (siodłowy): arthroza CMC I (rhizarthrosis) = najczęstsza arthroza ręki; leczenie: szyna + iniekcja → artroplastyka (LRTI); STAW BARKOWY (kulisty): najbardziej ruchomy + najmniej stabilny (mała panewka = glenoid < 30% główki kości ramiennej); stabilność przez rotatory stawu barkowego (rotator cuff: supraspinatus, infraspinatus, teres minor, subscapularis = SITS); STAW BIODROWY (kulisty): głęboka panewka (acetabulum) + labrum → stabilny + mała ruchomość vs bark; C — Fałsz: szwy: SYNARTHROSIS (nieruchome); synchondrosis: chrząstka szklista (nie maziowy); symphysis: fibrocartilage (nie maziowy); staw biodrowy: KULISTY (3 osie); łokciowy: zawiasowy; skokowy-goleniowy: ZAWIASOWY (nie elipsoidalny).',
    difficulty: 2, verified: true, source: 'własne, wzorowane na CKE',
  },

]

function post(body) {
  return new Promise((resolve, reject) => {
    const data = Buffer.from(JSON.stringify(body), 'utf8')
    const req = https.request({
      hostname: 'gzpxvfaftvkfwpvljcrk.supabase.co',
      path: '/rest/v1/questions', method: 'POST',
      headers: {
        apikey: KEY, Authorization: 'Bearer ' + KEY,
        'Content-Type': 'application/json', Prefer: 'return=minimal',
        'Content-Length': data.length,
      },
    }, res => {
      let r = ''; res.on('data', c => r += c)
      res.on('end', () => resolve({ status: res.statusCode, body: r }))
    })
    req.on('error', reject); req.write(data); req.end()
  })
}

async function main() {
  console.log(`Seeding batch 1 (${questions.length} questions)...`)
  for (const q of questions) {
    const { status, body } = await post(q)
    const ok = status === 201 || status === 204
    if (!ok) console.log('ERR', status, body.slice(0, 200))
    else console.log('OK', `[${q.question_type}]`, q.question_text.slice(0, 60).replace(/\n/g, ' '))
  }
  console.log('Done.')
}
main().catch(err => { console.error(err); process.exit(1) })
